"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Owner(google.protobuf.message.Message):
    """Group owner"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    EMAILS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name of the owner"""
    @property
    def emails(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Email addresses for the group members"""

    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        emails: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_name", b"_name", "name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_name", b"_name", "emails", b"emails", "name", b"name"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_name", b"_name"]) -> typing.Literal["name"] | None: ...

Global___Owner: typing_extensions.TypeAlias = Owner

@typing.final
class Group(google.protobuf.message.Message):
    """Group owning a model, used for model notifications"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetaEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    META_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name of the group"""
    @property
    def owner(self) -> Global___Owner:
        """Group owner info"""

    @property
    def meta(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Arbitrary key-value metadata from the group definition"""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        owner: Global___Owner | None = ...,
        meta: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["owner", b"owner"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["meta", b"meta", "name", b"name", "owner", b"owner"]) -> None: ...

Global___Group: typing_extensions.TypeAlias = Group

@typing.final
class Groups(google.protobuf.message.Message):
    """Collection of groups defined in the project"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GROUPS_FIELD_NUMBER: builtins.int
    @property
    def groups(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Group]: ...
    def __init__(
        self,
        *,
        groups: collections.abc.Iterable[Global___Group] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["groups", b"groups"]) -> None: ...

Global___Groups: typing_extensions.TypeAlias = Groups
