"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.public.v1.common.vortex_telemetry_contexts_pb2
import dbtlabs.proto.public.v1.events.vortex_pb2
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CliInvocation(google.protobuf.message.Message):
    """Anonymous usage event for the dbt Charts CLI (dct). Each invocation emits a
    start/end pair linked by invocation_id. Sent unauthenticated, and only when
    dbt's anonymous usage stats opt-outs and DO_NOT_TRACK allow it.

    Contains no board names, query text, file paths, model/column names, or
    warehouse identifiers.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENRICHMENT_FIELD_NUMBER: builtins.int
    COMMON_CONTEXT_FIELD_NUMBER: builtins.int
    EVENT_ID_FIELD_NUMBER: builtins.int
    INVOCATION_ID_FIELD_NUMBER: builtins.int
    PROGRESS_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    PYTHON_VERSION_FIELD_NUMBER: builtins.int
    OS_NAME_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    DBT_LOCAL_COOKIE_USER_ID_FIELD_NUMBER: builtins.int
    RESULT_TYPE_FIELD_NUMBER: builtins.int
    DURATION_MS_FIELD_NUMBER: builtins.int
    event_id: builtins.str
    """Unique identifier for this event. A generated UUID."""
    invocation_id: builtins.str
    """Links the start and end events for the same command execution. A generated UUID."""
    progress: builtins.str
    """"start" or "end"."""
    command: builtins.str
    """Resolved command path from a fixed set of command names (e.g. "render",
    "cloud connect"). Never includes arguments.
    """
    version: builtins.str
    """dbt-charts package version."""
    python_version: builtins.str
    """Python interpreter version running dct."""
    os_name: builtins.str
    """Operating system name."""
    project_id: builtins.str
    """MD5 hash of the dbt project name (not the actual name), as Fusion does.
    Not the dbt platform project ID; that belongs in common_context.project_id.
    """
    dbt_local_cookie_user_id: builtins.str
    """The anonymous user id stored at ~/.dbt/.user.yml."""
    result_type: builtins.str
    """Exit status: "ok" or "error". Only set on end events."""
    duration_ms: builtins.int
    """Wall-clock execution time in milliseconds. Only set on end events."""
    @property
    def enrichment(self) -> dbtlabs.proto.public.v1.events.vortex_pb2.VortexMessageEnrichment:
        """Server-side enrichment (IP geolocation, client platform)."""

    @property
    def common_context(self) -> dbtlabs.proto.public.v1.common.vortex_telemetry_contexts_pb2.VortexTelemetryCommonContext: ...
    def __init__(
        self,
        *,
        enrichment: dbtlabs.proto.public.v1.events.vortex_pb2.VortexMessageEnrichment | None = ...,
        common_context: dbtlabs.proto.public.v1.common.vortex_telemetry_contexts_pb2.VortexTelemetryCommonContext | None = ...,
        event_id: builtins.str = ...,
        invocation_id: builtins.str = ...,
        progress: builtins.str = ...,
        command: builtins.str = ...,
        version: builtins.str = ...,
        python_version: builtins.str = ...,
        os_name: builtins.str = ...,
        project_id: builtins.str = ...,
        dbt_local_cookie_user_id: builtins.str = ...,
        result_type: builtins.str = ...,
        duration_ms: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["common_context", b"common_context", "enrichment", b"enrichment"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["command", b"command", "common_context", b"common_context", "dbt_local_cookie_user_id", b"dbt_local_cookie_user_id", "duration_ms", b"duration_ms", "enrichment", b"enrichment", "event_id", b"event_id", "invocation_id", b"invocation_id", "os_name", b"os_name", "progress", b"progress", "project_id", b"project_id", "python_version", b"python_version", "result_type", b"result_type", "version", b"version"]) -> None: ...

Global___CliInvocation: typing_extensions.TypeAlias = CliInvocation
