# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/anthropic_key.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import anthropic_key_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_anthropic__key__pb2
from dbtlabs.proto.private.v1.common import event_options_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_common_dot_event__options__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3dbtlabs/proto/private/v1/events/anthropic_key.proto\x12\x17v1.events.anthropic_key\x1a\x34\x64\x62tlabs/proto/private/v1/records/anthropic_key.proto\x1a\x33\x64\x62tlabs/proto/private/v1/common/event_options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n\x05\x41\x64\x64\x65\x64\x12/\n\ranthropic_key\x18\x01 \x01(\x0b\x32\x18.v1.records.AnthropicKey\x12&\n\x02ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp:\x17\x82\xb5\x18\x13\x41nthropic Key Added\"}\n\x07\x43hanged\x12/\n\ranthropic_key\x18\x01 \x01(\x0b\x32\x18.v1.records.AnthropicKey\x12&\n\x02ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp:\x19\x82\xb5\x18\x15\x41nthropic Key Changed\"}\n\x07Removed\x12/\n\ranthropic_key\x18\x01 \x01(\x0b\x32\x18.v1.records.AnthropicKey\x12&\n\x02ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp:\x19\x82\xb5\x18\x15\x41nthropic Key RemovedB:Z8github.com/dbt-labs/proto-golang/v1/events/anthropic_keyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.anthropic_key_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/dbt-labs/proto-golang/v1/events/anthropic_key'
  _globals['_ADDED']._loaded_options = None
  _globals['_ADDED']._serialized_options = b'\202\265\030\023Anthropic Key Added'
  _globals['_CHANGED']._loaded_options = None
  _globals['_CHANGED']._serialized_options = b'\202\265\030\025Anthropic Key Changed'
  _globals['_REMOVED']._loaded_options = None
  _globals['_REMOVED']._serialized_options = b'\202\265\030\025Anthropic Key Removed'
  _globals['_ADDED']._serialized_start=220
  _globals['_ADDED']._serialized_end=341
  _globals['_CHANGED']._serialized_start=343
  _globals['_CHANGED']._serialized_end=468
  _globals['_REMOVED']._serialized_start=470
  _globals['_REMOVED']._serialized_end=595
# @@protoc_insertion_point(module_scope)
