"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.api_request_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Received(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    API_REQUEST_FIELD_NUMBER: builtins.int
    @property
    def api_request(self) -> dbtlabs.proto.private.v1.records.api_request_pb2.ApiRequest: ...
    def __init__(
        self,
        *,
        api_request: dbtlabs.proto.private.v1.records.api_request_pb2.ApiRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["api_request", b"api_request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["api_request", b"api_request"]) -> None: ...

global___Received = Received
