# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/auth_provider.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import auth_provider_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_auth__provider__pb2
from dbtlabs.proto.private.v1.common import event_options_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_common_dot_event__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3dbtlabs/proto/private/v1/events/auth_provider.proto\x12\x17v1.events.auth_provider\x1a\x34\x64\x62tlabs/proto/private/v1/records/auth_provider.proto\x1a\x33\x64\x62tlabs/proto/private/v1/common/event_options.proto\"U\n\x07\x43hanged\x12/\n\rauth_provider\x18\x01 \x01(\x0b\x32\x18.v1.records.AuthProvider:\x19\x82\xb5\x18\x15\x41uth Provider ChangedB:Z8github.com/dbt-labs/proto-golang/v1/events/auth_providerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.auth_provider_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/dbt-labs/proto-golang/v1/events/auth_provider'
  _globals['_CHANGED']._loaded_options = None
  _globals['_CHANGED']._serialized_options = b'\202\265\030\025Auth Provider Changed'
  _globals['_CHANGED']._serialized_start=187
  _globals['_CHANGED']._serialized_end=272
# @@protoc_insertion_point(module_scope)
