"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.auth_provider_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Changed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTH_PROVIDER_FIELD_NUMBER: builtins.int
    @property
    def auth_provider(self) -> dbtlabs.proto.private.v1.records.auth_provider_pb2.AuthProvider: ...
    def __init__(
        self,
        *,
        auth_provider: dbtlabs.proto.private.v1.records.auth_provider_pb2.AuthProvider | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["auth_provider", b"auth_provider"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["auth_provider", b"auth_provider"]) -> None: ...

global___Changed = Changed
