"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.account_pb2
import dbtlabs.proto.private.v1.records.environment_pb2
import dbtlabs.proto.private.v1.records.run_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Usage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _KeyOwner:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _KeyOwnerEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Usage._KeyOwner.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        KEY_OWNER_UNSPECIFIED: Usage._KeyOwner.ValueType  # 0
        KEY_OWNER_DBT: Usage._KeyOwner.ValueType  # 1
        KEY_OWNER_BYOK: Usage._KeyOwner.ValueType  # 2

    class KeyOwner(_KeyOwner, metaclass=_KeyOwnerEnumTypeWrapper): ...
    KEY_OWNER_UNSPECIFIED: Usage.KeyOwner.ValueType  # 0
    KEY_OWNER_DBT: Usage.KeyOwner.ValueType  # 1
    KEY_OWNER_BYOK: Usage.KeyOwner.ValueType  # 2

    @typing.final
    class ModelsBuilt(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TOTAL_COUNT_FIELD_NUMBER: builtins.int
        SUCCESSFUL_COUNT_FIELD_NUMBER: builtins.int
        RUN_FIELD_NUMBER: builtins.int
        total_count: builtins.int
        successful_count: builtins.int
        @property
        def run(self) -> dbtlabs.proto.private.v1.records.run_pb2.Run: ...
        def __init__(
            self,
            *,
            total_count: builtins.int = ...,
            successful_count: builtins.int = ...,
            run: dbtlabs.proto.private.v1.records.run_pb2.Run | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["run", b"run"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["run", b"run", "successful_count", b"successful_count", "total_count", b"total_count"]) -> None: ...

    @typing.final
    class AccountHeartbeat(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ACCOUNT_FIELD_NUMBER: builtins.int
        DEVELOPER_SEATS_IN_USE_FIELD_NUMBER: builtins.int
        READ_ONLY_SEATS_IN_USE_FIELD_NUMBER: builtins.int
        TOTAL_SEATS_FIELD_NUMBER: builtins.int
        TOTAL_SEATS_IN_USE_FIELD_NUMBER: builtins.int
        EXPLORER_SEATS_IN_USE_FIELD_NUMBER: builtins.int
        MONTHLY_ACTIVE_DEVELOPERS_FIELD_NUMBER: builtins.int
        MONTHLY_ACTIVE_READ_ONLY_FIELD_NUMBER: builtins.int
        developer_seats_in_use: builtins.int
        read_only_seats_in_use: builtins.int
        total_seats: builtins.int
        total_seats_in_use: builtins.int
        explorer_seats_in_use: builtins.int
        monthly_active_developers: builtins.int
        monthly_active_read_only: builtins.int
        @property
        def account(self) -> dbtlabs.proto.private.v1.records.account_pb2.Account: ...
        def __init__(
            self,
            *,
            account: dbtlabs.proto.private.v1.records.account_pb2.Account | None = ...,
            developer_seats_in_use: builtins.int = ...,
            read_only_seats_in_use: builtins.int = ...,
            total_seats: builtins.int = ...,
            total_seats_in_use: builtins.int = ...,
            explorer_seats_in_use: builtins.int = ...,
            monthly_active_developers: builtins.int | None = ...,
            monthly_active_read_only: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_monthly_active_developers", b"_monthly_active_developers", "_monthly_active_read_only", b"_monthly_active_read_only", "account", b"account", "monthly_active_developers", b"monthly_active_developers", "monthly_active_read_only", b"monthly_active_read_only"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_monthly_active_developers", b"_monthly_active_developers", "_monthly_active_read_only", b"_monthly_active_read_only", "account", b"account", "developer_seats_in_use", b"developer_seats_in_use", "explorer_seats_in_use", b"explorer_seats_in_use", "monthly_active_developers", b"monthly_active_developers", "monthly_active_read_only", b"monthly_active_read_only", "read_only_seats_in_use", b"read_only_seats_in_use", "total_seats", b"total_seats", "total_seats_in_use", b"total_seats_in_use"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_monthly_active_developers", b"_monthly_active_developers"]) -> typing.Literal["monthly_active_developers"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_monthly_active_read_only", b"_monthly_active_read_only"]) -> typing.Literal["monthly_active_read_only"] | None: ...

    @typing.final
    class SemanticLayerMetricsRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _QueryType:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _QueryTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Usage.SemanticLayerMetricsRequest._QueryType.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            QUERY: Usage.SemanticLayerMetricsRequest._QueryType.ValueType  # 0
            SAVED_QUERY: Usage.SemanticLayerMetricsRequest._QueryType.ValueType  # 1
            EXPORT: Usage.SemanticLayerMetricsRequest._QueryType.ValueType  # 2

        class QueryType(_QueryType, metaclass=_QueryTypeEnumTypeWrapper): ...
        QUERY: Usage.SemanticLayerMetricsRequest.QueryType.ValueType  # 0
        SAVED_QUERY: Usage.SemanticLayerMetricsRequest.QueryType.ValueType  # 1
        EXPORT: Usage.SemanticLayerMetricsRequest.QueryType.ValueType  # 2

        TOTAL_METRICS_FIELD_NUMBER: builtins.int
        ENVIRONMENT_FIELD_NUMBER: builtins.int
        IS_PRODUCTION_FIELD_NUMBER: builtins.int
        QUERY_TYPE_FIELD_NUMBER: builtins.int
        total_metrics: builtins.int
        is_production: builtins.bool
        query_type: global___Usage.SemanticLayerMetricsRequest.QueryType.ValueType
        @property
        def environment(self) -> dbtlabs.proto.private.v1.records.environment_pb2.Environment: ...
        def __init__(
            self,
            *,
            total_metrics: builtins.int = ...,
            environment: dbtlabs.proto.private.v1.records.environment_pb2.Environment | None = ...,
            is_production: builtins.bool = ...,
            query_type: global___Usage.SemanticLayerMetricsRequest.QueryType.ValueType = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["environment", b"environment"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["environment", b"environment", "is_production", b"is_production", "query_type", b"query_type", "total_metrics", b"total_metrics"]) -> None: ...

    @typing.final
    class AIUsage(google.protobuf.message.Message):
        """*
        Event for individual AI usage.
        Each call and response to an AI model emits an individual usage event.
        Usage events can either be tracked individually or aggregated by a session if available.
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MODEL_PROVIDER_FIELD_NUMBER: builtins.int
        MODEL_NAME_FIELD_NUMBER: builtins.int
        APP_NAME_FIELD_NUMBER: builtins.int
        TRIGGER_FIELD_NUMBER: builtins.int
        ACTION_FIELD_NUMBER: builtins.int
        REQUEST_ID_FIELD_NUMBER: builtins.int
        HAS_ERROR_FIELD_NUMBER: builtins.int
        ERROR_MESSAGE_FIELD_NUMBER: builtins.int
        TOKENS_IN_PROMPT_FIELD_NUMBER: builtins.int
        TOKENS_IN_RESPONSE_FIELD_NUMBER: builtins.int
        TOKENS_TOTAL_FIELD_NUMBER: builtins.int
        LATENCY_MS_FIELD_NUMBER: builtins.int
        USER_ID_FIELD_NUMBER: builtins.int
        PROJECT_ID_FIELD_NUMBER: builtins.int
        SESSION_ID_FIELD_NUMBER: builtins.int
        CACHE_CREATION_INPUT_TOKENS_FIELD_NUMBER: builtins.int
        CACHE_READ_INPUT_TOKENS_FIELD_NUMBER: builtins.int
        REASONING_OUTPUT_TOKENS_FIELD_NUMBER: builtins.int
        model_provider: builtins.str
        """* The provider of the AI model (e.g., OpenAI, Anthropic)"""
        model_name: builtins.str
        """* The specific model used (e.g. gpt-4o)"""
        app_name: builtins.str
        """* The name of the application using AI (e.g. ide, visual_editor, explorer, ...)"""
        trigger: builtins.str
        """* The event that triggered the AI usage (e.g. keyboard, copilot_button, formula_node, chat, ...)"""
        action: builtins.str
        """* The specific action performed by the AI (e.g. generate_sql, generate_documentation, generate_tests, ...)"""
        request_id: builtins.str
        """*
        Individual AI request identifier.
        This can be the request trace or any other request identifier.
        """
        has_error: builtins.bool
        """* Indicates if an error occurred during generation"""
        error_message: builtins.str
        """* Error message if an error occurred"""
        tokens_in_prompt: builtins.int
        """* Number of tokens in the input prompt"""
        tokens_in_response: builtins.int
        """* Number of tokens in the generated response"""
        tokens_total: builtins.int
        """* Total number of tokens used (prompt + response)"""
        latency_ms: builtins.int
        """* Time taken to generate the response in milliseconds"""
        user_id: builtins.str
        """* Identifier of the user making the request"""
        project_id: builtins.str
        """* The project id the AI usage happened in"""
        session_id: builtins.str
        """*
        Identifier for a session of activity.
        This can be a chat session, a code editor session, etc.
        Something to connect individual ai usage events together.
        """
        cache_creation_input_tokens: builtins.int
        """* Input tokens that were cached and resulted in a cache miss (cache was created from these tokens)"""
        cache_read_input_tokens: builtins.int
        """* Input tokens that were cached and resulted in a cache hit (read from cache)"""
        reasoning_output_tokens: builtins.int
        """* Reasoning output tokens (e.g. chain-of-thought tokens not returned in the response)"""
        def __init__(
            self,
            *,
            model_provider: builtins.str | None = ...,
            model_name: builtins.str | None = ...,
            app_name: builtins.str | None = ...,
            trigger: builtins.str | None = ...,
            action: builtins.str | None = ...,
            request_id: builtins.str = ...,
            has_error: builtins.bool | None = ...,
            error_message: builtins.str | None = ...,
            tokens_in_prompt: builtins.int | None = ...,
            tokens_in_response: builtins.int | None = ...,
            tokens_total: builtins.int | None = ...,
            latency_ms: builtins.int | None = ...,
            user_id: builtins.str = ...,
            project_id: builtins.str = ...,
            session_id: builtins.str | None = ...,
            cache_creation_input_tokens: builtins.int | None = ...,
            cache_read_input_tokens: builtins.int | None = ...,
            reasoning_output_tokens: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_action", b"_action", "_app_name", b"_app_name", "_cache_creation_input_tokens", b"_cache_creation_input_tokens", "_cache_read_input_tokens", b"_cache_read_input_tokens", "_error_message", b"_error_message", "_has_error", b"_has_error", "_latency_ms", b"_latency_ms", "_model_name", b"_model_name", "_model_provider", b"_model_provider", "_reasoning_output_tokens", b"_reasoning_output_tokens", "_session_id", b"_session_id", "_tokens_in_prompt", b"_tokens_in_prompt", "_tokens_in_response", b"_tokens_in_response", "_tokens_total", b"_tokens_total", "_trigger", b"_trigger", "action", b"action", "app_name", b"app_name", "cache_creation_input_tokens", b"cache_creation_input_tokens", "cache_read_input_tokens", b"cache_read_input_tokens", "error_message", b"error_message", "has_error", b"has_error", "latency_ms", b"latency_ms", "model_name", b"model_name", "model_provider", b"model_provider", "reasoning_output_tokens", b"reasoning_output_tokens", "session_id", b"session_id", "tokens_in_prompt", b"tokens_in_prompt", "tokens_in_response", b"tokens_in_response", "tokens_total", b"tokens_total", "trigger", b"trigger"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_action", b"_action", "_app_name", b"_app_name", "_cache_creation_input_tokens", b"_cache_creation_input_tokens", "_cache_read_input_tokens", b"_cache_read_input_tokens", "_error_message", b"_error_message", "_has_error", b"_has_error", "_latency_ms", b"_latency_ms", "_model_name", b"_model_name", "_model_provider", b"_model_provider", "_reasoning_output_tokens", b"_reasoning_output_tokens", "_session_id", b"_session_id", "_tokens_in_prompt", b"_tokens_in_prompt", "_tokens_in_response", b"_tokens_in_response", "_tokens_total", b"_tokens_total", "_trigger", b"_trigger", "action", b"action", "app_name", b"app_name", "cache_creation_input_tokens", b"cache_creation_input_tokens", "cache_read_input_tokens", b"cache_read_input_tokens", "error_message", b"error_message", "has_error", b"has_error", "latency_ms", b"latency_ms", "model_name", b"model_name", "model_provider", b"model_provider", "project_id", b"project_id", "reasoning_output_tokens", b"reasoning_output_tokens", "request_id", b"request_id", "session_id", b"session_id", "tokens_in_prompt", b"tokens_in_prompt", "tokens_in_response", b"tokens_in_response", "tokens_total", b"tokens_total", "trigger", b"trigger", "user_id", b"user_id"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_action", b"_action"]) -> typing.Literal["action"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_app_name", b"_app_name"]) -> typing.Literal["app_name"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_cache_creation_input_tokens", b"_cache_creation_input_tokens"]) -> typing.Literal["cache_creation_input_tokens"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_cache_read_input_tokens", b"_cache_read_input_tokens"]) -> typing.Literal["cache_read_input_tokens"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_error_message", b"_error_message"]) -> typing.Literal["error_message"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_has_error", b"_has_error"]) -> typing.Literal["has_error"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_latency_ms", b"_latency_ms"]) -> typing.Literal["latency_ms"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_model_name", b"_model_name"]) -> typing.Literal["model_name"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_model_provider", b"_model_provider"]) -> typing.Literal["model_provider"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_reasoning_output_tokens", b"_reasoning_output_tokens"]) -> typing.Literal["reasoning_output_tokens"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_session_id", b"_session_id"]) -> typing.Literal["session_id"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_tokens_in_prompt", b"_tokens_in_prompt"]) -> typing.Literal["tokens_in_prompt"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_tokens_in_response", b"_tokens_in_response"]) -> typing.Literal["tokens_in_response"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_tokens_total", b"_tokens_total"]) -> typing.Literal["tokens_total"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_trigger", b"_trigger"]) -> typing.Literal["trigger"] | None: ...

    @typing.final
    class AgentTokenUsage(google.protobuf.message.Message):
        """*
        DEPRECATED. Retained as a stub for backwards-compatible proto
        evolution; do not use. Producers now publish the top-level
        v1.events.agent_token_usage.AgentTokenUsage to the intake queue;
        the enricher emits Usage.AgentTokenUsageWithCredits on the billing
        queue (see below).
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PRODUCT_FIELD_NUMBER: builtins.int
        MODEL_PROVIDER_FIELD_NUMBER: builtins.int
        MODEL_NAME_FIELD_NUMBER: builtins.int
        INPUT_TOKENS_FIELD_NUMBER: builtins.int
        OUTPUT_TOKENS_FIELD_NUMBER: builtins.int
        CACHE_READ_INPUT_TOKENS_FIELD_NUMBER: builtins.int
        CACHE_CREATION_INPUT_TOKENS_FIELD_NUMBER: builtins.int
        KEY_OWNER_FIELD_NUMBER: builtins.int
        USER_ID_FIELD_NUMBER: builtins.int
        REASONING_OUTPUT_TOKENS_FIELD_NUMBER: builtins.int
        product: builtins.str
        """* Product emitting the event (e.g. "wizard", "dev_agent"). Open string — canonical list maintained at the consumer."""
        model_provider: builtins.str
        """* Provider of the AI model (e.g. "openai", "anthropic")."""
        model_name: builtins.str
        """* Specific model used (e.g. "gpt-4o", "claude-opus-4-7")."""
        input_tokens: builtins.int
        """* Input tokens consumed by the request."""
        output_tokens: builtins.int
        """* Output tokens produced by the response."""
        cache_read_input_tokens: builtins.int
        """* Input tokens that were cached and resulted in a cache hit (read from cache). Mirrors AIUsage.cache_read_input_tokens."""
        cache_creation_input_tokens: builtins.int
        """* Input tokens that were cached and resulted in a cache miss (cache was created from these tokens). Mirrors AIUsage.cache_creation_input_tokens."""
        key_owner: global___Usage.KeyOwner.ValueType
        """* Whose API key paid for the call — closed set, dispatched on by the consumer."""
        user_id: builtins.str
        """* JWT `sub` of the user making the request; per-user attribution."""
        reasoning_output_tokens: builtins.int
        """* Reasoning output tokens (e.g. chain-of-thought tokens not returned in the response). Billed separately from output_tokens for reasoning models. Mirrors AIUsage.reasoning_output_tokens."""
        def __init__(
            self,
            *,
            product: builtins.str = ...,
            model_provider: builtins.str = ...,
            model_name: builtins.str = ...,
            input_tokens: builtins.int = ...,
            output_tokens: builtins.int = ...,
            cache_read_input_tokens: builtins.int | None = ...,
            cache_creation_input_tokens: builtins.int | None = ...,
            key_owner: global___Usage.KeyOwner.ValueType = ...,
            user_id: builtins.str = ...,
            reasoning_output_tokens: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_cache_creation_input_tokens", b"_cache_creation_input_tokens", "_cache_read_input_tokens", b"_cache_read_input_tokens", "_reasoning_output_tokens", b"_reasoning_output_tokens", "cache_creation_input_tokens", b"cache_creation_input_tokens", "cache_read_input_tokens", b"cache_read_input_tokens", "reasoning_output_tokens", b"reasoning_output_tokens"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_cache_creation_input_tokens", b"_cache_creation_input_tokens", "_cache_read_input_tokens", b"_cache_read_input_tokens", "_reasoning_output_tokens", b"_reasoning_output_tokens", "cache_creation_input_tokens", b"cache_creation_input_tokens", "cache_read_input_tokens", b"cache_read_input_tokens", "input_tokens", b"input_tokens", "key_owner", b"key_owner", "model_name", b"model_name", "model_provider", b"model_provider", "output_tokens", b"output_tokens", "product", b"product", "reasoning_output_tokens", b"reasoning_output_tokens", "user_id", b"user_id"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_cache_creation_input_tokens", b"_cache_creation_input_tokens"]) -> typing.Literal["cache_creation_input_tokens"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_cache_read_input_tokens", b"_cache_read_input_tokens"]) -> typing.Literal["cache_read_input_tokens"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_reasoning_output_tokens", b"_reasoning_output_tokens"]) -> typing.Literal["reasoning_output_tokens"] | None: ...

    @typing.final
    class AgentTokenUsageWithCredits(google.protobuf.message.Message):
        """*
        Priced agent token usage — emitted by the agent-token-usage
        enricher onto the billing queue (v1.billing.usage) after running
        the raw v1.events.agent_token_usage.AgentTokenUsage intake event
        through the pricing service.

        Carries the original token counts plus the per-token-type credit
        breakdown so any consumer of the billing queue (Metronome ingest,
        billing audit, ...) sees the same priced view without
        re-running the formula.

        Token counts are uint64; credit fields are double (rates are
        fractional and quoted in credits-per-token).
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PRODUCT_FIELD_NUMBER: builtins.int
        MODEL_PROVIDER_FIELD_NUMBER: builtins.int
        MODEL_NAME_FIELD_NUMBER: builtins.int
        INPUT_TOKENS_FIELD_NUMBER: builtins.int
        OUTPUT_TOKENS_FIELD_NUMBER: builtins.int
        CACHE_READ_INPUT_TOKENS_FIELD_NUMBER: builtins.int
        CACHE_CREATION_INPUT_TOKENS_FIELD_NUMBER: builtins.int
        KEY_OWNER_FIELD_NUMBER: builtins.int
        ACTOR_ID_FIELD_NUMBER: builtins.int
        ACTOR_TYPE_FIELD_NUMBER: builtins.int
        REASONING_OUTPUT_TOKENS_FIELD_NUMBER: builtins.int
        INPUT_CREDITS_FIELD_NUMBER: builtins.int
        OUTPUT_CREDITS_FIELD_NUMBER: builtins.int
        CACHE_READ_INPUT_CREDITS_FIELD_NUMBER: builtins.int
        CACHE_CREATION_INPUT_CREDITS_FIELD_NUMBER: builtins.int
        TOTAL_CREDITS_FIELD_NUMBER: builtins.int
        product: builtins.str
        """* Product emitting the event (e.g. "wizard", "dev_agent")."""
        model_provider: builtins.str
        """* Provider of the AI model (e.g. "openai", "anthropic")."""
        model_name: builtins.str
        """* Specific model used."""
        input_tokens: builtins.int
        """* Input tokens consumed by the request."""
        output_tokens: builtins.int
        """* Output tokens produced by the response."""
        cache_read_input_tokens: builtins.int
        """* Input tokens that resulted in a cache hit (read from cache)."""
        cache_creation_input_tokens: builtins.int
        """* Input tokens that resulted in a cache miss (created the cache entry)."""
        key_owner: global___Usage.KeyOwner.ValueType
        """* Whose API key paid for the call."""
        actor_id: builtins.str
        """* Identifier of the actor that made the request. Interpretation
        tightly coupled to actor_type.
        """
        actor_type: builtins.str
        """* Discriminator for actor_id: distinguishes between users, service
        tokens, etc.
        """
        reasoning_output_tokens: builtins.int
        """* Reasoning output tokens; informational passthrough — billed via output_tokens at the provider level."""
        input_credits: builtins.float
        """* Credits charged for input_tokens."""
        output_credits: builtins.float
        """* Credits charged for output_tokens (includes reasoning_output_tokens at the provider level)."""
        cache_read_input_credits: builtins.float
        """* Credits charged for cache_read_input_tokens."""
        cache_creation_input_credits: builtins.float
        """* Credits charged for cache_creation_input_tokens."""
        total_credits: builtins.float
        """* Sum of all *_credits fields; denormalized so consumers do not
        have to re-add them — and because Metronome cannot sum them
        on ingest.
        """
        def __init__(
            self,
            *,
            product: builtins.str = ...,
            model_provider: builtins.str = ...,
            model_name: builtins.str = ...,
            input_tokens: builtins.int = ...,
            output_tokens: builtins.int = ...,
            cache_read_input_tokens: builtins.int = ...,
            cache_creation_input_tokens: builtins.int = ...,
            key_owner: global___Usage.KeyOwner.ValueType = ...,
            actor_id: builtins.str = ...,
            actor_type: builtins.str = ...,
            reasoning_output_tokens: builtins.int = ...,
            input_credits: builtins.float = ...,
            output_credits: builtins.float = ...,
            cache_read_input_credits: builtins.float = ...,
            cache_creation_input_credits: builtins.float = ...,
            total_credits: builtins.float = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["actor_id", b"actor_id", "actor_type", b"actor_type", "cache_creation_input_credits", b"cache_creation_input_credits", "cache_creation_input_tokens", b"cache_creation_input_tokens", "cache_read_input_credits", b"cache_read_input_credits", "cache_read_input_tokens", b"cache_read_input_tokens", "input_credits", b"input_credits", "input_tokens", b"input_tokens", "key_owner", b"key_owner", "model_name", b"model_name", "model_provider", b"model_provider", "output_credits", b"output_credits", "output_tokens", b"output_tokens", "product", b"product", "reasoning_output_tokens", b"reasoning_output_tokens", "total_credits", b"total_credits"]) -> None: ...

    EVENT_ID_FIELD_NUMBER: builtins.int
    ACCOUNT_IDENTIFIER_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    MODELS_BUILT_FIELD_NUMBER: builtins.int
    ACCOUNT_HEARTBEAT_FIELD_NUMBER: builtins.int
    SEMANTIC_LAYER_METRICS_REQUEST_FIELD_NUMBER: builtins.int
    AI_USAGE_FIELD_NUMBER: builtins.int
    AGENT_TOKEN_USAGE_WITH_CREDITS_FIELD_NUMBER: builtins.int
    event_id: builtins.str
    """* The event_id design is very important: Metronome uses it as the
    transaction_id for de-duplication and idempotency, so the same
    event_id replayed will not be billed twice. Choose this value
    carefully — consult the billing / Metronome experts before
    setting it for a new event type.
    """
    account_identifier: builtins.str
    timestamp: builtins.int
    """TODO: add more cloud environment fields once we agree on them
    https://www.notion.so/dbtlabs/Common-environment-values-in-helm-charts-6871dfc7a0b24bd8a720b6abc0f92e70
    """
    @property
    def models_built(self) -> global___Usage.ModelsBuilt: ...
    @property
    def account_heartbeat(self) -> global___Usage.AccountHeartbeat: ...
    @property
    def semantic_layer_metrics_request(self) -> global___Usage.SemanticLayerMetricsRequest: ...
    @property
    def ai_usage(self) -> global___Usage.AIUsage: ...
    @property
    def agent_token_usage_with_credits(self) -> global___Usage.AgentTokenUsageWithCredits: ...
    def __init__(
        self,
        *,
        event_id: builtins.str = ...,
        account_identifier: builtins.str = ...,
        timestamp: builtins.int = ...,
        models_built: global___Usage.ModelsBuilt | None = ...,
        account_heartbeat: global___Usage.AccountHeartbeat | None = ...,
        semantic_layer_metrics_request: global___Usage.SemanticLayerMetricsRequest | None = ...,
        ai_usage: global___Usage.AIUsage | None = ...,
        agent_token_usage_with_credits: global___Usage.AgentTokenUsageWithCredits | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account_heartbeat", b"account_heartbeat", "agent_token_usage_with_credits", b"agent_token_usage_with_credits", "ai_usage", b"ai_usage", "event", b"event", "models_built", b"models_built", "semantic_layer_metrics_request", b"semantic_layer_metrics_request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account_heartbeat", b"account_heartbeat", "account_identifier", b"account_identifier", "agent_token_usage_with_credits", b"agent_token_usage_with_credits", "ai_usage", b"ai_usage", "event", b"event", "event_id", b"event_id", "models_built", b"models_built", "semantic_layer_metrics_request", b"semantic_layer_metrics_request", "timestamp", b"timestamp"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["event", b"event"]) -> typing.Literal["models_built", "account_heartbeat", "semantic_layer_metrics_request", "ai_usage", "agent_token_usage_with_credits"] | None: ...

global___Usage = Usage
