"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import dbtlabs.proto.private.v1.fields.ddtrace_pb2
import dbtlabs.proto.private.v1.fields.environment_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class WarehouseIngestionTriggered(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    CREDENTIALS_ID_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    account_id: builtins.int
    """deprecated since credentials_id is enough info to kick off ingestion"""
    credentials_id: builtins.int
    @property
    def trace(self) -> dbtlabs.proto.private.v1.fields.ddtrace_pb2.DDTrace: ...
    def __init__(
        self,
        *,
        account_id: builtins.int = ...,
        credentials_id: builtins.int = ...,
        trace: dbtlabs.proto.private.v1.fields.ddtrace_pb2.DDTrace | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["trace", b"trace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "credentials_id", b"credentials_id", "trace", b"trace"]) -> None: ...

global___WarehouseIngestionTriggered = WarehouseIngestionTriggered

@typing.final
class WarehouseIngestionCompleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    CREDENTIALS_ID_FIELD_NUMBER: builtins.int
    OBJECT_STORAGE_PATH_FIELD_NUMBER: builtins.int
    CONNECTION_ID_FIELD_NUMBER: builtins.int
    ENVIRONMENTS_FIELD_NUMBER: builtins.int
    CONNECTION_NAME_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    account_id: builtins.int
    credentials_id: builtins.int
    object_storage_path: builtins.str
    connection_id: builtins.int
    connection_name: builtins.str
    @property
    def environments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[dbtlabs.proto.private.v1.fields.environment_pb2.Environment]: ...
    @property
    def trace(self) -> dbtlabs.proto.private.v1.fields.ddtrace_pb2.DDTrace: ...
    def __init__(
        self,
        *,
        account_id: builtins.int = ...,
        credentials_id: builtins.int = ...,
        object_storage_path: builtins.str = ...,
        connection_id: builtins.int = ...,
        environments: collections.abc.Iterable[dbtlabs.proto.private.v1.fields.environment_pb2.Environment] | None = ...,
        connection_name: builtins.str = ...,
        trace: dbtlabs.proto.private.v1.fields.ddtrace_pb2.DDTrace | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["trace", b"trace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "connection_id", b"connection_id", "connection_name", b"connection_name", "credentials_id", b"credentials_id", "environments", b"environments", "object_storage_path", b"object_storage_path", "trace", b"trace"]) -> None: ...

global___WarehouseIngestionCompleted = WarehouseIngestionCompleted

@typing.final
class IngestionEnabled(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREDENTIALS_ID_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    credentials_id: builtins.int
    @property
    def trace(self) -> dbtlabs.proto.private.v1.fields.ddtrace_pb2.DDTrace: ...
    def __init__(
        self,
        *,
        credentials_id: builtins.int = ...,
        trace: dbtlabs.proto.private.v1.fields.ddtrace_pb2.DDTrace | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["trace", b"trace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["credentials_id", b"credentials_id", "trace", b"trace"]) -> None: ...

global___IngestionEnabled = IngestionEnabled

@typing.final
class IngestionDisabled(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREDENTIALS_ID_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    credentials_id: builtins.int
    @property
    def trace(self) -> dbtlabs.proto.private.v1.fields.ddtrace_pb2.DDTrace: ...
    def __init__(
        self,
        *,
        credentials_id: builtins.int = ...,
        trace: dbtlabs.proto.private.v1.fields.ddtrace_pb2.DDTrace | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["trace", b"trace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["credentials_id", b"credentials_id", "trace", b"trace"]) -> None: ...

global___IngestionDisabled = IngestionDisabled
