# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/cost_insights.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import cost_insights_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_cost__insights__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3dbtlabs/proto/private/v1/events/cost_insights.proto\x12\x17v1.events.cost_insights\x1a\x34\x64\x62tlabs/proto/private/v1/records/cost_insights.proto\"<\n\tTriggered\x12/\n\rcost_insights\x18\x01 \x01(\x0b\x32\x18.v1.records.CostInsights\"J\n\x17\x43onnectionTestTriggered\x12/\n\rcost_insights\x18\x01 \x01(\x0b\x32\x18.v1.records.CostInsights\"l\n\x1f\x43onnectionTestTriggeredResponse\x12I\n\x06status\x18\x01 \x01(\x0e\x32\x39.v1.events.cost_insights.CostInsightsConnectionTestStatus\"N\n\x1b\x43onnectionTestStatusRequest\x12/\n\rcost_insights\x18\x01 \x01(\x0b\x32\x18.v1.records.CostInsights\"\xe5\x03\n\x1c\x43onnectionTestStatusResponse\x12I\n\x06status\x18\x01 \x01(\x0e\x32\x39.v1.events.cost_insights.CostInsightsConnectionTestStatus\x12X\n\rerror_details\x18\x02 \x03(\x0b\x32\x41.v1.events.cost_insights.ConnectionTestStatusResponse.ErrorDetail\x12\x12\n\nupdated_at\x18\x03 \x01(\t\x1a\x8d\x01\n\x0b\x45rrorDetail\x12\x12\n\ntable_name\x18\x01 \x01(\t\x12S\n\nerror_type\x18\x02 \x01(\x0e\x32?.v1.events.cost_insights.ConnectionTestStatusResponse.ErrorType\x12\x15\n\rerror_details\x18\x03 \x01(\t\"|\n\tErrorType\x12\x1a\n\x16\x45RROR_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14\x45RROR_TYPE_NO_ACCESS\x10\x01\x12\x16\n\x12\x45RROR_TYPE_NO_DATA\x10\x02\x12!\n\x1d\x45RROR_TYPE_NO_ACCESS_OPTIONAL\x10\x03*\xef\x01\n CostInsightsConnectionTestStatus\x12\x34\n0COST_INSIGHTS_CONNECTION_TEST_STATUS_UNSPECIFIED\x10\x00\x12\x30\n,COST_INSIGHTS_CONNECTION_TEST_STATUS_TESTING\x10\x01\x12\x32\n.COST_INSIGHTS_CONNECTION_TEST_STATUS_SUCCEEDED\x10\x02\x12/\n+COST_INSIGHTS_CONNECTION_TEST_STATUS_FAILED\x10\x03\x42:Z8github.com/dbt-labs/proto-golang/v1/events/cost_insightsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.cost_insights_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/dbt-labs/proto-golang/v1/events/cost_insights'
  _globals['_COSTINSIGHTSCONNECTIONTESTSTATUS']._serialized_start=951
  _globals['_COSTINSIGHTSCONNECTIONTESTSTATUS']._serialized_end=1190
  _globals['_TRIGGERED']._serialized_start=134
  _globals['_TRIGGERED']._serialized_end=194
  _globals['_CONNECTIONTESTTRIGGERED']._serialized_start=196
  _globals['_CONNECTIONTESTTRIGGERED']._serialized_end=270
  _globals['_CONNECTIONTESTTRIGGEREDRESPONSE']._serialized_start=272
  _globals['_CONNECTIONTESTTRIGGEREDRESPONSE']._serialized_end=380
  _globals['_CONNECTIONTESTSTATUSREQUEST']._serialized_start=382
  _globals['_CONNECTIONTESTSTATUSREQUEST']._serialized_end=460
  _globals['_CONNECTIONTESTSTATUSRESPONSE']._serialized_start=463
  _globals['_CONNECTIONTESTSTATUSRESPONSE']._serialized_end=948
  _globals['_CONNECTIONTESTSTATUSRESPONSE_ERRORDETAIL']._serialized_start=681
  _globals['_CONNECTIONTESTSTATUSRESPONSE_ERRORDETAIL']._serialized_end=822
  _globals['_CONNECTIONTESTSTATUSRESPONSE_ERRORTYPE']._serialized_start=824
  _globals['_CONNECTIONTESTSTATUSRESPONSE_ERRORTYPE']._serialized_end=948
# @@protoc_insertion_point(module_scope)
