"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import dbtlabs.proto.private.v1.records.cost_insights_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _CostInsightsConnectionTestStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CostInsightsConnectionTestStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CostInsightsConnectionTestStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    COST_INSIGHTS_CONNECTION_TEST_STATUS_UNSPECIFIED: _CostInsightsConnectionTestStatus.ValueType  # 0
    COST_INSIGHTS_CONNECTION_TEST_STATUS_TESTING: _CostInsightsConnectionTestStatus.ValueType  # 1
    COST_INSIGHTS_CONNECTION_TEST_STATUS_SUCCEEDED: _CostInsightsConnectionTestStatus.ValueType  # 2
    COST_INSIGHTS_CONNECTION_TEST_STATUS_FAILED: _CostInsightsConnectionTestStatus.ValueType  # 3

class CostInsightsConnectionTestStatus(_CostInsightsConnectionTestStatus, metaclass=_CostInsightsConnectionTestStatusEnumTypeWrapper): ...

COST_INSIGHTS_CONNECTION_TEST_STATUS_UNSPECIFIED: CostInsightsConnectionTestStatus.ValueType  # 0
COST_INSIGHTS_CONNECTION_TEST_STATUS_TESTING: CostInsightsConnectionTestStatus.ValueType  # 1
COST_INSIGHTS_CONNECTION_TEST_STATUS_SUCCEEDED: CostInsightsConnectionTestStatus.ValueType  # 2
COST_INSIGHTS_CONNECTION_TEST_STATUS_FAILED: CostInsightsConnectionTestStatus.ValueType  # 3
global___CostInsightsConnectionTestStatus = CostInsightsConnectionTestStatus

@typing.final
class Triggered(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COST_INSIGHTS_FIELD_NUMBER: builtins.int
    @property
    def cost_insights(self) -> dbtlabs.proto.private.v1.records.cost_insights_pb2.CostInsights: ...
    def __init__(
        self,
        *,
        cost_insights: dbtlabs.proto.private.v1.records.cost_insights_pb2.CostInsights | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cost_insights", b"cost_insights"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cost_insights", b"cost_insights"]) -> None: ...

global___Triggered = Triggered

@typing.final
class ConnectionTestTriggered(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COST_INSIGHTS_FIELD_NUMBER: builtins.int
    @property
    def cost_insights(self) -> dbtlabs.proto.private.v1.records.cost_insights_pb2.CostInsights: ...
    def __init__(
        self,
        *,
        cost_insights: dbtlabs.proto.private.v1.records.cost_insights_pb2.CostInsights | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cost_insights", b"cost_insights"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cost_insights", b"cost_insights"]) -> None: ...

global___ConnectionTestTriggered = ConnectionTestTriggered

@typing.final
class ConnectionTestTriggeredResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: global___CostInsightsConnectionTestStatus.ValueType
    def __init__(
        self,
        *,
        status: global___CostInsightsConnectionTestStatus.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___ConnectionTestTriggeredResponse = ConnectionTestTriggeredResponse

@typing.final
class ConnectionTestStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COST_INSIGHTS_FIELD_NUMBER: builtins.int
    @property
    def cost_insights(self) -> dbtlabs.proto.private.v1.records.cost_insights_pb2.CostInsights: ...
    def __init__(
        self,
        *,
        cost_insights: dbtlabs.proto.private.v1.records.cost_insights_pb2.CostInsights | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cost_insights", b"cost_insights"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cost_insights", b"cost_insights"]) -> None: ...

global___ConnectionTestStatusRequest = ConnectionTestStatusRequest

@typing.final
class ConnectionTestStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ErrorType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ErrorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ConnectionTestStatusResponse._ErrorType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ERROR_TYPE_UNSPECIFIED: ConnectionTestStatusResponse._ErrorType.ValueType  # 0
        ERROR_TYPE_NO_ACCESS: ConnectionTestStatusResponse._ErrorType.ValueType  # 1
        ERROR_TYPE_NO_DATA: ConnectionTestStatusResponse._ErrorType.ValueType  # 2
        ERROR_TYPE_NO_ACCESS_OPTIONAL: ConnectionTestStatusResponse._ErrorType.ValueType  # 3

    class ErrorType(_ErrorType, metaclass=_ErrorTypeEnumTypeWrapper): ...
    ERROR_TYPE_UNSPECIFIED: ConnectionTestStatusResponse.ErrorType.ValueType  # 0
    ERROR_TYPE_NO_ACCESS: ConnectionTestStatusResponse.ErrorType.ValueType  # 1
    ERROR_TYPE_NO_DATA: ConnectionTestStatusResponse.ErrorType.ValueType  # 2
    ERROR_TYPE_NO_ACCESS_OPTIONAL: ConnectionTestStatusResponse.ErrorType.ValueType  # 3

    @typing.final
    class ErrorDetail(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TABLE_NAME_FIELD_NUMBER: builtins.int
        ERROR_TYPE_FIELD_NUMBER: builtins.int
        ERROR_DETAILS_FIELD_NUMBER: builtins.int
        table_name: builtins.str
        error_type: global___ConnectionTestStatusResponse.ErrorType.ValueType
        error_details: builtins.str
        def __init__(
            self,
            *,
            table_name: builtins.str = ...,
            error_type: global___ConnectionTestStatusResponse.ErrorType.ValueType = ...,
            error_details: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["error_details", b"error_details", "error_type", b"error_type", "table_name", b"table_name"]) -> None: ...

    STATUS_FIELD_NUMBER: builtins.int
    ERROR_DETAILS_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    status: global___CostInsightsConnectionTestStatus.ValueType
    updated_at: builtins.str
    """Format should be YYYY-MM-DDTHH:MM:SSZ"""
    @property
    def error_details(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ConnectionTestStatusResponse.ErrorDetail]: ...
    def __init__(
        self,
        *,
        status: global___CostInsightsConnectionTestStatus.ValueType = ...,
        error_details: collections.abc.Iterable[global___ConnectionTestStatusResponse.ErrorDetail] | None = ...,
        updated_at: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_details", b"error_details", "status", b"status", "updated_at", b"updated_at"]) -> None: ...

global___ConnectionTestStatusResponse = ConnectionTestStatusResponse
