# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/credentials.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import credentials_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_credentials__pb2
from dbtlabs.proto.private.v1.common import event_options_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_common_dot_event__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1dbtlabs/proto/private/v1/events/credentials.proto\x12\x15v1.events.credentials\x1a\x32\x64\x62tlabs/proto/private/v1/records/credentials.proto\x1a\x33\x64\x62tlabs/proto/private/v1/common/event_options.proto\"W\n\x05\x41\x64\x64\x65\x64\x12,\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32\x17.v1.records.Credentials: \x82\xb5\x18\x1c\x43redentials Added to Project\"[\n\x07\x43hanged\x12,\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32\x17.v1.records.Credentials:\"\x82\xb5\x18\x1e\x43redentials Changed in Project\"]\n\x07Removed\x12,\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32\x17.v1.records.Credentials:$\x82\xb5\x18 Credentials Removed from ProjectB8Z6github.com/dbt-labs/proto-golang/v1/events/credentialsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.credentials_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/dbt-labs/proto-golang/v1/events/credentials'
  _globals['_ADDED']._loaded_options = None
  _globals['_ADDED']._serialized_options = b'\202\265\030\034Credentials Added to Project'
  _globals['_CHANGED']._loaded_options = None
  _globals['_CHANGED']._serialized_options = b'\202\265\030\036Credentials Changed in Project'
  _globals['_REMOVED']._loaded_options = None
  _globals['_REMOVED']._serialized_options = b'\202\265\030 Credentials Removed from Project'
  _globals['_ADDED']._serialized_start=181
  _globals['_ADDED']._serialized_end=268
  _globals['_CHANGED']._serialized_start=270
  _globals['_CHANGED']._serialized_end=361
  _globals['_REMOVED']._serialized_start=363
  _globals['_REMOVED']._serialized_end=456
# @@protoc_insertion_point(module_scope)
