"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.credentials_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Added(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREDENTIALS_FIELD_NUMBER: builtins.int
    @property
    def credentials(self) -> dbtlabs.proto.private.v1.records.credentials_pb2.Credentials: ...
    def __init__(
        self,
        *,
        credentials: dbtlabs.proto.private.v1.records.credentials_pb2.Credentials | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["credentials", b"credentials"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["credentials", b"credentials"]) -> None: ...

global___Added = Added

@typing.final
class Changed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREDENTIALS_FIELD_NUMBER: builtins.int
    @property
    def credentials(self) -> dbtlabs.proto.private.v1.records.credentials_pb2.Credentials: ...
    def __init__(
        self,
        *,
        credentials: dbtlabs.proto.private.v1.records.credentials_pb2.Credentials | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["credentials", b"credentials"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["credentials", b"credentials"]) -> None: ...

global___Changed = Changed

@typing.final
class Removed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREDENTIALS_FIELD_NUMBER: builtins.int
    @property
    def credentials(self) -> dbtlabs.proto.private.v1.records.credentials_pb2.Credentials: ...
    def __init__(
        self,
        *,
        credentials: dbtlabs.proto.private.v1.records.credentials_pb2.Credentials | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["credentials", b"credentials"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["credentials", b"credentials"]) -> None: ...

global___Removed = Removed
