# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/custom_environment_variable.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import custom_environment_variable_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_custom__environment__variable__pb2
from dbtlabs.proto.private.v1.common import event_options_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_common_dot_event__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAdbtlabs/proto/private/v1/events/custom_environment_variable.proto\x12%v1.events.custom_environment_variable\x1a\x42\x64\x62tlabs/proto/private/v1/records/custom_environment_variable.proto\x1a\x33\x64\x62tlabs/proto/private/v1/common/event_options.proto\"~\n\x07\x43hanged\x12J\n\x1b\x63ustom_environment_variable\x18\x01 \x01(\x0b\x32%.v1.records.CustomEnvironmentVariable:\'\x82\xb5\x18#Custom Environment Variable Changed\"z\n\x05\x41\x64\x64\x65\x64\x12J\n\x1b\x63ustom_environment_variable\x18\x01 \x01(\x0b\x32%.v1.records.CustomEnvironmentVariable:%\x82\xb5\x18!Custom Environment Variable Added\"~\n\x07Removed\x12J\n\x1b\x63ustom_environment_variable\x18\x01 \x01(\x0b\x32%.v1.records.CustomEnvironmentVariable:\'\x82\xb5\x18#Custom Environment Variable RemovedBHZFgithub.com/dbt-labs/proto-golang/v1/events/custom_environment_variableb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.custom_environment_variable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/dbt-labs/proto-golang/v1/events/custom_environment_variable'
  _globals['_CHANGED']._loaded_options = None
  _globals['_CHANGED']._serialized_options = b'\202\265\030#Custom Environment Variable Changed'
  _globals['_ADDED']._loaded_options = None
  _globals['_ADDED']._serialized_options = b'\202\265\030!Custom Environment Variable Added'
  _globals['_REMOVED']._loaded_options = None
  _globals['_REMOVED']._serialized_options = b'\202\265\030#Custom Environment Variable Removed'
  _globals['_CHANGED']._serialized_start=229
  _globals['_CHANGED']._serialized_end=355
  _globals['_ADDED']._serialized_start=357
  _globals['_ADDED']._serialized_end=479
  _globals['_REMOVED']._serialized_start=481
  _globals['_REMOVED']._serialized_end=607
# @@protoc_insertion_point(module_scope)
