# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/dbt_copilot_generation_complete.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEdbtlabs/proto/private/v1/events/dbt_copilot_generation_complete.proto\x12)v1.events.dbt_copilot_generation_complete\"\xfc\x04\n\x1c\x44\x62tCopilotGenerationComplete\x12\x16\n\x0emodel_provider\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\x10\n\x08\x61pp_name\x18\x03 \x01(\t\x12\x17\n\x0f\x63opilot_trigger\x18\x04 \x01(\t\x12\x16\n\x0e\x63opilot_action\x18\x05 \x01(\t\x12\x1a\n\x12\x63opilot_request_id\x18\x06 \x01(\t\x12\x11\n\thas_error\x18\x07 \x01(\x08\x12\x1a\n\rerror_message\x18\x08 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x15has_custom_styleguide\x18\t \x01(\x08\x12\x16\n\x0eprompt_version\x18\n \x01(\t\x12\x13\n\x0bprompt_name\x18\x0b \x01(\t\x12\x18\n\x10prompt_variation\x18\x0c \x01(\t\x12\x1d\n\x10tokens_in_prompt\x18\r \x01(\x03H\x01\x88\x01\x01\x12\x1f\n\x12tokens_in_response\x18\x0e \x01(\x03H\x02\x88\x01\x01\x12\x19\n\x0ctokens_total\x18\x0f \x01(\x03H\x03\x88\x01\x01\x12\x17\n\nlatency_ms\x18\x10 \x01(\x03H\x04\x88\x01\x01\x12\x0f\n\x07user_id\x18\x11 \x01(\t\x12\x12\n\nproject_id\x18\x12 \x01(\t\x12\x12\n\naccount_id\x18\x13 \x01(\t\x12\x1b\n\x0eide_session_id\x18\x14 \x01(\tH\x05\x88\x01\x01\x42\x10\n\x0e_error_messageB\x13\n\x11_tokens_in_promptB\x15\n\x13_tokens_in_responseB\x0f\n\r_tokens_totalB\r\n\x0b_latency_msB\x11\n\x0f_ide_session_idBLZJgithub.com/dbt-labs/proto-golang/v1/events/dbt_copilot_generation_completeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.dbt_copilot_generation_complete_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZJgithub.com/dbt-labs/proto-golang/v1/events/dbt_copilot_generation_complete'
  _globals['_DBTCOPILOTGENERATIONCOMPLETE']._serialized_start=117
  _globals['_DBTCOPILOTGENERATIONCOMPLETE']._serialized_end=753
# @@protoc_insertion_point(module_scope)
