# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/dbt_jwt.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import dbt_jwt_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_dbt__jwt__pb2
from dbtlabs.proto.private.v1.common import event_options_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_common_dot_event__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-dbtlabs/proto/private/v1/events/dbt_jwt.proto\x12\x11v1.events.dbt_jwt\x1a.dbtlabs/proto/private/v1/records/dbt_jwt.proto\x1a\x33\x64\x62tlabs/proto/private/v1/common/event_options.proto\"E\n\tJwtIssued\x12\x1f\n\x03jwt\x18\x01 \x01(\x0b\x32\x12.v1.records.DbtJwt:\x17\x82\xb5\x18\x13\x41\x63\x63\x65ss Token Issued\"G\n\nJwtRevoked\x12\x1f\n\x03jwt\x18\x01 \x01(\x0b\x32\x12.v1.records.DbtJwt:\x18\x82\xb5\x18\x14\x41\x63\x63\x65ss Token RevokedB4Z2github.com/dbt-labs/proto-golang/v1/events/dbt_jwtb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.dbt_jwt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/dbt-labs/proto-golang/v1/events/dbt_jwt'
  _globals['_JWTISSUED']._loaded_options = None
  _globals['_JWTISSUED']._serialized_options = b'\202\265\030\023Access Token Issued'
  _globals['_JWTREVOKED']._loaded_options = None
  _globals['_JWTREVOKED']._serialized_options = b'\202\265\030\024Access Token Revoked'
  _globals['_JWTISSUED']._serialized_start=169
  _globals['_JWTISSUED']._serialized_end=238
  _globals['_JWTREVOKED']._serialized_start=240
  _globals['_JWTREVOKED']._serialized_end=311
# @@protoc_insertion_point(module_scope)
