"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DbtCopilotUserAcceptance(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ResponseType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ResponseTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DbtCopilotUserAcceptance._ResponseType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ACCEPTED: DbtCopilotUserAcceptance._ResponseType.ValueType  # 0
        REJECTED: DbtCopilotUserAcceptance._ResponseType.ValueType  # 1
        EDITED: DbtCopilotUserAcceptance._ResponseType.ValueType  # 2

    class ResponseType(_ResponseType, metaclass=_ResponseTypeEnumTypeWrapper): ...
    ACCEPTED: DbtCopilotUserAcceptance.ResponseType.ValueType  # 0
    REJECTED: DbtCopilotUserAcceptance.ResponseType.ValueType  # 1
    EDITED: DbtCopilotUserAcceptance.ResponseType.ValueType  # 2

    COPILOT_REQUEST_ID_FIELD_NUMBER: builtins.int
    RESPONSE_TYPE_FIELD_NUMBER: builtins.int
    copilot_request_id: builtins.str
    response_type: global___DbtCopilotUserAcceptance.ResponseType.ValueType
    def __init__(
        self,
        *,
        copilot_request_id: builtins.str = ...,
        response_type: global___DbtCopilotUserAcceptance.ResponseType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["copilot_request_id", b"copilot_request_id", "response_type", b"response_type"]) -> None: ...

global___DbtCopilotUserAcceptance = DbtCopilotUserAcceptance
