"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.dbt_jwt_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class JwtIssued(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JWT_FIELD_NUMBER: builtins.int
    @property
    def jwt(self) -> dbtlabs.proto.private.v1.records.dbt_jwt_pb2.DbtJwt: ...
    def __init__(
        self,
        *,
        jwt: dbtlabs.proto.private.v1.records.dbt_jwt_pb2.DbtJwt | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["jwt", b"jwt"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["jwt", b"jwt"]) -> None: ...

global___JwtIssued = JwtIssued

@typing.final
class JwtRevoked(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JWT_FIELD_NUMBER: builtins.int
    @property
    def jwt(self) -> dbtlabs.proto.private.v1.records.dbt_jwt_pb2.DbtJwt: ...
    def __init__(
        self,
        *,
        jwt: dbtlabs.proto.private.v1.records.dbt_jwt_pb2.DbtJwt | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["jwt", b"jwt"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["jwt", b"jwt"]) -> None: ...

global___JwtRevoked = JwtRevoked
