"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.exposure_pb2
import dbtlabs.proto.private.v1.rpc.lineage.exposures_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GenerationTriggered(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Source:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SourceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[GenerationTriggered._Source.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DBT_CLOUD: GenerationTriggered._Source.ValueType  # 0
        """for integration crud events"""
        SCHEDULER: GenerationTriggered._Source.ValueType  # 1

    class Source(_Source, metaclass=_SourceEnumTypeWrapper): ...
    DBT_CLOUD: GenerationTriggered.Source.ValueType  # 0
    """for integration crud events"""
    SCHEDULER: GenerationTriggered.Source.ValueType  # 1

    EXPOSURE_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    source: global___GenerationTriggered.Source.ValueType
    @property
    def exposure(self) -> dbtlabs.proto.private.v1.records.exposure_pb2.GeneratedExposure: ...
    def __init__(
        self,
        *,
        exposure: dbtlabs.proto.private.v1.records.exposure_pb2.GeneratedExposure | None = ...,
        source: global___GenerationTriggered.Source.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["exposure", b"exposure"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["exposure", b"exposure", "source", b"source"]) -> None: ...

global___GenerationTriggered = GenerationTriggered

@typing.final
class Generated(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXPOSURE_FIELD_NUMBER: builtins.int
    EXPOSURE_COUNT_FIELD_NUMBER: builtins.int
    exposure_count: builtins.int
    @property
    def exposure(self) -> dbtlabs.proto.private.v1.records.exposure_pb2.GeneratedExposure: ...
    def __init__(
        self,
        *,
        exposure: dbtlabs.proto.private.v1.records.exposure_pb2.GeneratedExposure | None = ...,
        exposure_count: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["exposure", b"exposure"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["exposure", b"exposure", "exposure_count", b"exposure_count"]) -> None: ...

global___Generated = Generated

@typing.final
class RefreshTriggered(google.protobuf.message.Message):
    """trigger exposure refresh in BI Tool"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXPOSURE_ID_FIELD_NUMBER: builtins.int
    THROTTLE_MINUTES_FIELD_NUMBER: builtins.int
    exposure_id: builtins.str
    throttle_minutes: builtins.int
    def __init__(
        self,
        *,
        exposure_id: builtins.str = ...,
        throttle_minutes: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["exposure_id", b"exposure_id", "throttle_minutes", b"throttle_minutes"]) -> None: ...

global___RefreshTriggered = RefreshTriggered

@typing.final
class GetRefreshStatus(google.protobuf.message.Message):
    """get status of BI tool refresh job"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    key: builtins.str
    """Redis key containing the main state record for the env"""
    def __init__(
        self,
        *,
        key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["key", b"key"]) -> None: ...

global___GetRefreshStatus = GetRefreshStatus

@typing.final
class CancelRefresh(google.protobuf.message.Message):
    """Cancel refresh jobs in BI tool"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXPOSURE_ID_FIELD_NUMBER: builtins.int
    exposure_id: builtins.str
    """Exposure ID of the refresh to be canceled"""
    def __init__(
        self,
        *,
        exposure_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["exposure_id", b"exposure_id"]) -> None: ...

global___CancelRefresh = CancelRefresh

@typing.final
class TableauWebhookReceived(google.protobuf.message.Message):
    """received webhook from Tableau"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_FIELD_NUMBER: builtins.int
    EVENT_TYPE_FIELD_NUMBER: builtins.int
    RESOURCE_NAME_FIELD_NUMBER: builtins.int
    SITE_LUID_FIELD_NUMBER: builtins.int
    RESOURCE_LUID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    resource: builtins.str
    """Resource type of the object that the webhook is for"""
    event_type: builtins.str
    """Type of event that occurred"""
    resource_name: builtins.str
    """Name of the resource"""
    site_luid: builtins.str
    """LUID for the site contaning the resource"""
    resource_luid: builtins.str
    """The resource luid"""
    created_at: builtins.str
    """Timestamp of when the resource was created"""
    def __init__(
        self,
        *,
        resource: builtins.str = ...,
        event_type: builtins.str = ...,
        resource_name: builtins.str = ...,
        site_luid: builtins.str = ...,
        resource_luid: builtins.str = ...,
        created_at: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "event_type", b"event_type", "resource", b"resource", "resource_luid", b"resource_luid", "resource_name", b"resource_name", "site_luid", b"site_luid"]) -> None: ...

global___TableauWebhookReceived = TableauWebhookReceived

@typing.final
class RefreshCompleted(google.protobuf.message.Message):
    """indicates Tableau refresh completion"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXPOSURE_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_MSG_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    exposure_id: builtins.str
    status: dbtlabs.proto.private.v1.rpc.lineage.exposures_pb2.ExposureRefreshStatus.ValueType
    """Status of the exposure refresh"""
    error_msg: builtins.str
    """Error message that should be returned in the
    TriggerResponse (grpc api)
    """
    msg: builtins.str
    """message that should be returned in the TriggerResponse (gRPC API)"""
    def __init__(
        self,
        *,
        exposure_id: builtins.str = ...,
        status: dbtlabs.proto.private.v1.rpc.lineage.exposures_pb2.ExposureRefreshStatus.ValueType = ...,
        error_msg: builtins.str = ...,
        msg: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_msg", b"error_msg", "exposure_id", b"exposure_id", "msg", b"msg", "status", b"status"]) -> None: ...

global___RefreshCompleted = RefreshCompleted

@typing.final
class LineageIntegrationTask(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENVIRONMENT_ID_FIELD_NUMBER: builtins.int
    TRIGGER_REFRESH_FIELD_NUMBER: builtins.int
    GET_REFRESH_STATUS_FIELD_NUMBER: builtins.int
    RECEIVED_TABLEAU_WEBHOOK_FIELD_NUMBER: builtins.int
    CANCEL_REFRESH_FIELD_NUMBER: builtins.int
    ACCOUNT_IDENTIFIER_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    environment_id: builtins.str
    account_identifier: builtins.str
    """Temporarily optional until the migration is complete"""
    account_id: builtins.str
    """Temporarily optional until the migration is complete"""
    @property
    def trigger_refresh(self) -> global___RefreshTriggered: ...
    @property
    def get_refresh_status(self) -> global___GetRefreshStatus: ...
    @property
    def received_tableau_webhook(self) -> global___TableauWebhookReceived: ...
    @property
    def cancel_refresh(self) -> global___CancelRefresh: ...
    def __init__(
        self,
        *,
        environment_id: builtins.str = ...,
        trigger_refresh: global___RefreshTriggered | None = ...,
        get_refresh_status: global___GetRefreshStatus | None = ...,
        received_tableau_webhook: global___TableauWebhookReceived | None = ...,
        cancel_refresh: global___CancelRefresh | None = ...,
        account_identifier: builtins.str | None = ...,
        account_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_account_id", b"_account_id", "_account_identifier", b"_account_identifier", "account_id", b"account_id", "account_identifier", b"account_identifier", "cancel_refresh", b"cancel_refresh", "get_refresh_status", b"get_refresh_status", "lineage_integration_action", b"lineage_integration_action", "received_tableau_webhook", b"received_tableau_webhook", "trigger_refresh", b"trigger_refresh"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_account_id", b"_account_id", "_account_identifier", b"_account_identifier", "account_id", b"account_id", "account_identifier", b"account_identifier", "cancel_refresh", b"cancel_refresh", "environment_id", b"environment_id", "get_refresh_status", b"get_refresh_status", "lineage_integration_action", b"lineage_integration_action", "received_tableau_webhook", b"received_tableau_webhook", "trigger_refresh", b"trigger_refresh"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_account_id", b"_account_id"]) -> typing.Literal["account_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_account_identifier", b"_account_identifier"]) -> typing.Literal["account_identifier"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["lineage_integration_action", b"lineage_integration_action"]) -> typing.Literal["trigger_refresh", "get_refresh_status", "received_tableau_webhook", "cancel_refresh"] | None: ...

global___LineageIntegrationTask = LineageIntegrationTask
