# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/external_run_ingestion.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import trace_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_trace__pb2
from dbtlabs.proto.private.v1.fields import cloudprovider_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_cloudprovider__pb2
from dbtlabs.proto.private.v1.records import run_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_run__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<dbtlabs/proto/private/v1/events/external_run_ingestion.proto\x12 v1.events.external_run_ingestion\x1a,dbtlabs/proto/private/v1/records/trace.proto\x1a\x33\x64\x62tlabs/proto/private/v1/fields/cloudprovider.proto\x1a*dbtlabs/proto/private/v1/records/run.proto\"\xec\x01\n\x13\x45xternalRunIngested\x12\n\n\x02id\x18\x01 \x01(\t\x12\x30\n\x0e\x63loud_provider\x18\x02 \x01(\x0e\x32\x18.v1.fields.CloudProvider\x12\x18\n\x10\x61rtifacts_bucket\x18\x03 \x01(\t\x12\x16\n\x0e\x61rtifacts_path\x18\x04 \x01(\t\x12\x16\n\x0e\x65nvironment_id\x18\x05 \x01(\t\x12%\n\x05trace\x18\x06 \x01(\x0b\x32\x11.v1.records.TraceH\x00\x88\x01\x01\x12\x1c\n\x03run\x18\x07 \x01(\x0b\x32\x0f.v1.records.RunB\x08\n\x06_trace\"n\n\x1d\x45xternalRunIngestionCompleted\x12\x1c\n\x03run\x18\x01 \x01(\x0b\x32\x0f.v1.records.Run\x12%\n\x05trace\x18\x02 \x01(\x0b\x32\x11.v1.records.TraceH\x00\x88\x01\x01\x42\x08\n\x06_traceBCZAgithub.com/dbt-labs/proto-golang/v1/events/external_run_ingestionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.external_run_ingestion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/dbt-labs/proto-golang/v1/events/external_run_ingestion'
  _globals['_EXTERNALRUNINGESTED']._serialized_start=242
  _globals['_EXTERNALRUNINGESTED']._serialized_end=478
  _globals['_EXTERNALRUNINGESTIONCOMPLETED']._serialized_start=480
  _globals['_EXTERNALRUNINGESTIONCOMPLETED']._serialized_end=590
# @@protoc_insertion_point(module_scope)
