"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.extended_attributes_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Added(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXTENDED_ATTRIBUTES_FIELD_NUMBER: builtins.int
    @property
    def extended_attributes(self) -> dbtlabs.proto.private.v1.records.extended_attributes_pb2.ExtendedAttributes: ...
    def __init__(
        self,
        *,
        extended_attributes: dbtlabs.proto.private.v1.records.extended_attributes_pb2.ExtendedAttributes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["extended_attributes", b"extended_attributes"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["extended_attributes", b"extended_attributes"]) -> None: ...

global___Added = Added

@typing.final
class Changed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXTENDED_ATTRIBUTES_FIELD_NUMBER: builtins.int
    @property
    def extended_attributes(self) -> dbtlabs.proto.private.v1.records.extended_attributes_pb2.ExtendedAttributes: ...
    def __init__(
        self,
        *,
        extended_attributes: dbtlabs.proto.private.v1.records.extended_attributes_pb2.ExtendedAttributes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["extended_attributes", b"extended_attributes"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["extended_attributes", b"extended_attributes"]) -> None: ...

global___Changed = Changed

@typing.final
class Removed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXTENDED_ATTRIBUTES_FIELD_NUMBER: builtins.int
    @property
    def extended_attributes(self) -> dbtlabs.proto.private.v1.records.extended_attributes_pb2.ExtendedAttributes: ...
    def __init__(
        self,
        *,
        extended_attributes: dbtlabs.proto.private.v1.records.extended_attributes_pb2.ExtendedAttributes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["extended_attributes", b"extended_attributes"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["extended_attributes", b"extended_attributes"]) -> None: ...

global___Removed = Removed
