# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/fusion.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.public.v1.common import vortex_options_pb2 as dbtlabs_dot_proto_dot_public_dot_v1_dot_common_dot_vortex__options__pb2
from dbtlabs.proto.public.v1.events import vortex_pb2 as dbtlabs_dot_proto_dot_public_dot_v1_dot_events_dot_vortex__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,dbtlabs/proto/private/v1/events/fusion.proto\x12\x10v1.events.fusion\x1a\x33\x64\x62tlabs/proto/public/v1/common/vortex_options.proto\x1a+dbtlabs/proto/public/v1/events/vortex.proto\"\xfa\x02\n\x0f\x43loudInvocation\x12=\n\nenrichment\x18\x01 \x01(\x0b\x32).v1.events.vortex.VortexMessageEnrichment\x12\x15\n\rinvocation_id\x18\x02 \x01(\t\x12$\n\x1c\x64\x62t_cloud_account_identifier\x18\x03 \x01(\t\x12\x1c\n\x14\x64\x62t_cloud_project_id\x18\x04 \x01(\t\x12 \n\x18\x64\x62t_cloud_environment_id\x18\x05 \x01(\t\x12\x18\n\x10\x64\x62t_cloud_job_id\x18\x06 \x01(\t\x12\"\n\x1a\x64\x62t_cloud_environment_type\x18\x07 \x01(\t\x12-\n%dbt_cloud_environment_deployment_type\x18\x08 \x01(\t\x12\x1a\n\x12\x64\x62t_cloud_job_type\x18\t \x01(\t\x12\x18\n\x10\x64\x62t_cloud_run_id\x18\n \x01(\t:\x08\xd8\xa6\x1d\x03\x80\xa7\x1d\x01\x42\x33Z1github.com/dbt-labs/proto-golang/v1/events/fusionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.fusion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/dbt-labs/proto-golang/v1/events/fusion'
  _globals['_CLOUDINVOCATION']._loaded_options = None
  _globals['_CLOUDINVOCATION']._serialized_options = b'\330\246\035\003\200\247\035\001'
  _globals['_CLOUDINVOCATION']._serialized_start=165
  _globals['_CLOUDINVOCATION']._serialized_end=543
# @@protoc_insertion_point(module_scope)
