"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.public.v1.events.vortex_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CloudInvocation(google.protobuf.message.Message):
    """
    RFC 2119 Expectations for using these events:

    1. After the Fusion emits the `v1.public.events.fusion.Invocation` event it MAY emit the `CloudInvocation` at the start of the process before any other events
    a. Fusion should only emit the `CloudInvocation` event if it is running in dbt Cloud based on whether environment variables have been set
    b. Fusion MUST set the `invocation_id` field to match the `invocation_id` field of the `v1.public.events.fusion.Invocation` event
    c. All fields with Required in the comment MUST be set, others are optional.

    CloudInvocation is additional information about a Fusion CLI invocation that
    is available when the Fusion CLI is invoked in the dbt Cloud enviroment. It
    is emitted after the public Invocation event and adds additional decoration
    to that stream of events that are specific to the cloud environment.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENRICHMENT_FIELD_NUMBER: builtins.int
    INVOCATION_ID_FIELD_NUMBER: builtins.int
    DBT_CLOUD_ACCOUNT_IDENTIFIER_FIELD_NUMBER: builtins.int
    DBT_CLOUD_PROJECT_ID_FIELD_NUMBER: builtins.int
    DBT_CLOUD_ENVIRONMENT_ID_FIELD_NUMBER: builtins.int
    DBT_CLOUD_JOB_ID_FIELD_NUMBER: builtins.int
    DBT_CLOUD_ENVIRONMENT_TYPE_FIELD_NUMBER: builtins.int
    DBT_CLOUD_ENVIRONMENT_DEPLOYMENT_TYPE_FIELD_NUMBER: builtins.int
    DBT_CLOUD_JOB_TYPE_FIELD_NUMBER: builtins.int
    DBT_CLOUD_RUN_ID_FIELD_NUMBER: builtins.int
    invocation_id: builtins.str
    """A foreign key to the Invocation message that was emitted at the
    start of the fusion process.
    """
    dbt_cloud_account_identifier: builtins.str
    """Globally unique account identifier in which the invokation is run.
    Comes from the DBT_CLOUD_ACCOUNT_IDENTIFIER environment variable.
    e.g. act_0g9JY6ZTSUNAQPG6WvLNYYdmYHW
    Required
    """
    dbt_cloud_project_id: builtins.str
    """Project identifier
    Comes from the DBT_CLOUD_PROJECT_ID environment variable.
    e.g. 672
    Required
    """
    dbt_cloud_environment_id: builtins.str
    """Unique identifier of the environment within the tenant.
    Comes from the DBT_CLOUD_ENVIRONMENT_ID environment variable.
    e.g. 2
    Required
    """
    dbt_cloud_job_id: builtins.str
    """Unique identifier of the job within the account identifier.
    Comes from the DBT_CLOUD_JOB_ID environment variable.
    e.g. 0
    """
    dbt_cloud_environment_type: builtins.str
    """The type of environment in dbt Cloud.
    Comes from the DBT_CLOUD_ENVIRONMENT_TYPE environment variable.
    e.g. development or deployment
    Required
    """
    dbt_cloud_environment_deployment_type: builtins.str
    """The type of deployment for the environment.
    Comes from the DBT_CLOUD_ENVIRONMENT_DEPLOYMENT_TYPE environment variable.
    e.g. production or staging
    """
    dbt_cloud_job_type: builtins.str
    """The job type as configured when the invocation ran
    Comes from the DBT_CLOUD_JOB_TYPE environment variable.
    e.g. ci, scheduled, merge, adaptive, etc.
    """
    dbt_cloud_run_id: builtins.str
    """The unique run identifier in dbt Cloud
    Comes from the DBT_CLOUD_RUN_ID environment variable.
    May be empty if executed from a development context
    """
    @property
    def enrichment(self) -> dbtlabs.proto.public.v1.events.vortex_pb2.VortexMessageEnrichment: ...
    def __init__(
        self,
        *,
        enrichment: dbtlabs.proto.public.v1.events.vortex_pb2.VortexMessageEnrichment | None = ...,
        invocation_id: builtins.str = ...,
        dbt_cloud_account_identifier: builtins.str = ...,
        dbt_cloud_project_id: builtins.str = ...,
        dbt_cloud_environment_id: builtins.str = ...,
        dbt_cloud_job_id: builtins.str = ...,
        dbt_cloud_environment_type: builtins.str = ...,
        dbt_cloud_environment_deployment_type: builtins.str = ...,
        dbt_cloud_job_type: builtins.str = ...,
        dbt_cloud_run_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["enrichment", b"enrichment"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["dbt_cloud_account_identifier", b"dbt_cloud_account_identifier", "dbt_cloud_environment_deployment_type", b"dbt_cloud_environment_deployment_type", "dbt_cloud_environment_id", b"dbt_cloud_environment_id", "dbt_cloud_environment_type", b"dbt_cloud_environment_type", "dbt_cloud_job_id", b"dbt_cloud_job_id", "dbt_cloud_job_type", b"dbt_cloud_job_type", "dbt_cloud_project_id", b"dbt_cloud_project_id", "dbt_cloud_run_id", b"dbt_cloud_run_id", "enrichment", b"enrichment", "invocation_id", b"invocation_id"]) -> None: ...

global___CloudInvocation = CloudInvocation
