"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.gitlab_application_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Changed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GITLAB_APPLICATION_FIELD_NUMBER: builtins.int
    @property
    def gitlab_application(self) -> dbtlabs.proto.private.v1.records.gitlab_application_pb2.GitlabApplication: ...
    def __init__(
        self,
        *,
        gitlab_application: dbtlabs.proto.private.v1.records.gitlab_application_pb2.GitlabApplication | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["gitlab_application", b"gitlab_application"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["gitlab_application", b"gitlab_application"]) -> None: ...

global___Changed = Changed
