# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/group_permission.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import group_permission_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_group__permission__pb2
from dbtlabs.proto.private.v1.common import event_options_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_common_dot_event__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6dbtlabs/proto/private/v1/events/group_permission.proto\x12\x1av1.events.group_permission\x1a\x37\x64\x62tlabs/proto/private/v1/records/group_permission.proto\x1a\x33\x64\x62tlabs/proto/private/v1/common/event_options.proto\"Z\n\x05\x41\x64\x64\x65\x64\x12\x35\n\x10group_permission\x18\x01 \x01(\x0b\x32\x1b.v1.records.GroupPermission:\x1a\x82\xb5\x18\x16Group Permission Added\"^\n\x07\x43hanged\x12\x35\n\x10group_permission\x18\x01 \x01(\x0b\x32\x1b.v1.records.GroupPermission:\x1c\x82\xb5\x18\x18Group Permission Changed\"^\n\x07Removed\x12\x35\n\x10group_permission\x18\x01 \x01(\x0b\x32\x1b.v1.records.GroupPermission:\x1c\x82\xb5\x18\x18Group Permission RemovedB=Z;github.com/dbt-labs/proto-golang/v1/events/group_permissionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.group_permission_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/dbt-labs/proto-golang/v1/events/group_permission'
  _globals['_ADDED']._loaded_options = None
  _globals['_ADDED']._serialized_options = b'\202\265\030\026Group Permission Added'
  _globals['_CHANGED']._loaded_options = None
  _globals['_CHANGED']._serialized_options = b'\202\265\030\030Group Permission Changed'
  _globals['_REMOVED']._loaded_options = None
  _globals['_REMOVED']._serialized_options = b'\202\265\030\030Group Permission Removed'
  _globals['_ADDED']._serialized_start=196
  _globals['_ADDED']._serialized_end=286
  _globals['_CHANGED']._serialized_start=288
  _globals['_CHANGED']._serialized_end=382
  _globals['_REMOVED']._serialized_start=384
  _globals['_REMOVED']._serialized_end=478
# @@protoc_insertion_point(module_scope)
