"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.integration_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Deleted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INTEGRATION_FIELD_NUMBER: builtins.int
    @property
    def integration(self) -> dbtlabs.proto.private.v1.records.integration_pb2.Integration: ...
    def __init__(
        self,
        *,
        integration: dbtlabs.proto.private.v1.records.integration_pb2.Integration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["integration", b"integration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["integration", b"integration"]) -> None: ...

global___Deleted = Deleted
