# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/invocation.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import invocation_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_invocation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0dbtlabs/proto/private/v1/events/invocation.proto\x12\x14v1.events.invocation\x1a\x31\x64\x62tlabs/proto/private/v1/records/invocation.proto\"7\n\tCompleted\x12*\n\ninvocation\x18\x01 \x01(\x0b\x32\x16.v1.records.InvocationB7Z5github.com/dbt-labs/proto-golang/v1/events/invocationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.invocation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/dbt-labs/proto-golang/v1/events/invocation'
  _globals['_COMPLETED']._serialized_start=125
  _globals['_COMPLETED']._serialized_end=180
# @@protoc_insertion_point(module_scope)
