"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.invocation_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Completed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INVOCATION_FIELD_NUMBER: builtins.int
    @property
    def invocation(self) -> dbtlabs.proto.private.v1.records.invocation_pb2.Invocation: ...
    def __init__(
        self,
        *,
        invocation: dbtlabs.proto.private.v1.records.invocation_pb2.Invocation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["invocation", b"invocation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["invocation", b"invocation"]) -> None: ...

global___Completed = Completed
