"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.ip_rule_set_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Changed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IP_RULE_SET_FIELD_NUMBER: builtins.int
    @property
    def ip_rule_set(self) -> dbtlabs.proto.private.v1.records.ip_rule_set_pb2.IPRuleSet: ...
    def __init__(
        self,
        *,
        ip_rule_set: dbtlabs.proto.private.v1.records.ip_rule_set_pb2.IPRuleSet | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ip_rule_set", b"ip_rule_set"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ip_rule_set", b"ip_rule_set"]) -> None: ...

global___Changed = Changed
