"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.ip_rule_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Added(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IP_RULE_FIELD_NUMBER: builtins.int
    @property
    def ip_rule(self) -> dbtlabs.proto.private.v1.records.ip_rule_pb2.IPRule: ...
    def __init__(
        self,
        *,
        ip_rule: dbtlabs.proto.private.v1.records.ip_rule_pb2.IPRule | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ip_rule", b"ip_rule"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ip_rule", b"ip_rule"]) -> None: ...

global___Added = Added

@typing.final
class Changed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IP_RULE_FIELD_NUMBER: builtins.int
    @property
    def ip_rule(self) -> dbtlabs.proto.private.v1.records.ip_rule_pb2.IPRule: ...
    def __init__(
        self,
        *,
        ip_rule: dbtlabs.proto.private.v1.records.ip_rule_pb2.IPRule | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ip_rule", b"ip_rule"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ip_rule", b"ip_rule"]) -> None: ...

global___Changed = Changed

@typing.final
class Removed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IP_RULE_FIELD_NUMBER: builtins.int
    @property
    def ip_rule(self) -> dbtlabs.proto.private.v1.records.ip_rule_pb2.IPRule: ...
    def __init__(
        self,
        *,
        ip_rule: dbtlabs.proto.private.v1.records.ip_rule_pb2.IPRule | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ip_rule", b"ip_rule"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ip_rule", b"ip_rule"]) -> None: ...

global___Removed = Removed
