"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.job_definition_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Added(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOB_DEFINITION_FIELD_NUMBER: builtins.int
    @property
    def job_definition(self) -> dbtlabs.proto.private.v1.records.job_definition_pb2.JobDefinition: ...
    def __init__(
        self,
        *,
        job_definition: dbtlabs.proto.private.v1.records.job_definition_pb2.JobDefinition | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["job_definition", b"job_definition"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["job_definition", b"job_definition"]) -> None: ...

global___Added = Added

@typing.final
class Changed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOB_DEFINITION_FIELD_NUMBER: builtins.int
    @property
    def job_definition(self) -> dbtlabs.proto.private.v1.records.job_definition_pb2.JobDefinition: ...
    def __init__(
        self,
        *,
        job_definition: dbtlabs.proto.private.v1.records.job_definition_pb2.JobDefinition | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["job_definition", b"job_definition"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["job_definition", b"job_definition"]) -> None: ...

global___Changed = Changed

@typing.final
class Removed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOB_DEFINITION_FIELD_NUMBER: builtins.int
    @property
    def job_definition(self) -> dbtlabs.proto.private.v1.records.job_definition_pb2.JobDefinition: ...
    def __init__(
        self,
        *,
        job_definition: dbtlabs.proto.private.v1.records.job_definition_pb2.JobDefinition | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["job_definition", b"job_definition"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["job_definition", b"job_definition"]) -> None: ...

global___Removed = Removed
