# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/job_definition.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import job_definition_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_job__definition__pb2
from dbtlabs.proto.private.v1.common import event_options_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_common_dot_event__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4dbtlabs/proto/private/v1/events/job_definition.proto\x12\x18v1.events.job_definition\x1a\x35\x64\x62tlabs/proto/private/v1/records/job_definition.proto\x1a\x33\x64\x62tlabs/proto/private/v1/common/event_options.proto\"I\n\x05\x41\x64\x64\x65\x64\x12\x31\n\x0ejob_definition\x18\x01 \x01(\x0b\x32\x19.v1.records.JobDefinition:\r\x82\xb5\x18\tJob Added\"M\n\x07\x43hanged\x12\x31\n\x0ejob_definition\x18\x01 \x01(\x0b\x32\x19.v1.records.JobDefinition:\x0f\x82\xb5\x18\x0bJob Changed\"M\n\x07Removed\x12\x31\n\x0ejob_definition\x18\x01 \x01(\x0b\x32\x19.v1.records.JobDefinition:\x0f\x82\xb5\x18\x0bJob RemovedB;Z9github.com/dbt-labs/proto-golang/v1/events/job_definitionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.job_definition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/dbt-labs/proto-golang/v1/events/job_definition'
  _globals['_ADDED']._loaded_options = None
  _globals['_ADDED']._serialized_options = b'\202\265\030\tJob Added'
  _globals['_CHANGED']._loaded_options = None
  _globals['_CHANGED']._serialized_options = b'\202\265\030\013Job Changed'
  _globals['_REMOVED']._loaded_options = None
  _globals['_REMOVED']._serialized_options = b'\202\265\030\013Job Removed'
  _globals['_ADDED']._serialized_start=190
  _globals['_ADDED']._serialized_end=263
  _globals['_CHANGED']._serialized_start=265
  _globals['_CHANGED']._serialized_end=342
  _globals['_REMOVED']._serialized_start=344
  _globals['_REMOVED']._serialized_end=421
# @@protoc_insertion_point(module_scope)
