"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.license_map_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Added(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LICENSE_MAP_FIELD_NUMBER: builtins.int
    @property
    def license_map(self) -> dbtlabs.proto.private.v1.records.license_map_pb2.LicenseMap: ...
    def __init__(
        self,
        *,
        license_map: dbtlabs.proto.private.v1.records.license_map_pb2.LicenseMap | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["license_map", b"license_map"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["license_map", b"license_map"]) -> None: ...

global___Added = Added

@typing.final
class Changed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LICENSE_MAP_FIELD_NUMBER: builtins.int
    @property
    def license_map(self) -> dbtlabs.proto.private.v1.records.license_map_pb2.LicenseMap: ...
    def __init__(
        self,
        *,
        license_map: dbtlabs.proto.private.v1.records.license_map_pb2.LicenseMap | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["license_map", b"license_map"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["license_map", b"license_map"]) -> None: ...

global___Changed = Changed

@typing.final
class Removed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LICENSE_MAP_FIELD_NUMBER: builtins.int
    @property
    def license_map(self) -> dbtlabs.proto.private.v1.records.license_map_pb2.LicenseMap: ...
    def __init__(
        self,
        *,
        license_map: dbtlabs.proto.private.v1.records.license_map_pb2.LicenseMap | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["license_map", b"license_map"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["license_map", b"license_map"]) -> None: ...

global___Removed = Removed
