# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/metadata.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import run_artifact_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_run__artifact__pb2
from dbtlabs.proto.private.v1.records import metadata_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_metadata__pb2
from dbtlabs.proto.private.v1.records import trace_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_trace__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.dbtlabs/proto/private/v1/events/metadata.proto\x12\x12v1.events.metadata\x1a\x33\x64\x62tlabs/proto/private/v1/records/run_artifact.proto\x1a/dbtlabs/proto/private/v1/records/metadata.proto\x1a,dbtlabs/proto/private/v1/records/trace.proto\"j\n\x08Ingested\x12-\n\x0crun_artifact\x18\x01 \x01(\x0b\x32\x17.v1.records.RunArtifact\x12%\n\x05trace\x18\x02 \x01(\x0b\x32\x11.v1.records.TraceH\x00\x88\x01\x01\x42\x08\n\x06_trace\"7\n\x06Parsed\x12-\n\x0crun_artifact\x18\x01 \x01(\x0b\x32\x17.v1.records.RunArtifact\"u\n\x13\x45nvironmentIngested\x12-\n\x0crun_artifact\x18\x01 \x01(\x0b\x32\x17.v1.records.RunArtifact\x12%\n\x05trace\x18\x02 \x01(\x0b\x32\x11.v1.records.TraceH\x00\x88\x01\x01\x42\x08\n\x06_trace\"E\n\x12\x45xposureTileViewed\x12/\n\rexposure_tile\x18\x01 \x01(\x0b\x32\x18.v1.records.ExposureTileB5Z3github.com/dbt-labs/proto-golang/v1/events/metadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/dbt-labs/proto-golang/v1/events/metadata'
  _globals['_INGESTED']._serialized_start=218
  _globals['_INGESTED']._serialized_end=324
  _globals['_PARSED']._serialized_start=326
  _globals['_PARSED']._serialized_end=381
  _globals['_ENVIRONMENTINGESTED']._serialized_start=383
  _globals['_ENVIRONMENTINGESTED']._serialized_end=500
  _globals['_EXPOSURETILEVIEWED']._serialized_start=502
  _globals['_EXPOSURETILEVIEWED']._serialized_end=571
# @@protoc_insertion_point(module_scope)
