"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.metadata_pb2
import dbtlabs.proto.private.v1.records.run_artifact_pb2
import dbtlabs.proto.private.v1.records.trace_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Ingested(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ARTIFACT_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    @property
    def run_artifact(self) -> dbtlabs.proto.private.v1.records.run_artifact_pb2.RunArtifact: ...
    @property
    def trace(self) -> dbtlabs.proto.private.v1.records.trace_pb2.Trace: ...
    def __init__(
        self,
        *,
        run_artifact: dbtlabs.proto.private.v1.records.run_artifact_pb2.RunArtifact | None = ...,
        trace: dbtlabs.proto.private.v1.records.trace_pb2.Trace | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_trace", b"_trace", "run_artifact", b"run_artifact", "trace", b"trace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_trace", b"_trace", "run_artifact", b"run_artifact", "trace", b"trace"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_trace", b"_trace"]) -> typing.Literal["trace"] | None: ...

global___Ingested = Ingested

@typing.final
class Parsed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ARTIFACT_FIELD_NUMBER: builtins.int
    @property
    def run_artifact(self) -> dbtlabs.proto.private.v1.records.run_artifact_pb2.RunArtifact: ...
    def __init__(
        self,
        *,
        run_artifact: dbtlabs.proto.private.v1.records.run_artifact_pb2.RunArtifact | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["run_artifact", b"run_artifact"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["run_artifact", b"run_artifact"]) -> None: ...

global___Parsed = Parsed

@typing.final
class EnvironmentIngested(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ARTIFACT_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    @property
    def run_artifact(self) -> dbtlabs.proto.private.v1.records.run_artifact_pb2.RunArtifact: ...
    @property
    def trace(self) -> dbtlabs.proto.private.v1.records.trace_pb2.Trace: ...
    def __init__(
        self,
        *,
        run_artifact: dbtlabs.proto.private.v1.records.run_artifact_pb2.RunArtifact | None = ...,
        trace: dbtlabs.proto.private.v1.records.trace_pb2.Trace | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_trace", b"_trace", "run_artifact", b"run_artifact", "trace", b"trace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_trace", b"_trace", "run_artifact", b"run_artifact", "trace", b"trace"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_trace", b"_trace"]) -> typing.Literal["trace"] | None: ...

global___EnvironmentIngested = EnvironmentIngested

@typing.final
class ExposureTileViewed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXPOSURE_TILE_FIELD_NUMBER: builtins.int
    @property
    def exposure_tile(self) -> dbtlabs.proto.private.v1.records.metadata_pb2.ExposureTile: ...
    def __init__(
        self,
        *,
        exposure_tile: dbtlabs.proto.private.v1.records.metadata_pb2.ExposureTile | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["exposure_tile", b"exposure_tile"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["exposure_tile", b"exposure_tile"]) -> None: ...

global___ExposureTileViewed = ExposureTileViewed
