# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/microsoft_entra_application.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import microsoft_entra_application_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_microsoft__entra__application__pb2
from dbtlabs.proto.private.v1.common import event_options_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_common_dot_event__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAdbtlabs/proto/private/v1/events/microsoft_entra_application.proto\x12%v1.events.microsoft_entra_application\x1a\x42\x64\x62tlabs/proto/private/v1/records/microsoft_entra_application.proto\x1a\x33\x64\x62tlabs/proto/private/v1/common/event_options.proto\"z\n\x05\x41\x64\x64\x65\x64\x12J\n\x1bmicrosoft_entra_application\x18\x01 \x01(\x0b\x32%.v1.records.MicrosoftEntraApplication:%\x82\xb5\x18!Microsoft Entra Application Added\"~\n\x07\x43hanged\x12J\n\x1bmicrosoft_entra_application\x18\x01 \x01(\x0b\x32%.v1.records.MicrosoftEntraApplication:\'\x82\xb5\x18#Microsoft Entra Application Changed\"~\n\x07Removed\x12J\n\x1bmicrosoft_entra_application\x18\x01 \x01(\x0b\x32%.v1.records.MicrosoftEntraApplication:\'\x82\xb5\x18#Microsoft Entra Application RemovedBHZFgithub.com/dbt-labs/proto-golang/v1/events/microsoft_entra_applicationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.microsoft_entra_application_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/dbt-labs/proto-golang/v1/events/microsoft_entra_application'
  _globals['_ADDED']._loaded_options = None
  _globals['_ADDED']._serialized_options = b'\202\265\030!Microsoft Entra Application Added'
  _globals['_CHANGED']._loaded_options = None
  _globals['_CHANGED']._serialized_options = b'\202\265\030#Microsoft Entra Application Changed'
  _globals['_REMOVED']._loaded_options = None
  _globals['_REMOVED']._serialized_options = b'\202\265\030#Microsoft Entra Application Removed'
  _globals['_ADDED']._serialized_start=229
  _globals['_ADDED']._serialized_end=351
  _globals['_CHANGED']._serialized_start=353
  _globals['_CHANGED']._serialized_end=479
  _globals['_REMOVED']._serialized_start=481
  _globals['_REMOVED']._serialized_end=607
# @@protoc_insertion_point(module_scope)
