"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ModelExecution(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _StatusCode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ModelExecution._StatusCode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STATUS_CODE_SUCCESS: ModelExecution._StatusCode.ValueType  # 0
        STATUS_CODE_WARNING: ModelExecution._StatusCode.ValueType  # 1
        STATUS_CODE_FAILURE: ModelExecution._StatusCode.ValueType  # 2
        STATUS_CODE_SKIPPED: ModelExecution._StatusCode.ValueType  # 3

    class StatusCode(_StatusCode, metaclass=_StatusCodeEnumTypeWrapper): ...
    STATUS_CODE_SUCCESS: ModelExecution.StatusCode.ValueType  # 0
    STATUS_CODE_WARNING: ModelExecution.StatusCode.ValueType  # 1
    STATUS_CODE_FAILURE: ModelExecution.StatusCode.ValueType  # 2
    STATUS_CODE_SKIPPED: ModelExecution.StatusCode.ValueType  # 3

    RUN_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    UNIQUE_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    GROUP_NAME_FIELD_NUMBER: builtins.int
    GROUP_OWNER_NAME_FIELD_NUMBER: builtins.int
    GROUP_OWNER_EMAIL_FIELD_NUMBER: builtins.int
    GROUP_OWNER_SLACK_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    ENVIRONMENT_ID_FIELD_NUMBER: builtins.int
    IS_MODEL_FIELD_NUMBER: builtins.int
    GROUP_OWNER_EMAILS_FIELD_NUMBER: builtins.int
    ACCOUNT_IDENTIFIER_FIELD_NUMBER: builtins.int
    ACCOUNT_PLAN_FIELD_NUMBER: builtins.int
    run_id: builtins.str
    name: builtins.str
    unique_id: builtins.str
    status: global___ModelExecution.StatusCode.ValueType
    group_name: builtins.str
    group_owner_name: builtins.str
    group_owner_email: builtins.str
    group_owner_slack: builtins.str
    account_id: builtins.str
    environment_id: builtins.str
    is_model: builtins.bool
    account_identifier: builtins.str
    """Temporarily optional until the migration is complete"""
    account_plan: builtins.str
    @property
    def group_owner_emails(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        run_id: builtins.str = ...,
        name: builtins.str = ...,
        unique_id: builtins.str = ...,
        status: global___ModelExecution.StatusCode.ValueType = ...,
        group_name: builtins.str = ...,
        group_owner_name: builtins.str = ...,
        group_owner_email: builtins.str = ...,
        group_owner_slack: builtins.str = ...,
        account_id: builtins.str = ...,
        environment_id: builtins.str = ...,
        is_model: builtins.bool = ...,
        group_owner_emails: collections.abc.Iterable[builtins.str] | None = ...,
        account_identifier: builtins.str | None = ...,
        account_plan: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_account_identifier", b"_account_identifier", "account_identifier", b"account_identifier"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_account_identifier", b"_account_identifier", "account_id", b"account_id", "account_identifier", b"account_identifier", "account_plan", b"account_plan", "environment_id", b"environment_id", "group_name", b"group_name", "group_owner_email", b"group_owner_email", "group_owner_emails", b"group_owner_emails", "group_owner_name", b"group_owner_name", "group_owner_slack", b"group_owner_slack", "is_model", b"is_model", "name", b"name", "run_id", b"run_id", "status", b"status", "unique_id", b"unique_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_account_identifier", b"_account_identifier"]) -> typing.Literal["account_identifier"] | None: ...

global___ModelExecution = ModelExecution
