# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/notifications_internal.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<dbtlabs/proto/private/v1/events/notifications_internal.proto\x12 v1.events.notifications_internal\"H\n\x0e\x44ispatchEmails\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x15\n\remail_address\x18\x02 \x03(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x03\"A\n\x15\x44ispatchSlackMessages\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x18\n\x10slack_channel_id\x18\x02 \x01(\t\"L\n\x15\x44ispatchTeamsMessages\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x12\n\nchannel_id\x18\x02 \x01(\t\x12\x0f\n\x07team_id\x18\x03 \x01(\t\"\xdd\x03\n\x10\x44ispatchWebhooks\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x12\n\nevent_type\x18\x04 \x01(\t\x12\x12\n\nwebhook_id\x18\x05 \x01(\t\x12\x14\n\x0cwebhook_name\x18\x06 \x01(\t\x12\x13\n\x0bwebhook_url\x18\x07 \x01(\t\x12\x0c\n\x04hmac\x18\x08 \x01(\t\x12\x0e\n\x06job_id\x18\t \x01(\t\x12\x10\n\x08job_name\x18\n \x01(\t\x12\x0e\n\x06run_id\x18\x0b \x01(\t\x12\x16\n\x0e\x65nvironment_id\x18\x0c \x01(\t\x12\x18\n\x10\x65nvironment_name\x18\r \x01(\t\x12\x13\n\x0b\x64\x62t_version\x18\x0e \x01(\t\x12\x14\n\x0cproject_name\x18\x0f \x01(\t\x12\x12\n\nproject_id\x18\x10 \x01(\t\x12\x12\n\nrun_status\x18\x11 \x01(\t\x12\x17\n\x0frun_status_code\x18\x12 \x01(\x03\x12\x1a\n\x12run_status_message\x18\x13 \x01(\t\x12\x12\n\nrun_reason\x18\x14 \x01(\t\x12\x16\n\x0erun_started_at\x18\x15 \x01(\t\x12\x17\n\x0frun_finished_at\x18\x16 \x01(\tBCZAgithub.com/dbt-labs/proto-golang/v1/events/notifications_internalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.notifications_internal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/dbt-labs/proto-golang/v1/events/notifications_internal'
  _globals['_DISPATCHEMAILS']._serialized_start=98
  _globals['_DISPATCHEMAILS']._serialized_end=170
  _globals['_DISPATCHSLACKMESSAGES']._serialized_start=172
  _globals['_DISPATCHSLACKMESSAGES']._serialized_end=237
  _globals['_DISPATCHTEAMSMESSAGES']._serialized_start=239
  _globals['_DISPATCHTEAMSMESSAGES']._serialized_end=315
  _globals['_DISPATCHWEBHOOKS']._serialized_start=318
  _globals['_DISPATCHWEBHOOKS']._serialized_end=795
# @@protoc_insertion_point(module_scope)
