# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/notifications.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.events import model_execution_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_events_dot_model__execution__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3dbtlabs/proto/private/v1/events/notifications.proto\x12\x17v1.events.notifications\x1a\x35\x64\x62tlabs/proto/private/v1/events/model_execution.proto\"\xd2\x01\n\x11ModelNotification\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x1a\n\x12\x61\x63\x63ount_identifier\x18\x02 \x01(\t\x12\x0e\n\x06run_id\x18\x03 \x01(\t\x12\x16\n\x0e\x65nvironment_id\x18\x04 \x01(\t\x12\x38\n\x07\x64\x65tails\x18\x05 \x03(\x0b\x32\'.v1.events.notifications.NodeExecDetail\x12\x17\n\x0f\x65mail_addresses\x18\x06 \x03(\t\x12\x12\n\nis_summary\x18\x07 \x01(\x08\"\xae\x01\n\x0eNodeExecDetail\x12\x34\n\tnode_type\x18\x01 \x01(\x0e\x32!.v1.events.notifications.NodeType\x12\x44\n\x06status\x18\x02 \x01(\x0e\x32\x34.v1.events.model_execution.ModelExecution.StatusCode\x12\x11\n\tresources\x18\x03 \x03(\t\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\"m\n\x10NotificationTest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x1a\n\x12\x61\x63\x63ount_identifier\x18\x03 \x01(\t\x12\x17\n\x0fsubscription_id\x18\x04 \x01(\t*N\n\x08NodeType\x12\x19\n\x15NODE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fNODE_TYPE_MODEL\x10\x01\x12\x12\n\x0eNODE_TYPE_TEST\x10\x02\x42:Z8github.com/dbt-labs/proto-golang/v1/events/notificationsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.notifications_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/dbt-labs/proto-golang/v1/events/notifications'
  _globals['_NODETYPE']._serialized_start=636
  _globals['_NODETYPE']._serialized_end=714
  _globals['_MODELNOTIFICATION']._serialized_start=136
  _globals['_MODELNOTIFICATION']._serialized_end=346
  _globals['_NODEEXECDETAIL']._serialized_start=349
  _globals['_NODEEXECDETAIL']._serialized_end=523
  _globals['_NOTIFICATIONTEST']._serialized_start=525
  _globals['_NOTIFICATIONTEST']._serialized_end=634
# @@protoc_insertion_point(module_scope)
