"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import dbtlabs.proto.private.v1.records.oauth_client_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Added(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OAUTH_CLIENT_FIELD_NUMBER: builtins.int
    TS_FIELD_NUMBER: builtins.int
    @property
    def oauth_client(self) -> dbtlabs.proto.private.v1.records.oauth_client_pb2.OAuthClient: ...
    @property
    def ts(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        oauth_client: dbtlabs.proto.private.v1.records.oauth_client_pb2.OAuthClient | None = ...,
        ts: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["oauth_client", b"oauth_client", "ts", b"ts"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["oauth_client", b"oauth_client", "ts", b"ts"]) -> None: ...

global___Added = Added

@typing.final
class Removed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OAUTH_CLIENT_FIELD_NUMBER: builtins.int
    TS_FIELD_NUMBER: builtins.int
    REMOVAL_REASON_FIELD_NUMBER: builtins.int
    REMOVED_BY_USER_ID_FIELD_NUMBER: builtins.int
    removal_reason: builtins.str
    removed_by_user_id: builtins.str
    @property
    def oauth_client(self) -> dbtlabs.proto.private.v1.records.oauth_client_pb2.OAuthClient: ...
    @property
    def ts(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        oauth_client: dbtlabs.proto.private.v1.records.oauth_client_pb2.OAuthClient | None = ...,
        ts: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        removal_reason: builtins.str = ...,
        removed_by_user_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["oauth_client", b"oauth_client", "ts", b"ts"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["oauth_client", b"oauth_client", "removal_reason", b"removal_reason", "removed_by_user_id", b"removed_by_user_id", "ts", b"ts"]) -> None: ...

global___Removed = Removed

@typing.final
class Authorized(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OAUTH_CLIENT_FIELD_NUMBER: builtins.int
    TS_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    SCOPES_FIELD_NUMBER: builtins.int
    PROJECT_IDS_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    @property
    def oauth_client(self) -> dbtlabs.proto.private.v1.records.oauth_client_pb2.OAuthClient: ...
    @property
    def ts(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def scopes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def project_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        oauth_client: dbtlabs.proto.private.v1.records.oauth_client_pb2.OAuthClient | None = ...,
        ts: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        user_id: builtins.str = ...,
        scopes: collections.abc.Iterable[builtins.str] | None = ...,
        project_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["oauth_client", b"oauth_client", "ts", b"ts"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["oauth_client", b"oauth_client", "project_ids", b"project_ids", "scopes", b"scopes", "ts", b"ts", "user_id", b"user_id"]) -> None: ...

global___Authorized = Authorized

@typing.final
class Denied(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OAUTH_CLIENT_FIELD_NUMBER: builtins.int
    TS_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    REQUESTED_SCOPES_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    @property
    def oauth_client(self) -> dbtlabs.proto.private.v1.records.oauth_client_pb2.OAuthClient: ...
    @property
    def ts(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def requested_scopes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        oauth_client: dbtlabs.proto.private.v1.records.oauth_client_pb2.OAuthClient | None = ...,
        ts: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        user_id: builtins.str = ...,
        requested_scopes: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["oauth_client", b"oauth_client", "ts", b"ts"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["oauth_client", b"oauth_client", "requested_scopes", b"requested_scopes", "ts", b"ts", "user_id", b"user_id"]) -> None: ...

global___Denied = Denied
