"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.permission_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Added(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PERMISSION_FIELD_NUMBER: builtins.int
    @property
    def permission(self) -> dbtlabs.proto.private.v1.records.permission_pb2.Permission: ...
    def __init__(
        self,
        *,
        permission: dbtlabs.proto.private.v1.records.permission_pb2.Permission | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["permission", b"permission"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["permission", b"permission"]) -> None: ...

global___Added = Added

@typing.final
class Removed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PERMISSION_FIELD_NUMBER: builtins.int
    @property
    def permission(self) -> dbtlabs.proto.private.v1.records.permission_pb2.Permission: ...
    def __init__(
        self,
        *,
        permission: dbtlabs.proto.private.v1.records.permission_pb2.Permission | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["permission", b"permission"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["permission", b"permission"]) -> None: ...

global___Removed = Removed
