# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/profile.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import profile_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_profile__pb2
from dbtlabs.proto.private.v1.common import event_options_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_common_dot_event__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-dbtlabs/proto/private/v1/events/profile.proto\x12\x11v1.events.profile\x1a.dbtlabs/proto/private/v1/records/profile.proto\x1a\x33\x64\x62tlabs/proto/private/v1/common/event_options.proto\"K\n\x05\x41\x64\x64\x65\x64\x12$\n\x07profile\x18\x01 \x01(\x0b\x32\x13.v1.records.Profile:\x1c\x82\xb5\x18\x18Profile Added to Project\"O\n\x07\x43hanged\x12$\n\x07profile\x18\x01 \x01(\x0b\x32\x13.v1.records.Profile:\x1e\x82\xb5\x18\x1aProfile Changed in Project\"Q\n\x07Removed\x12$\n\x07profile\x18\x01 \x01(\x0b\x32\x13.v1.records.Profile: \x82\xb5\x18\x1cProfile Removed from ProjectB4Z2github.com/dbt-labs/proto-golang/v1/events/profileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/dbt-labs/proto-golang/v1/events/profile'
  _globals['_ADDED']._loaded_options = None
  _globals['_ADDED']._serialized_options = b'\202\265\030\030Profile Added to Project'
  _globals['_CHANGED']._loaded_options = None
  _globals['_CHANGED']._serialized_options = b'\202\265\030\032Profile Changed in Project'
  _globals['_REMOVED']._loaded_options = None
  _globals['_REMOVED']._serialized_options = b'\202\265\030\034Profile Removed from Project'
  _globals['_ADDED']._serialized_start=169
  _globals['_ADDED']._serialized_end=244
  _globals['_CHANGED']._serialized_start=246
  _globals['_CHANGED']._serialized_end=325
  _globals['_REMOVED']._serialized_start=327
  _globals['_REMOVED']._serialized_end=408
# @@protoc_insertion_point(module_scope)
