# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/refresh_token.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import refresh_token_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_refresh__token__pb2
from dbtlabs.proto.private.v1.common import event_options_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_common_dot_event__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3dbtlabs/proto/private/v1/events/refresh_token.proto\x12\x17v1.events.refresh_token\x1a\x34\x64\x62tlabs/proto/private/v1/records/refresh_token.proto\x1a\x33\x64\x62tlabs/proto/private/v1/common/event_options.proto\"_\n\x12RefreshTokenIssued\x12/\n\rrefresh_token\x18\x01 \x01(\x0b\x32\x18.v1.records.RefreshToken:\x18\x82\xb5\x18\x14Refresh Token Issued\"y\n\x13RefreshTokenRevoked\x12/\n\rrefresh_token\x18\x01 \x01(\x0b\x32\x18.v1.records.RefreshToken\x12\x16\n\x0ereason_revoked\x18\x02 \x01(\t:\x19\x82\xb5\x18\x15Refresh Token RevokedB:Z8github.com/dbt-labs/proto-golang/v1/events/refresh_tokenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.refresh_token_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/dbt-labs/proto-golang/v1/events/refresh_token'
  _globals['_REFRESHTOKENISSUED']._loaded_options = None
  _globals['_REFRESHTOKENISSUED']._serialized_options = b'\202\265\030\024Refresh Token Issued'
  _globals['_REFRESHTOKENREVOKED']._loaded_options = None
  _globals['_REFRESHTOKENREVOKED']._serialized_options = b'\202\265\030\025Refresh Token Revoked'
  _globals['_REFRESHTOKENISSUED']._serialized_start=187
  _globals['_REFRESHTOKENISSUED']._serialized_end=282
  _globals['_REFRESHTOKENREVOKED']._serialized_start=284
  _globals['_REFRESHTOKENREVOKED']._serialized_end=405
# @@protoc_insertion_point(module_scope)
