"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.repository_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Added(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPOSITORY_FIELD_NUMBER: builtins.int
    @property
    def repository(self) -> dbtlabs.proto.private.v1.records.repository_pb2.Repository: ...
    def __init__(
        self,
        *,
        repository: dbtlabs.proto.private.v1.records.repository_pb2.Repository | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["repository", b"repository"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["repository", b"repository"]) -> None: ...

global___Added = Added

@typing.final
class Changed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPOSITORY_FIELD_NUMBER: builtins.int
    @property
    def repository(self) -> dbtlabs.proto.private.v1.records.repository_pb2.Repository: ...
    def __init__(
        self,
        *,
        repository: dbtlabs.proto.private.v1.records.repository_pb2.Repository | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["repository", b"repository"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["repository", b"repository"]) -> None: ...

global___Changed = Changed

@typing.final
class Removed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPOSITORY_FIELD_NUMBER: builtins.int
    @property
    def repository(self) -> dbtlabs.proto.private.v1.records.repository_pb2.Repository: ...
    def __init__(
        self,
        *,
        repository: dbtlabs.proto.private.v1.records.repository_pb2.Repository | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["repository", b"repository"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["repository", b"repository"]) -> None: ...

global___Removed = Removed
