"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.fields.httpstatus_pb2
import dbtlabs.proto.private.v1.fields.private_link_config_pb2
import dbtlabs.proto.private.v1.records.environment_variable_pb2
import dbtlabs.proto.private.v1.records.run_pb2
import dbtlabs.proto.private.v1.records.trace_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Started(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_FIELD_NUMBER: builtins.int
    @property
    def run(self) -> dbtlabs.proto.private.v1.records.run_pb2.Run: ...
    def __init__(
        self,
        *,
        run: dbtlabs.proto.private.v1.records.run_pb2.Run | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["run", b"run"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["run", b"run"]) -> None: ...

global___Started = Started

@typing.final
class Completed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_FIELD_NUMBER: builtins.int
    HAS_DOWNSTREAM_JOBS_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    HAS_WARNINGS_FIELD_NUMBER: builtins.int
    has_downstream_jobs: builtins.bool
    """true if this run could potentially trigger a downstream job"""
    has_warnings: builtins.bool
    """true if any model in the run has model-level warnings"""
    @property
    def run(self) -> dbtlabs.proto.private.v1.records.run_pb2.Run: ...
    @property
    def trace(self) -> dbtlabs.proto.private.v1.records.trace_pb2.Trace: ...
    def __init__(
        self,
        *,
        run: dbtlabs.proto.private.v1.records.run_pb2.Run | None = ...,
        has_downstream_jobs: builtins.bool = ...,
        trace: dbtlabs.proto.private.v1.records.trace_pb2.Trace | None = ...,
        has_warnings: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_trace", b"_trace", "run", b"run", "trace", b"trace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_trace", b"_trace", "has_downstream_jobs", b"has_downstream_jobs", "has_warnings", b"has_warnings", "run", b"run", "trace", b"trace"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_trace", b"_trace"]) -> typing.Literal["trace"] | None: ...

global___Completed = Completed

@typing.final
class CompletedForTemporaryRuntimeUseOnly(google.protobuf.message.Message):
    """CompletedForTemporaryRuntimeUseOnly is a deprecated message."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_FIELD_NUMBER: builtins.int
    ENVIRONMENT_VARIABLES_FIELD_NUMBER: builtins.int
    @property
    def run(self) -> dbtlabs.proto.private.v1.records.run_pb2.Run: ...
    @property
    def environment_variables(self) -> dbtlabs.proto.private.v1.records.environment_variable_pb2.EnvironmentVariables: ...
    def __init__(
        self,
        *,
        run: dbtlabs.proto.private.v1.records.run_pb2.Run | None = ...,
        environment_variables: dbtlabs.proto.private.v1.records.environment_variable_pb2.EnvironmentVariables | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["environment_variables", b"environment_variables", "run", b"run"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["environment_variables", b"environment_variables", "run", b"run"]) -> None: ...

global___CompletedForTemporaryRuntimeUseOnly = CompletedForTemporaryRuntimeUseOnly

@typing.final
class CancelRequest(google.protobuf.message.Message):
    """AMQP RPC event to request run cancellation from pods running in a
    cluster
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    message: builtins.str
    @property
    def run(self) -> dbtlabs.proto.private.v1.records.run_pb2.Run: ...
    @property
    def trace(self) -> dbtlabs.proto.private.v1.records.trace_pb2.Trace: ...
    def __init__(
        self,
        *,
        run: dbtlabs.proto.private.v1.records.run_pb2.Run | None = ...,
        message: builtins.str = ...,
        trace: dbtlabs.proto.private.v1.records.trace_pb2.Trace | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_trace", b"_trace", "run", b"run", "trace", b"trace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_trace", b"_trace", "message", b"message", "run", b"run", "trace", b"trace"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_trace", b"_trace"]) -> typing.Literal["trace"] | None: ...

global___CancelRequest = CancelRequest

@typing.final
class CancelResponse(google.protobuf.message.Message):
    """AMQP RPC event to respond to run cancellation of pods running in a
    cluster
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_FIELD_NUMBER: builtins.int
    STATUS_CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    status_code: dbtlabs.proto.private.v1.fields.httpstatus_pb2.HTTPStatusCode.ValueType
    message: builtins.str
    @property
    def run(self) -> dbtlabs.proto.private.v1.records.run_pb2.Run: ...
    def __init__(
        self,
        *,
        run: dbtlabs.proto.private.v1.records.run_pb2.Run | None = ...,
        status_code: dbtlabs.proto.private.v1.fields.httpstatus_pb2.HTTPStatusCode.ValueType = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["run", b"run"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "run", b"run", "status_code", b"status_code"]) -> None: ...

global___CancelResponse = CancelResponse

@typing.final
class Execute(google.protobuf.message.Message):
    """Once sent, this event will trigger a run to be executed."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_FIELD_NUMBER: builtins.int
    PRIVATE_LINK_ENABLED_FIELD_NUMBER: builtins.int
    DEFER_TO_STATE_FIELD_NUMBER: builtins.int
    DEFER_ARTIFACTS_REMOTE_PATH_FIELD_NUMBER: builtins.int
    RETRY_ARTIFACTS_REMOTE_PATH_FIELD_NUMBER: builtins.int
    PRIVATE_LINK_CONFIG_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    DEFER_GIT_SHA_FIELD_NUMBER: builtins.int
    private_link_enabled: builtins.bool
    defer_to_state: builtins.bool
    defer_artifacts_remote_path: builtins.str
    retry_artifacts_remote_path: builtins.str
    defer_git_sha: builtins.str
    @property
    def run(self) -> dbtlabs.proto.private.v1.records.run_pb2.Run: ...
    @property
    def private_link_config(self) -> dbtlabs.proto.private.v1.fields.private_link_config_pb2.PrivateLinkConfig: ...
    @property
    def trace(self) -> dbtlabs.proto.private.v1.records.trace_pb2.Trace: ...
    def __init__(
        self,
        *,
        run: dbtlabs.proto.private.v1.records.run_pb2.Run | None = ...,
        private_link_enabled: builtins.bool = ...,
        defer_to_state: builtins.bool = ...,
        defer_artifacts_remote_path: builtins.str = ...,
        retry_artifacts_remote_path: builtins.str = ...,
        private_link_config: dbtlabs.proto.private.v1.fields.private_link_config_pb2.PrivateLinkConfig | None = ...,
        trace: dbtlabs.proto.private.v1.records.trace_pb2.Trace | None = ...,
        defer_git_sha: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_trace", b"_trace", "private_link_config", b"private_link_config", "run", b"run", "trace", b"trace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_trace", b"_trace", "defer_artifacts_remote_path", b"defer_artifacts_remote_path", "defer_git_sha", b"defer_git_sha", "defer_to_state", b"defer_to_state", "private_link_config", b"private_link_config", "private_link_enabled", b"private_link_enabled", "retry_artifacts_remote_path", b"retry_artifacts_remote_path", "run", b"run", "trace", b"trace"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_trace", b"_trace"]) -> typing.Literal["trace"] | None: ...

global___Execute = Execute

@typing.final
class Cancel(google.protobuf.message.Message):
    """Once sent, this event will trigger a run to be cancelled. This is
    only targeting those runs handled by warm run pods.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    @property
    def run(self) -> dbtlabs.proto.private.v1.records.run_pb2.Run: ...
    @property
    def trace(self) -> dbtlabs.proto.private.v1.records.trace_pb2.Trace: ...
    def __init__(
        self,
        *,
        run: dbtlabs.proto.private.v1.records.run_pb2.Run | None = ...,
        trace: dbtlabs.proto.private.v1.records.trace_pb2.Trace | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_trace", b"_trace", "run", b"run", "trace", b"trace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_trace", b"_trace", "run", b"run", "trace", b"trace"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_trace", b"_trace"]) -> typing.Literal["trace"] | None: ...

global___Cancel = Cancel

@typing.final
class CancelConfirmationRequest(google.protobuf.message.Message):
    """AMQP RPC event to request confirmation of run cancellation"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    message: builtins.str
    @property
    def run(self) -> dbtlabs.proto.private.v1.records.run_pb2.Run: ...
    @property
    def trace(self) -> dbtlabs.proto.private.v1.records.trace_pb2.Trace: ...
    def __init__(
        self,
        *,
        run: dbtlabs.proto.private.v1.records.run_pb2.Run | None = ...,
        message: builtins.str = ...,
        trace: dbtlabs.proto.private.v1.records.trace_pb2.Trace | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_trace", b"_trace", "run", b"run", "trace", b"trace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_trace", b"_trace", "message", b"message", "run", b"run", "trace", b"trace"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_trace", b"_trace"]) -> typing.Literal["trace"] | None: ...

global___CancelConfirmationRequest = CancelConfirmationRequest

@typing.final
class CancelConfirmationResponse(google.protobuf.message.Message):
    """AMQP RPC event confirm run cancellation with a response"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_FIELD_NUMBER: builtins.int
    STATUS_CODE_FIELD_NUMBER: builtins.int
    CANCELLED_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    status_code: dbtlabs.proto.private.v1.fields.httpstatus_pb2.HTTPStatusCode.ValueType
    cancelled: builtins.bool
    message: builtins.str
    @property
    def run(self) -> dbtlabs.proto.private.v1.records.run_pb2.Run: ...
    def __init__(
        self,
        *,
        run: dbtlabs.proto.private.v1.records.run_pb2.Run | None = ...,
        status_code: dbtlabs.proto.private.v1.fields.httpstatus_pb2.HTTPStatusCode.ValueType = ...,
        cancelled: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["run", b"run"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cancelled", b"cancelled", "message", b"message", "run", b"run", "status_code", b"status_code"]) -> None: ...

global___CancelConfirmationResponse = CancelConfirmationResponse
