"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.scim_config_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Changed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCIM_CONFIG_FIELD_NUMBER: builtins.int
    @property
    def scim_config(self) -> dbtlabs.proto.private.v1.records.scim_config_pb2.SCIMConfig: ...
    def __init__(
        self,
        *,
        scim_config: dbtlabs.proto.private.v1.records.scim_config_pb2.SCIMConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["scim_config", b"scim_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["scim_config", b"scim_config"]) -> None: ...

global___Changed = Changed
