"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.search_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SearchIndexTriggered(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORD_FIELD_NUMBER: builtins.int
    @property
    def record(self) -> dbtlabs.proto.private.v1.records.search_pb2.SearchIndexTriggered: ...
    def __init__(
        self,
        *,
        record: dbtlabs.proto.private.v1.records.search_pb2.SearchIndexTriggered | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["record", b"record"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["record", b"record"]) -> None: ...

global___SearchIndexTriggered = SearchIndexTriggered
