"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.semantic_layer_config_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Added(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEMANTIC_LAYER_CONFIG_FIELD_NUMBER: builtins.int
    @property
    def semantic_layer_config(self) -> dbtlabs.proto.private.v1.records.semantic_layer_config_pb2.SemanticLayerConfig: ...
    def __init__(
        self,
        *,
        semantic_layer_config: dbtlabs.proto.private.v1.records.semantic_layer_config_pb2.SemanticLayerConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["semantic_layer_config", b"semantic_layer_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["semantic_layer_config", b"semantic_layer_config"]) -> None: ...

global___Added = Added

@typing.final
class Changed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEMANTIC_LAYER_CONFIG_FIELD_NUMBER: builtins.int
    @property
    def semantic_layer_config(self) -> dbtlabs.proto.private.v1.records.semantic_layer_config_pb2.SemanticLayerConfig: ...
    def __init__(
        self,
        *,
        semantic_layer_config: dbtlabs.proto.private.v1.records.semantic_layer_config_pb2.SemanticLayerConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["semantic_layer_config", b"semantic_layer_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["semantic_layer_config", b"semantic_layer_config"]) -> None: ...

global___Changed = Changed

@typing.final
class Removed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEMANTIC_LAYER_CONFIG_FIELD_NUMBER: builtins.int
    @property
    def semantic_layer_config(self) -> dbtlabs.proto.private.v1.records.semantic_layer_config_pb2.SemanticLayerConfig: ...
    def __init__(
        self,
        *,
        semantic_layer_config: dbtlabs.proto.private.v1.records.semantic_layer_config_pb2.SemanticLayerConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["semantic_layer_config", b"semantic_layer_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["semantic_layer_config", b"semantic_layer_config"]) -> None: ...

global___Removed = Removed
