"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.user_group_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Added(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_GROUP_FIELD_NUMBER: builtins.int
    @property
    def user_group(self) -> dbtlabs.proto.private.v1.records.user_group_pb2.UserGroup: ...
    def __init__(
        self,
        *,
        user_group: dbtlabs.proto.private.v1.records.user_group_pb2.UserGroup | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["user_group", b"user_group"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["user_group", b"user_group"]) -> None: ...

global___Added = Added

@typing.final
class Changed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_GROUP_FIELD_NUMBER: builtins.int
    @property
    def user_group(self) -> dbtlabs.proto.private.v1.records.user_group_pb2.UserGroup: ...
    def __init__(
        self,
        *,
        user_group: dbtlabs.proto.private.v1.records.user_group_pb2.UserGroup | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["user_group", b"user_group"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["user_group", b"user_group"]) -> None: ...

global___Changed = Changed

@typing.final
class Removed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_GROUP_FIELD_NUMBER: builtins.int
    @property
    def user_group(self) -> dbtlabs.proto.private.v1.records.user_group_pb2.UserGroup: ...
    def __init__(
        self,
        *,
        user_group: dbtlabs.proto.private.v1.records.user_group_pb2.UserGroup | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["user_group", b"user_group"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["user_group", b"user_group"]) -> None: ...

global___Removed = Removed
