# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/user_license.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import user_license_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_user__license__pb2
from dbtlabs.proto.private.v1.records import user_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_user__pb2
from dbtlabs.proto.private.v1.common import event_options_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_common_dot_event__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2dbtlabs/proto/private/v1/events/user_license.proto\x12\x16v1.events.user_license\x1a\x33\x64\x62tlabs/proto/private/v1/records/user_license.proto\x1a+dbtlabs/proto/private/v1/records/user.proto\x1a\x33\x64\x62tlabs/proto/private/v1/common/event_options.proto\"p\n\x05\x41\x64\x64\x65\x64\x12\x1e\n\x04user\x18\x01 \x01(\x0b\x32\x10.v1.records.User\x12-\n\x0cuser_license\x18\x02 \x01(\x0b\x32\x17.v1.records.UserLicense:\x18\x82\xb5\x18\x14User License Created\"r\n\x07\x43hanged\x12\x1e\n\x04user\x18\x01 \x01(\x0b\x32\x10.v1.records.User\x12-\n\x0cuser_license\x18\x02 \x01(\x0b\x32\x17.v1.records.UserLicense:\x18\x82\xb5\x18\x14User License Changed\"r\n\x07Removed\x12\x1e\n\x04user\x18\x01 \x01(\x0b\x32\x10.v1.records.User\x12-\n\x0cuser_license\x18\x02 \x01(\x0b\x32\x17.v1.records.UserLicense:\x18\x82\xb5\x18\x14User License RemovedB9Z7github.com/dbt-labs/proto-golang/v1/events/user_licenseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.user_license_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/dbt-labs/proto-golang/v1/events/user_license'
  _globals['_ADDED']._loaded_options = None
  _globals['_ADDED']._serialized_options = b'\202\265\030\024User License Created'
  _globals['_CHANGED']._loaded_options = None
  _globals['_CHANGED']._serialized_options = b'\202\265\030\024User License Changed'
  _globals['_REMOVED']._loaded_options = None
  _globals['_REMOVED']._serialized_options = b'\202\265\030\024User License Removed'
  _globals['_ADDED']._serialized_start=229
  _globals['_ADDED']._serialized_end=341
  _globals['_CHANGED']._serialized_start=343
  _globals['_CHANGED']._serialized_end=457
  _globals['_REMOVED']._serialized_start=459
  _globals['_REMOVED']._serialized_end=573
# @@protoc_insertion_point(module_scope)
