"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.warehouse_extraction_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class StartRequested(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAREHOUSE_EXTRACTION_FIELD_NUMBER: builtins.int
    @property
    def warehouse_extraction(self) -> dbtlabs.proto.private.v1.records.warehouse_extraction_pb2.WarehouseExtraction: ...
    def __init__(
        self,
        *,
        warehouse_extraction: dbtlabs.proto.private.v1.records.warehouse_extraction_pb2.WarehouseExtraction | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["warehouse_extraction", b"warehouse_extraction"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["warehouse_extraction", b"warehouse_extraction"]) -> None: ...

global___StartRequested = StartRequested
