# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/webhooks_subscription.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.records import webhooks_subscription_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_records_dot_webhooks__subscription__pb2
from dbtlabs.proto.private.v1.common import event_options_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_common_dot_event__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;dbtlabs/proto/private/v1/events/webhooks_subscription.proto\x12\x1fv1.events.webhooks_subscription\x1a<dbtlabs/proto/private/v1/records/webhooks_subscription.proto\x1a\x33\x64\x62tlabs/proto/private/v1/common/event_options.proto\"`\n\x05\x41\x64\x64\x65\x64\x12\x36\n\x0csubscription\x18\x01 \x01(\x0b\x32 .v1.records.WebhooksSubscription:\x1f\x82\xb5\x18\x1bWebhooks Subscription Added\"d\n\x07\x43hanged\x12\x36\n\x0csubscription\x18\x01 \x01(\x0b\x32 .v1.records.WebhooksSubscription:!\x82\xb5\x18\x1dWebhooks Subscription Changed\"d\n\x07Removed\x12\x36\n\x0csubscription\x18\x01 \x01(\x0b\x32 .v1.records.WebhooksSubscription:!\x82\xb5\x18\x1dWebhooks Subscription RemovedBBZ@github.com/dbt-labs/proto-golang/v1/events/webhooks_subscriptionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.webhooks_subscription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/dbt-labs/proto-golang/v1/events/webhooks_subscription'
  _globals['_ADDED']._loaded_options = None
  _globals['_ADDED']._serialized_options = b'\202\265\030\033Webhooks Subscription Added'
  _globals['_CHANGED']._loaded_options = None
  _globals['_CHANGED']._serialized_options = b'\202\265\030\035Webhooks Subscription Changed'
  _globals['_REMOVED']._loaded_options = None
  _globals['_REMOVED']._serialized_options = b'\202\265\030\035Webhooks Subscription Removed'
  _globals['_ADDED']._serialized_start=211
  _globals['_ADDED']._serialized_end=307
  _globals['_CHANGED']._serialized_start=309
  _globals['_CHANGED']._serialized_end=409
  _globals['_REMOVED']._serialized_start=411
  _globals['_REMOVED']._serialized_end=511
# @@protoc_insertion_point(module_scope)
