"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.records.webhooks_subscription_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Added(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBSCRIPTION_FIELD_NUMBER: builtins.int
    @property
    def subscription(self) -> dbtlabs.proto.private.v1.records.webhooks_subscription_pb2.WebhooksSubscription: ...
    def __init__(
        self,
        *,
        subscription: dbtlabs.proto.private.v1.records.webhooks_subscription_pb2.WebhooksSubscription | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["subscription", b"subscription"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["subscription", b"subscription"]) -> None: ...

global___Added = Added

@typing.final
class Changed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBSCRIPTION_FIELD_NUMBER: builtins.int
    @property
    def subscription(self) -> dbtlabs.proto.private.v1.records.webhooks_subscription_pb2.WebhooksSubscription: ...
    def __init__(
        self,
        *,
        subscription: dbtlabs.proto.private.v1.records.webhooks_subscription_pb2.WebhooksSubscription | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["subscription", b"subscription"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["subscription", b"subscription"]) -> None: ...

global___Changed = Changed

@typing.final
class Removed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBSCRIPTION_FIELD_NUMBER: builtins.int
    @property
    def subscription(self) -> dbtlabs.proto.private.v1.records.webhooks_subscription_pb2.WebhooksSubscription: ...
    def __init__(
        self,
        *,
        subscription: dbtlabs.proto.private.v1.records.webhooks_subscription_pb2.WebhooksSubscription | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["subscription", b"subscription"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["subscription", b"subscription"]) -> None: ...

global___Removed = Removed
