"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class LspRequest(google.protobuf.message.Message):
    """Span emitted for an inbound LSP request or notification handled by dbt-lsp
    that targets at most a single document (with optional cursor position or
    range). Use `LspCommandRequest` for `workspace/executeCommand` invocations
    and `LspBatchFileRequest` for requests that span multiple URIs.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METHOD_FIELD_NUMBER: builtins.int
    URI_FIELD_NUMBER: builtins.int
    LINE_FIELD_NUMBER: builtins.int
    CHARACTER_FIELD_NUMBER: builtins.int
    END_LINE_FIELD_NUMBER: builtins.int
    END_CHARACTER_FIELD_NUMBER: builtins.int
    method: builtins.str
    """LSP method name, e.g. "textDocument/references", "textDocument/rename"."""
    uri: builtins.str
    """URI of the document the request targets, if any."""
    line: builtins.int
    """Cursor line (0-based) for position-bearing requests."""
    character: builtins.int
    """Cursor character (0-based) for position-bearing requests."""
    end_line: builtins.int
    """End line (0-based, exclusive) for range-bearing requests."""
    end_character: builtins.int
    """End character (0-based, exclusive) for range-bearing requests."""
    def __init__(
        self,
        *,
        method: builtins.str = ...,
        uri: builtins.str | None = ...,
        line: builtins.int | None = ...,
        character: builtins.int | None = ...,
        end_line: builtins.int | None = ...,
        end_character: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_character", b"_character", "_end_character", b"_end_character", "_end_line", b"_end_line", "_line", b"_line", "_uri", b"_uri", "character", b"character", "end_character", b"end_character", "end_line", b"end_line", "line", b"line", "uri", b"uri"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_character", b"_character", "_end_character", b"_end_character", "_end_line", b"_end_line", "_line", b"_line", "_uri", b"_uri", "character", b"character", "end_character", b"end_character", "end_line", b"end_line", "line", b"line", "method", b"method", "uri", b"uri"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_character", b"_character"]) -> typing.Literal["character"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_end_character", b"_end_character"]) -> typing.Literal["end_character"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_end_line", b"_end_line"]) -> typing.Literal["end_line"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_line", b"_line"]) -> typing.Literal["line"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_uri", b"_uri"]) -> typing.Literal["uri"] | None: ...

global___LspRequest = LspRequest

@typing.final
class LspCommandRequest(google.protobuf.message.Message):
    """Span emitted for an LSP request that dispatches a named command, typically
    `workspace/executeCommand`. The custom `command` field captures which
    command was invoked, since the LSP `method` alone is not enough to
    distinguish dbt-lsp custom commands (e.g. dbt.show, dbt.compileFile).
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METHOD_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    URI_FIELD_NUMBER: builtins.int
    method: builtins.str
    """LSP method name, typically "workspace/executeCommand"."""
    command: builtins.str
    """The custom command that was invoked, e.g. "dbt.show", "dbt.compileFile"."""
    uri: builtins.str
    """URI of the document the command targets, if the command operates on a
    specific file.
    """
    def __init__(
        self,
        *,
        method: builtins.str = ...,
        command: builtins.str = ...,
        uri: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_uri", b"_uri", "uri", b"uri"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_uri", b"_uri", "command", b"command", "method", b"method", "uri", b"uri"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_uri", b"_uri"]) -> typing.Literal["uri"] | None: ...

global___LspCommandRequest = LspCommandRequest

@typing.final
class LspBatchFileRequest(google.protobuf.message.Message):
    """Span emitted for an LSP request or notification that targets multiple URIs
    at once, e.g. "workspace/willRenameFiles" or
    "workspace/didChangeWatchedFiles".
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METHOD_FIELD_NUMBER: builtins.int
    URIS_FIELD_NUMBER: builtins.int
    method: builtins.str
    """LSP method name, e.g. "workspace/willRenameFiles"."""
    @property
    def uris(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """All URIs affected by this request."""

    def __init__(
        self,
        *,
        method: builtins.str = ...,
        uris: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["method", b"method", "uris", b"uris"]) -> None: ...

global___LspBatchFileRequest = LspBatchFileRequest
