# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/events/fusion/lsp/lsp.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4dbtlabs/proto/private/v1/events/fusion/lsp/lsp.proto\x12\x14v1.events.fusion.lsp\"\xca\x01\n\nLspRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x10\n\x03uri\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04line\x18\x03 \x01(\rH\x01\x88\x01\x01\x12\x16\n\tcharacter\x18\x04 \x01(\rH\x02\x88\x01\x01\x12\x15\n\x08\x65nd_line\x18\x05 \x01(\rH\x03\x88\x01\x01\x12\x1a\n\rend_character\x18\x06 \x01(\rH\x04\x88\x01\x01\x42\x06\n\x04_uriB\x07\n\x05_lineB\x0c\n\n_characterB\x0b\n\t_end_lineB\x10\n\x0e_end_character\"N\n\x11LspCommandRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x10\n\x03uri\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x06\n\x04_uri\"3\n\x13LspBatchFileRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0c\n\x04uris\x18\x02 \x03(\tB7Z5github.com/dbt-labs/proto-golang/v1/events/fusion/lspb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.events.fusion.lsp.lsp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/dbt-labs/proto-golang/v1/events/fusion/lsp'
  _globals['_LSPREQUEST']._serialized_start=79
  _globals['_LSPREQUEST']._serialized_end=281
  _globals['_LSPCOMMANDREQUEST']._serialized_start=283
  _globals['_LSPCOMMANDREQUEST']._serialized_end=361
  _globals['_LSPBATCHFILEREQUEST']._serialized_start=363
  _globals['_LSPBATCHFILEREQUEST']._serialized_end=414
# @@protoc_insertion_point(module_scope)
