"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.fields.account_pb2
import dbtlabs.proto.private.v1.fields.connection_pb2
import dbtlabs.proto.private.v1.fields.credentials_pb2
import dbtlabs.proto.private.v1.fields.environment_pb2
import dbtlabs.proto.private.v1.fields.project_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CostInsights(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENVIRONMENT_FIELD_NUMBER: builtins.int
    CONNECTION_FIELD_NUMBER: builtins.int
    CREDENTIALS_FIELD_NUMBER: builtins.int
    PROJECT_FIELD_NUMBER: builtins.int
    ACCOUNT_FIELD_NUMBER: builtins.int
    DATE_FIELD_NUMBER: builtins.int
    date: builtins.str
    """The date to calculate costs for
    Format should be YYYY-MM-DD
    """
    @property
    def environment(self) -> dbtlabs.proto.private.v1.fields.environment_pb2.Environment:
        """The environment to calculate costs for"""

    @property
    def connection(self) -> dbtlabs.proto.private.v1.fields.connection_pb2.Connection:
        """The connection associated with the environment"""

    @property
    def credentials(self) -> dbtlabs.proto.private.v1.fields.credentials_pb2.Credentials:
        """The platform metadata credentials associated with the connection"""

    @property
    def project(self) -> dbtlabs.proto.private.v1.fields.project_pb2.Project:
        """The project that the environment belongs to"""

    @property
    def account(self) -> dbtlabs.proto.private.v1.fields.account_pb2.Account:
        """The account that the environment belongs to"""

    def __init__(
        self,
        *,
        environment: dbtlabs.proto.private.v1.fields.environment_pb2.Environment | None = ...,
        connection: dbtlabs.proto.private.v1.fields.connection_pb2.Connection | None = ...,
        credentials: dbtlabs.proto.private.v1.fields.credentials_pb2.Credentials | None = ...,
        project: dbtlabs.proto.private.v1.fields.project_pb2.Project | None = ...,
        account: dbtlabs.proto.private.v1.fields.account_pb2.Account | None = ...,
        date: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account", b"account", "connection", b"connection", "credentials", b"credentials", "environment", b"environment", "project", b"project"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account", b"account", "connection", b"connection", "credentials", b"credentials", "date", b"date", "environment", b"environment", "project", b"project"]) -> None: ...

global___CostInsights = CostInsights
