# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/records/custom_environment_variable.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.fields import custom_environment_variable_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_custom__environment__variable__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBdbtlabs/proto/private/v1/records/custom_environment_variable.proto\x12\nv1.records\x1a\x41\x64\x62tlabs/proto/private/v1/fields/custom_environment_variable.proto\"Q\n\x19\x43ustomEnvironmentVariable\x12\x34\n\x06\x66ields\x18\x01 \x01(\x0b\x32$.v1.fields.CustomEnvironmentVariableB-Z+github.com/dbt-labs/proto-golang/v1/recordsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.records.custom_environment_variable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/dbt-labs/proto-golang/v1/records'
  _globals['_CUSTOMENVIRONMENTVARIABLE']._serialized_start=149
  _globals['_CUSTOMENVIRONMENTVARIABLE']._serialized_end=230
# @@protoc_insertion_point(module_scope)
