"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.fields.account_pb2
import dbtlabs.proto.private.v1.fields.http_request_pb2
import dbtlabs.proto.private.v1.fields.user_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DbtCloudApiRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _AuthType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AuthTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DbtCloudApiRequest._AuthType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: DbtCloudApiRequest._AuthType.ValueType  # 0
        SESSION: DbtCloudApiRequest._AuthType.ValueType  # 1
        TOKEN: DbtCloudApiRequest._AuthType.ValueType  # 2
        """to be deprecated in favor of one below"""
        USER_API_TOKEN: DbtCloudApiRequest._AuthType.ValueType  # 3
        """user scoped api token (soon to be deprecated for ACCOUNT_SCOPED_USER_TOKEN)"""
        ACCOUNT_SCOPED_USER_TOKEN: DbtCloudApiRequest._AuthType.ValueType  # 4
        SERVICE_TOKEN: DbtCloudApiRequest._AuthType.ValueType  # 5

    class AuthType(_AuthType, metaclass=_AuthTypeEnumTypeWrapper): ...
    UNKNOWN: DbtCloudApiRequest.AuthType.ValueType  # 0
    SESSION: DbtCloudApiRequest.AuthType.ValueType  # 1
    TOKEN: DbtCloudApiRequest.AuthType.ValueType  # 2
    """to be deprecated in favor of one below"""
    USER_API_TOKEN: DbtCloudApiRequest.AuthType.ValueType  # 3
    """user scoped api token (soon to be deprecated for ACCOUNT_SCOPED_USER_TOKEN)"""
    ACCOUNT_SCOPED_USER_TOKEN: DbtCloudApiRequest.AuthType.ValueType  # 4
    SERVICE_TOKEN: DbtCloudApiRequest.AuthType.ValueType  # 5

    class _PartnerAppPlatform:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PartnerAppPlatformEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DbtCloudApiRequest._PartnerAppPlatform.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SNOWFLAKE: DbtCloudApiRequest._PartnerAppPlatform.ValueType  # 0

    class PartnerAppPlatform(_PartnerAppPlatform, metaclass=_PartnerAppPlatformEnumTypeWrapper): ...
    SNOWFLAKE: DbtCloudApiRequest.PartnerAppPlatform.ValueType  # 0

    class _DbtCloudApiVersion:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DbtCloudApiVersionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DbtCloudApiRequest._DbtCloudApiVersion.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNSPECIFIED: DbtCloudApiRequest._DbtCloudApiVersion.ValueType  # 0
        V1: DbtCloudApiRequest._DbtCloudApiVersion.ValueType  # 1
        V2: DbtCloudApiRequest._DbtCloudApiVersion.ValueType  # 2
        V3: DbtCloudApiRequest._DbtCloudApiVersion.ValueType  # 3

    class DbtCloudApiVersion(_DbtCloudApiVersion, metaclass=_DbtCloudApiVersionEnumTypeWrapper): ...
    UNSPECIFIED: DbtCloudApiRequest.DbtCloudApiVersion.ValueType  # 0
    V1: DbtCloudApiRequest.DbtCloudApiVersion.ValueType  # 1
    V2: DbtCloudApiRequest.DbtCloudApiVersion.ValueType  # 2
    V3: DbtCloudApiRequest.DbtCloudApiVersion.ValueType  # 3

    @typing.final
    class SnowflakeMetadata(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SNOWFLAKE_USER_ID_FIELD_NUMBER: builtins.int
        SNOWFLAKE_ACCOUNT_NAME_FIELD_NUMBER: builtins.int
        snowflake_user_id: builtins.str
        snowflake_account_name: builtins.str
        def __init__(
            self,
            *,
            snowflake_user_id: builtins.str = ...,
            snowflake_account_name: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["snowflake_account_name", b"snowflake_account_name", "snowflake_user_id", b"snowflake_user_id"]) -> None: ...

    @typing.final
    class PartnerAppMetadata(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PARTNER_APP_PLATFORM_FIELD_NUMBER: builtins.int
        SNOWFLAKE_FIELD_NUMBER: builtins.int
        partner_app_platform: global___DbtCloudApiRequest.PartnerAppPlatform.ValueType
        @property
        def snowflake(self) -> global___DbtCloudApiRequest.SnowflakeMetadata: ...
        def __init__(
            self,
            *,
            partner_app_platform: global___DbtCloudApiRequest.PartnerAppPlatform.ValueType = ...,
            snowflake: global___DbtCloudApiRequest.SnowflakeMetadata | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["platform_metadata", b"platform_metadata", "snowflake", b"snowflake"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["partner_app_platform", b"partner_app_platform", "platform_metadata", b"platform_metadata", "snowflake", b"snowflake"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["platform_metadata", b"platform_metadata"]) -> typing.Literal["snowflake"] | None: ...

    HTTP_REQUEST_FIELD_NUMBER: builtins.int
    AUTH_TYPE_FIELD_NUMBER: builtins.int
    DBT_CLOUD_API_VERSION_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    ACCOUNT_FIELD_NUMBER: builtins.int
    PARTNER_APP_METADATA_FIELD_NUMBER: builtins.int
    auth_type: global___DbtCloudApiRequest.AuthType.ValueType
    dbt_cloud_api_version: global___DbtCloudApiRequest.DbtCloudApiVersion.ValueType
    @property
    def http_request(self) -> dbtlabs.proto.private.v1.fields.http_request_pb2.HttpRequest: ...
    @property
    def user(self) -> dbtlabs.proto.private.v1.fields.user_pb2.User: ...
    @property
    def account(self) -> dbtlabs.proto.private.v1.fields.account_pb2.Account: ...
    @property
    def partner_app_metadata(self) -> global___DbtCloudApiRequest.PartnerAppMetadata: ...
    def __init__(
        self,
        *,
        http_request: dbtlabs.proto.private.v1.fields.http_request_pb2.HttpRequest | None = ...,
        auth_type: global___DbtCloudApiRequest.AuthType.ValueType = ...,
        dbt_cloud_api_version: global___DbtCloudApiRequest.DbtCloudApiVersion.ValueType = ...,
        user: dbtlabs.proto.private.v1.fields.user_pb2.User | None = ...,
        account: dbtlabs.proto.private.v1.fields.account_pb2.Account | None = ...,
        partner_app_metadata: global___DbtCloudApiRequest.PartnerAppMetadata | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_partner_app_metadata", b"_partner_app_metadata", "account", b"account", "http_request", b"http_request", "partner_app_metadata", b"partner_app_metadata", "user", b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_partner_app_metadata", b"_partner_app_metadata", "account", b"account", "auth_type", b"auth_type", "dbt_cloud_api_version", b"dbt_cloud_api_version", "http_request", b"http_request", "partner_app_metadata", b"partner_app_metadata", "user", b"user"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_partner_app_metadata", b"_partner_app_metadata"]) -> typing.Literal["partner_app_metadata"] | None: ...

global___DbtCloudApiRequest = DbtCloudApiRequest
