"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.fields.account_pb2
import dbtlabs.proto.private.v1.fields.environment_pb2
import dbtlabs.proto.private.v1.fields.integration_pb2
import dbtlabs.proto.private.v1.fields.project_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GeneratedExposure(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    ENVIRONMENT_FIELD_NUMBER: builtins.int
    PROJECT_FIELD_NUMBER: builtins.int
    INTEGRATION_FIELD_NUMBER: builtins.int
    @property
    def account(self) -> dbtlabs.proto.private.v1.fields.account_pb2.Account: ...
    @property
    def environment(self) -> dbtlabs.proto.private.v1.fields.environment_pb2.Environment: ...
    @property
    def project(self) -> dbtlabs.proto.private.v1.fields.project_pb2.Project: ...
    @property
    def integration(self) -> dbtlabs.proto.private.v1.fields.integration_pb2.Integration: ...
    def __init__(
        self,
        *,
        account: dbtlabs.proto.private.v1.fields.account_pb2.Account | None = ...,
        environment: dbtlabs.proto.private.v1.fields.environment_pb2.Environment | None = ...,
        project: dbtlabs.proto.private.v1.fields.project_pb2.Project | None = ...,
        integration: dbtlabs.proto.private.v1.fields.integration_pb2.Integration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account", b"account", "environment", b"environment", "integration", b"integration", "project", b"project"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account", b"account", "environment", b"environment", "integration", b"integration", "project", b"project"]) -> None: ...

global___GeneratedExposure = GeneratedExposure
