"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.fields.account_pb2
import dbtlabs.proto.private.v1.fields.environment_pb2
import dbtlabs.proto.private.v1.fields.extended_attributes_pb2
import dbtlabs.proto.private.v1.fields.project_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ExtendedAttributes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIELDS_FIELD_NUMBER: builtins.int
    ACCOUNT_FIELD_NUMBER: builtins.int
    PROJECT_FIELD_NUMBER: builtins.int
    ENVIRONMENT_FIELD_NUMBER: builtins.int
    @property
    def fields(self) -> dbtlabs.proto.private.v1.fields.extended_attributes_pb2.ExtendedAttributes: ...
    @property
    def account(self) -> dbtlabs.proto.private.v1.fields.account_pb2.Account: ...
    @property
    def project(self) -> dbtlabs.proto.private.v1.fields.project_pb2.Project: ...
    @property
    def environment(self) -> dbtlabs.proto.private.v1.fields.environment_pb2.Environment: ...
    def __init__(
        self,
        *,
        fields: dbtlabs.proto.private.v1.fields.extended_attributes_pb2.ExtendedAttributes | None = ...,
        account: dbtlabs.proto.private.v1.fields.account_pb2.Account | None = ...,
        project: dbtlabs.proto.private.v1.fields.project_pb2.Project | None = ...,
        environment: dbtlabs.proto.private.v1.fields.environment_pb2.Environment | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account", b"account", "environment", b"environment", "fields", b"fields", "project", b"project"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account", b"account", "environment", b"environment", "fields", b"fields", "project", b"project"]) -> None: ...

global___ExtendedAttributes = ExtendedAttributes
