"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.fields.github_installation_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GithubInstallation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIELDS_FIELD_NUMBER: builtins.int
    @property
    def fields(self) -> dbtlabs.proto.private.v1.fields.github_installation_pb2.GithubInstallation: ...
    def __init__(
        self,
        *,
        fields: dbtlabs.proto.private.v1.fields.github_installation_pb2.GithubInstallation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fields", b"fields"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fields", b"fields"]) -> None: ...

global___GithubInstallation = GithubInstallation
