"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.fields.account_pb2
import dbtlabs.proto.private.v1.fields.environment_pb2
import dbtlabs.proto.private.v1.fields.invocation_pb2
import dbtlabs.proto.private.v1.fields.project_pb2
import dbtlabs.proto.private.v1.fields.user_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Invocation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_FIELD_NUMBER: builtins.int
    ENVIRONMENT_FIELD_NUMBER: builtins.int
    PROJECT_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    @property
    def account(self) -> dbtlabs.proto.private.v1.fields.account_pb2.Account: ...
    @property
    def environment(self) -> dbtlabs.proto.private.v1.fields.environment_pb2.Environment: ...
    @property
    def project(self) -> dbtlabs.proto.private.v1.fields.project_pb2.Project: ...
    @property
    def user(self) -> dbtlabs.proto.private.v1.fields.user_pb2.User: ...
    @property
    def fields(self) -> dbtlabs.proto.private.v1.fields.invocation_pb2.Invocation: ...
    def __init__(
        self,
        *,
        account: dbtlabs.proto.private.v1.fields.account_pb2.Account | None = ...,
        environment: dbtlabs.proto.private.v1.fields.environment_pb2.Environment | None = ...,
        project: dbtlabs.proto.private.v1.fields.project_pb2.Project | None = ...,
        user: dbtlabs.proto.private.v1.fields.user_pb2.User | None = ...,
        fields: dbtlabs.proto.private.v1.fields.invocation_pb2.Invocation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account", b"account", "environment", b"environment", "fields", b"fields", "project", b"project", "user", b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account", b"account", "environment", b"environment", "fields", b"fields", "project", b"project", "user", b"user"]) -> None: ...

global___Invocation = Invocation
