# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/records/job_definition.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.fields import job_definition_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_job__definition__pb2
from dbtlabs.proto.private.v1.fields import account_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_account__pb2
from dbtlabs.proto.private.v1.fields import environment_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_environment__pb2
from dbtlabs.proto.private.v1.fields import project_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_project__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5dbtlabs/proto/private/v1/records/job_definition.proto\x12\nv1.records\x1a\x34\x64\x62tlabs/proto/private/v1/fields/job_definition.proto\x1a-dbtlabs/proto/private/v1/fields/account.proto\x1a\x31\x64\x62tlabs/proto/private/v1/fields/environment.proto\x1a-dbtlabs/proto/private/v1/fields/project.proto\"\xb0\x01\n\rJobDefinition\x12(\n\x06\x66ields\x18\x01 \x01(\x0b\x32\x18.v1.fields.JobDefinition\x12#\n\x07\x61\x63\x63ount\x18\x02 \x01(\x0b\x32\x12.v1.fields.Account\x12+\n\x0b\x65nvironment\x18\x03 \x01(\x0b\x32\x16.v1.fields.Environment\x12#\n\x07project\x18\x04 \x01(\x0b\x32\x12.v1.fields.ProjectB-Z+github.com/dbt-labs/proto-golang/v1/recordsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.records.job_definition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/dbt-labs/proto-golang/v1/records'
  _globals['_JOBDEFINITION']._serialized_start=269
  _globals['_JOBDEFINITION']._serialized_end=445
# @@protoc_insertion_point(module_scope)
