# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/records/mantle_query.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.public.v1.common import vortex_options_pb2 as dbtlabs_dot_proto_dot_public_dot_v1_dot_common_dot_vortex__options__pb2
from dbtlabs.proto.private.v1.fields import mantle_query_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_mantle__query__pb2
from dbtlabs.proto.public.v1.fields import adapter_types_pb2 as dbtlabs_dot_proto_dot_public_dot_v1_dot_fields_dot_adapter__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3dbtlabs/proto/private/v1/records/mantle_query.proto\x12\nv1.records\x1a\x33\x64\x62tlabs/proto/public/v1/common/vortex_options.proto\x1a\x32\x64\x62tlabs/proto/private/v1/fields/mantle_query.proto\x1a\x32\x64\x62tlabs/proto/public/v1/fields/adapter_types.proto\"5\n\x0bMantleQuery\x12&\n\x06\x66ields\x18\x01 \x01(\x0b\x32\x16.v1.fields.MantleQuery\"\xac\x01\n\x19\x45nrichedSQLQueryStatusMsg\x12\x38\n\x12invocation_context\x18\x01 \x01(\x0b\x32\x1c.v1.fields.InvocationContext\x12K\n\x10sql_query_status\x18\x02 \x01(\x0b\x32\x31.v1.public.fields.adapter_types.SQLQueryStatusMsg:\x08\xd8\xa6\x1d\x05\x80\xa7\x1d\x01\x42-Z+github.com/dbt-labs/proto-golang/v1/recordsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.records.mantle_query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/dbt-labs/proto-golang/v1/records'
  _globals['_ENRICHEDSQLQUERYSTATUSMSG']._loaded_options = None
  _globals['_ENRICHEDSQLQUERYSTATUSMSG']._serialized_options = b'\330\246\035\005\200\247\035\001'
  _globals['_MANTLEQUERY']._serialized_start=224
  _globals['_MANTLEQUERY']._serialized_end=277
  _globals['_ENRICHEDSQLQUERYSTATUSMSG']._serialized_start=280
  _globals['_ENRICHEDSQLQUERYSTATUSMSG']._serialized_end=452
# @@protoc_insertion_point(module_scope)
