# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/records/model_query_history.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.fields import account_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_account__pb2
from dbtlabs.proto.private.v1.fields import environment_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_environment__pb2
from dbtlabs.proto.private.v1.fields import project_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_project__pb2
from dbtlabs.proto.private.v1.fields import model_query_history_connection_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_model__query__history__connection__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:dbtlabs/proto/private/v1/records/model_query_history.proto\x12\nv1.records\x1a-dbtlabs/proto/private/v1/fields/account.proto\x1a\x31\x64\x62tlabs/proto/private/v1/fields/environment.proto\x1a-dbtlabs/proto/private/v1/fields/project.proto\x1a\x44\x64\x62tlabs/proto/private/v1/fields/model_query_history_connection.proto\"\xda\x01\n\x11ModelQueryHistory\x12#\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x12.v1.fields.Account\x12+\n\x0b\x65nvironment\x18\x02 \x01(\x0b\x32\x16.v1.fields.Environment\x12#\n\x07project\x18\x03 \x01(\x0b\x32\x12.v1.fields.Project\x12N\n\x1emodel_query_history_connection\x18\x04 \x01(\x0b\x32&.v1.fields.ModelQueryHistoryConnectionB-Z+github.com/dbt-labs/proto-golang/v1/recordsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.records.model_query_history_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/dbt-labs/proto-golang/v1/records'
  _globals['_MODELQUERYHISTORY']._serialized_start=290
  _globals['_MODELQUERYHISTORY']._serialized_end=508
# @@protoc_insertion_point(module_scope)
