# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/records/permission.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.fields import permission_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_permission__pb2
from dbtlabs.proto.private.v1.fields import user_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1dbtlabs/proto/private/v1/records/permission.proto\x12\nv1.records\x1a\x30\x64\x62tlabs/proto/private/v1/fields/permission.proto\x1a*dbtlabs/proto/private/v1/fields/user.proto\"R\n\nPermission\x12%\n\x06\x66ields\x18\x01 \x01(\x0b\x32\x15.v1.fields.Permission\x12\x1d\n\x04user\x18\x02 \x01(\x0b\x32\x0f.v1.fields.UserB-Z+github.com/dbt-labs/proto-golang/v1/recordsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.records.permission_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/dbt-labs/proto-golang/v1/records'
  _globals['_PERMISSION']._serialized_start=159
  _globals['_PERMISSION']._serialized_end=241
# @@protoc_insertion_point(module_scope)
