"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.fields.account_pb2
import dbtlabs.proto.private.v1.fields.git_provider_pb2
import dbtlabs.proto.private.v1.fields.keypair_pb2
import dbtlabs.proto.private.v1.fields.project_pb2
import dbtlabs.proto.private.v1.fields.repository_credentials_pb2
import dbtlabs.proto.private.v1.fields.repository_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Repository(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIELDS_FIELD_NUMBER: builtins.int
    ACCOUNT_FIELD_NUMBER: builtins.int
    REPOSITORY_CREDENTIALS_FIELD_NUMBER: builtins.int
    GIT_PROVIDER_FIELD_NUMBER: builtins.int
    PROJECT_FIELD_NUMBER: builtins.int
    DEPLOY_KEY_FIELD_NUMBER: builtins.int
    @property
    def fields(self) -> dbtlabs.proto.private.v1.fields.repository_pb2.Repository: ...
    @property
    def account(self) -> dbtlabs.proto.private.v1.fields.account_pb2.Account: ...
    @property
    def repository_credentials(self) -> dbtlabs.proto.private.v1.fields.repository_credentials_pb2.RepositoryCredentials: ...
    @property
    def git_provider(self) -> dbtlabs.proto.private.v1.fields.git_provider_pb2.GitProvider: ...
    @property
    def project(self) -> dbtlabs.proto.private.v1.fields.project_pb2.Project: ...
    @property
    def deploy_key(self) -> dbtlabs.proto.private.v1.fields.keypair_pb2.Keypair: ...
    def __init__(
        self,
        *,
        fields: dbtlabs.proto.private.v1.fields.repository_pb2.Repository | None = ...,
        account: dbtlabs.proto.private.v1.fields.account_pb2.Account | None = ...,
        repository_credentials: dbtlabs.proto.private.v1.fields.repository_credentials_pb2.RepositoryCredentials | None = ...,
        git_provider: dbtlabs.proto.private.v1.fields.git_provider_pb2.GitProvider | None = ...,
        project: dbtlabs.proto.private.v1.fields.project_pb2.Project | None = ...,
        deploy_key: dbtlabs.proto.private.v1.fields.keypair_pb2.Keypair | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account", b"account", "deploy_key", b"deploy_key", "fields", b"fields", "git_provider", b"git_provider", "project", b"project", "repository_credentials", b"repository_credentials"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account", b"account", "deploy_key", b"deploy_key", "fields", b"fields", "git_provider", b"git_provider", "project", b"project", "repository_credentials", b"repository_credentials"]) -> None: ...

global___Repository = Repository
