# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/records/semantic_layer_credentials.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.fields import account_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_account__pb2
from dbtlabs.proto.private.v1.fields import semantic_layer_credentials_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_semantic__layer__credentials__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAdbtlabs/proto/private/v1/records/semantic_layer_credentials.proto\x12\nv1.records\x1a-dbtlabs/proto/private/v1/fields/account.proto\x1a@dbtlabs/proto/private/v1/fields/semantic_layer_credentials.proto\"t\n\x18SemanticLayerCredentials\x12\x33\n\x06\x66ields\x18\x01 \x01(\x0b\x32#.v1.fields.SemanticLayerCredentials\x12#\n\x07\x61\x63\x63ount\x18\x02 \x01(\x0b\x32\x12.v1.fields.AccountB-Z+github.com/dbt-labs/proto-golang/v1/recordsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.records.semantic_layer_credentials_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/dbt-labs/proto-golang/v1/records'
  _globals['_SEMANTICLAYERCREDENTIALS']._serialized_start=194
  _globals['_SEMANTICLAYERCREDENTIALS']._serialized_end=310
# @@protoc_insertion_point(module_scope)
