"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import dbtlabs.proto.private.v1.fields.account_pb2
import dbtlabs.proto.private.v1.fields.service_token_pb2
import dbtlabs.proto.private.v1.fields.user_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ServiceToken(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIELDS_FIELD_NUMBER: builtins.int
    ACCOUNT_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    @property
    def fields(self) -> dbtlabs.proto.private.v1.fields.service_token_pb2.ServiceToken: ...
    @property
    def account(self) -> dbtlabs.proto.private.v1.fields.account_pb2.Account: ...
    @property
    def user(self) -> dbtlabs.proto.private.v1.fields.user_pb2.User: ...
    def __init__(
        self,
        *,
        fields: dbtlabs.proto.private.v1.fields.service_token_pb2.ServiceToken | None = ...,
        account: dbtlabs.proto.private.v1.fields.account_pb2.Account | None = ...,
        user: dbtlabs.proto.private.v1.fields.user_pb2.User | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["account", b"account", "fields", b"fields", "user", b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account", b"account", "fields", b"fields", "user", b"user"]) -> None: ...

global___ServiceToken = ServiceToken
