# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/records/warehouse_extraction.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.fields import warehouse_extraction_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_warehouse__extraction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;dbtlabs/proto/private/v1/records/warehouse_extraction.proto\x12\nv1.records\x1a:dbtlabs/proto/private/v1/fields/warehouse_extraction.proto\"E\n\x13WarehouseExtraction\x12.\n\x06\x66ields\x18\x01 \x01(\x0b\x32\x1e.v1.fields.WarehouseExtractionB-Z+github.com/dbt-labs/proto-golang/v1/recordsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.records.warehouse_extraction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/dbt-labs/proto-golang/v1/records'
  _globals['_WAREHOUSEEXTRACTION']._serialized_start=135
  _globals['_WAREHOUSEEXTRACTION']._serialized_end=204
# @@protoc_insertion_point(module_scope)
