# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/records/webhooks_subscription.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dbtlabs.proto.private.v1.fields import account_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_account__pb2
from dbtlabs.proto.private.v1.fields import webhooks_subscription_pb2 as dbtlabs_dot_proto_dot_private_dot_v1_dot_fields_dot_webhooks__subscription__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<dbtlabs/proto/private/v1/records/webhooks_subscription.proto\x12\nv1.records\x1a-dbtlabs/proto/private/v1/fields/account.proto\x1a;dbtlabs/proto/private/v1/fields/webhooks_subscription.proto\"r\n\x14WebhooksSubscription\x12#\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x12.v1.fields.Account\x12\x35\n\x0csubscription\x18\x02 \x01(\x0b\x32\x1f.v1.fields.WebhooksSubscriptionB-Z+github.com/dbt-labs/proto-golang/v1/recordsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.records.webhooks_subscription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/dbt-labs/proto-golang/v1/records'
  _globals['_WEBHOOKSSUBSCRIPTION']._serialized_start=184
  _globals['_WEBHOOKSSUBSCRIPTION']._serialized_end=298
# @@protoc_insertion_point(module_scope)
