"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RepoServiceCacheType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RepoServiceCacheTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RepoServiceCacheType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    REPO_SERVICE_CACHE_TYPE_UNKNOWN: _RepoServiceCacheType.ValueType  # 0
    RUN: _RepoServiceCacheType.ValueType  # 1
    """Orchestration team for production run."""
    SUCCESSFUL_RUN: _RepoServiceCacheType.ValueType  # 2
    VISUAL_EDITOR: _RepoServiceCacheType.ValueType  # 3
    """Cloud client team for visual editor dev run."""
    CLOUD_CLI: _RepoServiceCacheType.ValueType  # 4
    """Cloud client team for cloud CLI dev run."""
    GIT_UNIVERSAL: _RepoServiceCacheType.ValueType  # 5
    """GIT_UNIVERSAL is a special type whose identifier is the git commit sha. Since
    the git commit sha is unique across all repositories, it functions as a unique
    identifier for a git repo cache.
    """

class RepoServiceCacheType(_RepoServiceCacheType, metaclass=_RepoServiceCacheTypeEnumTypeWrapper):
    """RepoServiceCacheType is reserved from different teams. If you want to use repo 
    service, add your team in this enum value and contact orchestration team in slack
    channel #ask-dev-orchestration.
    """

REPO_SERVICE_CACHE_TYPE_UNKNOWN: RepoServiceCacheType.ValueType  # 0
RUN: RepoServiceCacheType.ValueType  # 1
"""Orchestration team for production run."""
SUCCESSFUL_RUN: RepoServiceCacheType.ValueType  # 2
VISUAL_EDITOR: RepoServiceCacheType.ValueType  # 3
"""Cloud client team for visual editor dev run."""
CLOUD_CLI: RepoServiceCacheType.ValueType  # 4
"""Cloud client team for cloud CLI dev run."""
GIT_UNIVERSAL: RepoServiceCacheType.ValueType  # 5
"""GIT_UNIVERSAL is a special type whose identifier is the git commit sha. Since
the git commit sha is unique across all repositories, it functions as a unique
identifier for a git repo cache.
"""
global___RepoServiceCacheType = RepoServiceCacheType

class _OperationStatusType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OperationStatusTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OperationStatusType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _OperationStatusType.ValueType  # 0
    CLONING: _OperationStatusType.ValueType  # 1
    """CLONING means the repo is being cloned."""
    DEPS: _OperationStatusType.ValueType  # 2
    """DEPS means the repo is downloading dependencies."""
    SUCCESS: _OperationStatusType.ValueType  # 3
    """SUCCESS means the repo was successfully cloned."""
    ERROR: _OperationStatusType.ValueType  # 4
    """ERROR means the repo cache process failed at some point."""
    CANCELLED: _OperationStatusType.ValueType  # 5
    """CANCELLED means the repo cache process was cancelled."""
    EXPIRED: _OperationStatusType.ValueType  # 6
    """EXPIRED means the repo cache process was expired."""

class OperationStatusType(_OperationStatusType, metaclass=_OperationStatusTypeEnumTypeWrapper):
    """OperationStatusType are the various internal states the repo cache 
    might be in
    """

UNKNOWN: OperationStatusType.ValueType  # 0
CLONING: OperationStatusType.ValueType  # 1
"""CLONING means the repo is being cloned."""
DEPS: OperationStatusType.ValueType  # 2
"""DEPS means the repo is downloading dependencies."""
SUCCESS: OperationStatusType.ValueType  # 3
"""SUCCESS means the repo was successfully cloned."""
ERROR: OperationStatusType.ValueType  # 4
"""ERROR means the repo cache process failed at some point."""
CANCELLED: OperationStatusType.ValueType  # 5
"""CANCELLED means the repo cache process was cancelled."""
EXPIRED: OperationStatusType.ValueType  # 6
"""EXPIRED means the repo cache process was expired."""
global___OperationStatusType = OperationStatusType

class _ResourceType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ResourceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResourceType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PROJECT_ARCHIVE: _ResourceType.ValueType  # 0
    """The project zip"""
    PROJECT_FILE: _ResourceType.ValueType  # 1
    """Any individual file"""

class ResourceType(_ResourceType, metaclass=_ResourceTypeEnumTypeWrapper):
    """ResourceType includes all the types of resource (archives/files) that the RepoCacheService will serve to clients"""

PROJECT_ARCHIVE: ResourceType.ValueType  # 0
"""The project zip"""
PROJECT_FILE: ResourceType.ValueType  # 1
"""Any individual file"""
global___ResourceType = ResourceType

@typing.final
class SourceCodeConfiguration(google.protobuf.message.Message):
    """SourceCodeConfiguration describes how repo-cache service perform git clone and the 
    follow up checkout to get the right source code snapshot.

    Clone configurations.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLE_SHALLOW_FIELD_NUMBER: builtins.int
    SKIP_LFS_FIELD_NUMBER: builtins.int
    BRANCH_FIELD_NUMBER: builtins.int
    SHA_FIELD_NUMBER: builtins.int
    enable_shallow: builtins.bool
    """Whether shallow mode should be enable when perform git clone. Notice if shallow is 
    enabled, you are only able to get the head of required branch and it's not 
    compatible with sha checkout.
    See more details in 
    https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/
    """
    skip_lfs: builtins.bool
    """Whether git LFS should be enabled to ignoring large files.
    See more details in https://github.com/git-lfs/git-lfs
    """
    branch: builtins.str
    """
    Checkout configurations.

    Git branch to be checked out, it would always be the head of that branch in origin.
    Notice you should only specify one of "branch" and "sha" as they are not 
    compatible. If they are both not specified, service will fallback to head of 
    default(most likely main or master) branch.
    """
    sha: builtins.str
    """Git commit sha to be checked out. The commit sha must be recorded in origin main(
    or master) branch.
    Notice you should only specify one of "branch" and "sha" as they are not 
    compatible. If they are both not specified, service will fallback to head of 
    default(most likely main or master) branch.
    TODO: Consider support getting branch using project environment from cloud config 
    call.
    TODO: Consider support getting last applied sha from cloud artifact call.
    """
    def __init__(
        self,
        *,
        enable_shallow: builtins.bool | None = ...,
        skip_lfs: builtins.bool | None = ...,
        branch: builtins.str | None = ...,
        sha: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_branch", b"_branch", "_enable_shallow", b"_enable_shallow", "_sha", b"_sha", "_skip_lfs", b"_skip_lfs", "branch", b"branch", "enable_shallow", b"enable_shallow", "sha", b"sha", "skip_lfs", b"skip_lfs"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_branch", b"_branch", "_enable_shallow", b"_enable_shallow", "_sha", b"_sha", "_skip_lfs", b"_skip_lfs", "branch", b"branch", "enable_shallow", b"enable_shallow", "sha", b"sha", "skip_lfs", b"skip_lfs"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_branch", b"_branch"]) -> typing.Literal["branch"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_enable_shallow", b"_enable_shallow"]) -> typing.Literal["enable_shallow"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_sha", b"_sha"]) -> typing.Literal["sha"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_skip_lfs", b"_skip_lfs"]) -> typing.Literal["skip_lfs"] | None: ...

global___SourceCodeConfiguration = SourceCodeConfiguration

@typing.final
class GitInfo(google.protobuf.message.Message):
    """GitInfo describes repo git status."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BRANCH_FIELD_NUMBER: builtins.int
    SHA_FIELD_NUMBER: builtins.int
    REMOTE_URL_FIELD_NUMBER: builtins.int
    REPO_NAME_FIELD_NUMBER: builtins.int
    branch: builtins.str
    """Git branch that repo is working on."""
    sha: builtins.str
    """Git commit sha that repo is working on."""
    remote_url: builtins.str
    """Git remote url the repo is cloned from."""
    repo_name: builtins.str
    """Git repo name."""
    def __init__(
        self,
        *,
        branch: builtins.str = ...,
        sha: builtins.str = ...,
        remote_url: builtins.str = ...,
        repo_name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_repo_name", b"_repo_name", "repo_name", b"repo_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_repo_name", b"_repo_name", "branch", b"branch", "remote_url", b"remote_url", "repo_name", b"repo_name", "sha", b"sha"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_repo_name", b"_repo_name"]) -> typing.Literal["repo_name"] | None: ...

global___GitInfo = GitInfo

@typing.final
class GitConfiguration(google.protobuf.message.Message):
    """GitConfiguration stores everything that needs to access git and deps."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_ID_FIELD_NUMBER: builtins.int
    project_id: builtins.int
    """Project id to fetch git source code credentials from."""
    def __init__(
        self,
        *,
        project_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_project_id", b"_project_id", "project_id", b"project_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_project_id", b"_project_id", "project_id", b"project_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_project_id", b"_project_id"]) -> typing.Literal["project_id"] | None: ...

global___GitConfiguration = GitConfiguration

@typing.final
class CacheInfo(google.protobuf.message.Message):
    """CacheInfo describes the an unique cache unit that maps to a repo."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    IDENTIFIER_FIELD_NUMBER: builtins.int
    type: global___RepoServiceCacheType.ValueType
    """Type of cache."""
    identifier: builtins.str
    """An unique identifier of cached repo, e.g., run ID."""
    def __init__(
        self,
        *,
        type: global___RepoServiceCacheType.ValueType = ...,
        identifier: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["identifier", b"identifier", "type", b"type"]) -> None: ...

global___CacheInfo = CacheInfo

@typing.final
class OperationStatus(google.protobuf.message.Message):
    """OperationStatus stores any git operation status with info message."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    status: global___OperationStatusType.ValueType
    message: builtins.str
    """Info message."""
    created_at: builtins.int
    """created_at is the timestamp of when the operation status was created."""
    updated_at: builtins.int
    """updated_at is the timestamp of when the operation status was updated."""
    def __init__(
        self,
        *,
        status: global___OperationStatusType.ValueType = ...,
        message: builtins.str = ...,
        created_at: builtins.int = ...,
        updated_at: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "message", b"message", "status", b"status", "updated_at", b"updated_at"]) -> None: ...

global___OperationStatus = OperationStatus

@typing.final
class RepoStatus(google.protobuf.message.Message):
    """RepoStatus provides all status details for the repo."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CACHE_STATUS_FIELD_NUMBER: builtins.int
    SOURCE_CODE_GIT_INFO_FIELD_NUMBER: builtins.int
    @property
    def cache_status(self) -> global___OperationStatus: ...
    @property
    def source_code_git_info(self) -> global___GitInfo:
        """Source code git info."""

    def __init__(
        self,
        *,
        cache_status: global___OperationStatus | None = ...,
        source_code_git_info: global___GitInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_cache_status", b"_cache_status", "_source_code_git_info", b"_source_code_git_info", "cache_status", b"cache_status", "source_code_git_info", b"source_code_git_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_cache_status", b"_cache_status", "_source_code_git_info", b"_source_code_git_info", "cache_status", b"cache_status", "source_code_git_info", b"source_code_git_info"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_cache_status", b"_cache_status"]) -> typing.Literal["cache_status"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_source_code_git_info", b"_source_code_git_info"]) -> typing.Literal["source_code_git_info"] | None: ...

global___RepoStatus = RepoStatus

@typing.final
class RepoPath(google.protobuf.message.Message):
    """RepoPath provides the location and other details of the repo."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    EXPIRED_AT_FIELD_NUMBER: builtins.int
    bucket: builtins.str
    """s3 bucket or azure container."""
    path: builtins.str
    created_at: builtins.int
    """Timestamp seconds of when the repo object is created."""
    expired_at: builtins.int
    """Timestamp seconds of when the repo object is expired."""
    def __init__(
        self,
        *,
        bucket: builtins.str = ...,
        path: builtins.str = ...,
        created_at: builtins.int = ...,
        expired_at: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket", b"bucket", "created_at", b"created_at", "expired_at", b"expired_at", "path", b"path"]) -> None: ...

global___RepoPath = RepoPath

@typing.final
class RepoInfo(google.protobuf.message.Message):
    """RepoInfo provides the location and other details of the repo."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    EXPIRED_AT_FIELD_NUMBER: builtins.int
    bucket: builtins.str
    """Blob storage resource."""
    created_at: builtins.int
    """Timestamp seconds of when the resource is created."""
    expired_at: builtins.int
    """Timestamp seconds of when the resource is expired."""
    def __init__(
        self,
        *,
        bucket: builtins.str = ...,
        created_at: builtins.int = ...,
        expired_at: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket", b"bucket", "created_at", b"created_at", "expired_at", b"expired_at"]) -> None: ...

global___RepoInfo = RepoInfo

@typing.final
class CreateRequest(google.protobuf.message.Message):
    """////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GIT_CONFIG_FIELD_NUMBER: builtins.int
    SOURCE_CODE_CONFIG_FIELD_NUMBER: builtins.int
    DOWNLOAD_DEPS_FIELD_NUMBER: builtins.int
    CACHE_INFO_FIELD_NUMBER: builtins.int
    CACHE_TTL_SECONDS_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    download_deps: builtins.bool
    """If true deps packages would be downloaded as well."""
    cache_ttl_seconds: builtins.int
    """How long does cache unit is expired after repo is materialized in object store."""
    account_id: builtins.int
    """Account ID for account-level validation.
    Optional for backwards compatibility. Will be required in a future release.
    """
    @property
    def git_config(self) -> global___GitConfiguration: ...
    @property
    def source_code_config(self) -> global___SourceCodeConfiguration: ...
    @property
    def cache_info(self) -> global___CacheInfo:
        """Cache info identifies a cache unit that maps to the repo."""

    def __init__(
        self,
        *,
        git_config: global___GitConfiguration | None = ...,
        source_code_config: global___SourceCodeConfiguration | None = ...,
        download_deps: builtins.bool | None = ...,
        cache_info: global___CacheInfo | None = ...,
        cache_ttl_seconds: builtins.int = ...,
        account_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_account_id", b"_account_id", "_download_deps", b"_download_deps", "account_id", b"account_id", "cache_info", b"cache_info", "download_deps", b"download_deps", "git_config", b"git_config", "source_code_config", b"source_code_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_account_id", b"_account_id", "_download_deps", b"_download_deps", "account_id", b"account_id", "cache_info", b"cache_info", "cache_ttl_seconds", b"cache_ttl_seconds", "download_deps", b"download_deps", "git_config", b"git_config", "source_code_config", b"source_code_config"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_account_id", b"_account_id"]) -> typing.Literal["account_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_download_deps", b"_download_deps"]) -> typing.Literal["download_deps"] | None: ...

global___CreateRequest = CreateRequest

@typing.final
class CreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPO_STATUS_FIELD_NUMBER: builtins.int
    @property
    def repo_status(self) -> global___RepoStatus: ...
    def __init__(
        self,
        *,
        repo_status: global___RepoStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["repo_status", b"repo_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["repo_status", b"repo_status"]) -> None: ...

global___CreateResponse = CreateResponse

@typing.final
class GetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CACHE_INFO_FIELD_NUMBER: builtins.int
    RESOURCE_INFO_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.int
    """Account ID for account-level validation.
    Optional for backwards compatibility. Will be required in a future release.
    """
    @property
    def cache_info(self) -> global___CacheInfo:
        """Cache info to identify a unique cache unit."""

    @property
    def resource_info(self) -> global___ResourceInfo:
        """Info on what resource to retrieve. If not specified, return project archive."""

    def __init__(
        self,
        *,
        cache_info: global___CacheInfo | None = ...,
        resource_info: global___ResourceInfo | None = ...,
        account_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_account_id", b"_account_id", "_resource_info", b"_resource_info", "account_id", b"account_id", "cache_info", b"cache_info", "resource_info", b"resource_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_account_id", b"_account_id", "_resource_info", b"_resource_info", "account_id", b"account_id", "cache_info", b"cache_info", "resource_info", b"resource_info"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_account_id", b"_account_id"]) -> typing.Literal["account_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_resource_info", b"_resource_info"]) -> typing.Literal["resource_info"] | None: ...

global___GetRequest = GetRequest

@typing.final
class GetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPO_PATH_FIELD_NUMBER: builtins.int
    REPO_STATUS_FIELD_NUMBER: builtins.int
    REPO_INFO_FIELD_NUMBER: builtins.int
    RESOURCE_PATH_FIELD_NUMBER: builtins.int
    resource_path: builtins.str
    """Blob path to the requested resource. If it's empty the cache has not been created, upload is incomplete,
    or it's missing from cache.
    """
    @property
    def repo_path(self) -> global___RepoPath:
        """The path to the new copied repo. If it's empty, the repo cache object is not
        available yet.
        """

    @property
    def repo_status(self) -> global___RepoStatus: ...
    @property
    def repo_info(self) -> global___RepoInfo:
        """Repo info, if it's empty, the cache has not been created or upload is incomplete."""

    def __init__(
        self,
        *,
        repo_path: global___RepoPath | None = ...,
        repo_status: global___RepoStatus | None = ...,
        repo_info: global___RepoInfo | None = ...,
        resource_path: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_repo_info", b"_repo_info", "_repo_path", b"_repo_path", "repo_info", b"repo_info", "repo_path", b"repo_path", "repo_status", b"repo_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_repo_info", b"_repo_info", "_repo_path", b"_repo_path", "repo_info", b"repo_info", "repo_path", b"repo_path", "repo_status", b"repo_status", "resource_path", b"resource_path"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_repo_info", b"_repo_info"]) -> typing.Literal["repo_info"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_repo_path", b"_repo_path"]) -> typing.Literal["repo_path"] | None: ...

global___GetResponse = GetResponse

@typing.final
class PersistRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FROM_CACHE_INFO_FIELD_NUMBER: builtins.int
    TO_CACHE_INFO_FIELD_NUMBER: builtins.int
    CACHE_TTL_SECONDS_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    cache_ttl_seconds: builtins.int
    """How long does cache unit is expired after repo is materialized in object store."""
    account_id: builtins.int
    """Account ID for account-level validation.
    Optional for backwards compatibility. Will be required in a future release.
    """
    @property
    def from_cache_info(self) -> global___CacheInfo:
        """Cache info to identify an unique cache repo that is persisted from."""

    @property
    def to_cache_info(self) -> global___CacheInfo:
        """Cache info to identify an unique cache repo that is persisted to. It will overwrite
        existing cache.
        """

    def __init__(
        self,
        *,
        from_cache_info: global___CacheInfo | None = ...,
        to_cache_info: global___CacheInfo | None = ...,
        cache_ttl_seconds: builtins.int = ...,
        account_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_account_id", b"_account_id", "account_id", b"account_id", "from_cache_info", b"from_cache_info", "to_cache_info", b"to_cache_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_account_id", b"_account_id", "account_id", b"account_id", "cache_ttl_seconds", b"cache_ttl_seconds", "from_cache_info", b"from_cache_info", "to_cache_info", b"to_cache_info"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_account_id", b"_account_id"]) -> typing.Literal["account_id"] | None: ...

global___PersistRequest = PersistRequest

@typing.final
class PersistResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPO_PATH_FIELD_NUMBER: builtins.int
    REPO_STATUS_FIELD_NUMBER: builtins.int
    @property
    def repo_path(self) -> global___RepoPath:
        """The path to the new persisted repo."""

    @property
    def repo_status(self) -> global___RepoStatus: ...
    def __init__(
        self,
        *,
        repo_path: global___RepoPath | None = ...,
        repo_status: global___RepoStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["repo_path", b"repo_path", "repo_status", b"repo_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["repo_path", b"repo_path", "repo_status", b"repo_status"]) -> None: ...

global___PersistResponse = PersistResponse

@typing.final
class ResourceInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    type: global___ResourceType.ValueType
    """The ResourceType requested"""
    path: builtins.str
    """Only relevant when ResourceType == PROJECT_FILE, path should be relative to repo name"""
    def __init__(
        self,
        *,
        type: global___ResourceType.ValueType = ...,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["path", b"path", "type", b"type"]) -> None: ...

global___ResourceInfo = ResourceInfo

@typing.final
class ListFilter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCE_INFO_FIELD_NUMBER: builtins.int
    @property
    def resource_info(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ResourceInfo]:
        """List of resources to return"""

    def __init__(
        self,
        *,
        resource_info: collections.abc.Iterable[global___ResourceInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["resource_info", b"resource_info"]) -> None: ...

global___ListFilter = ListFilter

@typing.final
class ListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CACHE_INFO_FIELD_NUMBER: builtins.int
    FILTERS_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.int
    """Account ID for account-level validation.
    Optional for backwards compatibility. Will be required in a future release.
    """
    @property
    def cache_info(self) -> global___CacheInfo:
        """Cache info to identify an unique cache unit."""

    @property
    def filters(self) -> global___ListFilter:
        """filters for the request, if not supplied everything is returned"""

    def __init__(
        self,
        *,
        cache_info: global___CacheInfo | None = ...,
        filters: global___ListFilter | None = ...,
        account_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_account_id", b"_account_id", "_filters", b"_filters", "account_id", b"account_id", "cache_info", b"cache_info", "filters", b"filters"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_account_id", b"_account_id", "_filters", b"_filters", "account_id", b"account_id", "cache_info", b"cache_info", "filters", b"filters"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_account_id", b"_account_id"]) -> typing.Literal["account_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_filters", b"_filters"]) -> typing.Literal["filters"] | None: ...

global___ListRequest = ListRequest

@typing.final
class ListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ResourceMappingEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    RESOURCE_MAPPING_FIELD_NUMBER: builtins.int
    REPO_INFO_FIELD_NUMBER: builtins.int
    REPO_STATUS_FIELD_NUMBER: builtins.int
    @property
    def resource_mapping(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Map of file path -> blob path (we use 'PROJECT_ARCHIVE' instead of file path for the project zip)
        If it's empty the cache has not been created, upload is incomplete, or there were no results for filters
        """

    @property
    def repo_info(self) -> global___RepoInfo:
        """Info on the repo, if it's empty, the cache has not been created or upload is incomplete"""

    @property
    def repo_status(self) -> global___RepoStatus: ...
    def __init__(
        self,
        *,
        resource_mapping: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        repo_info: global___RepoInfo | None = ...,
        repo_status: global___RepoStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_repo_info", b"_repo_info", "repo_info", b"repo_info", "repo_status", b"repo_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_repo_info", b"_repo_info", "repo_info", b"repo_info", "repo_status", b"repo_status", "resource_mapping", b"resource_mapping"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_repo_info", b"_repo_info"]) -> typing.Literal["repo_info"] | None: ...

global___ListResponse = ListResponse
