# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/fields/dbt_jwt.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-dbtlabs/proto/private/v1/fields/dbt_jwt.proto\x12\tv1.fields\"\x1d\n\x0e\x44\x62tJwtProjects\x12\x0b\n\x03ids\x18\x01 \x03(\t\"\xe9\x01\n\x06\x44\x62tJwt\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0e\n\x06scopes\x18\x02 \x03(\t\x12\x0b\n\x03jti\x18\x03 \x01(\t\x12\x11\n\tissued_at\x18\x04 \x01(\x03\x12\x12\n\nexpires_at\x18\x05 \x01(\x03\x12\x0b\n\x03\x61ud\x18\x06 \x01(\t\x12\x0b\n\x03iss\x18\x07 \x01(\t\x12\x15\n\tclient_ip\x18\x08 \x01(\tB\x02\x18\x01\x12\x0b\n\x03sub\x18\t \x01(\x03\x12\x0e\n\x06\x66\x61mily\x18\n \x01(\t\x12\r\n\x05\x65mail\x18\x0b \x01(\t\x12+\n\x08projects\x18\x0c \x01(\x0b\x32\x19.v1.fields.DbtJwtProjectsB,Z*github.com/dbt-labs/proto-golang/v1/fieldsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.fields.dbt_jwt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/dbt-labs/proto-golang/v1/fields'
  _globals['_DBTJWT'].fields_by_name['client_ip']._loaded_options = None
  _globals['_DBTJWT'].fields_by_name['client_ip']._serialized_options = b'\030\001'
  _globals['_DBTJWTPROJECTS']._serialized_start=60
  _globals['_DBTJWTPROJECTS']._serialized_end=89
  _globals['_DBTJWT']._serialized_start=92
  _globals['_DBTJWT']._serialized_end=325
# @@protoc_insertion_point(module_scope)
