"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ExtendedAttributes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    id: builtins.str
    created_at: builtins.int
    updated_at: builtins.int
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        created_at: builtins.int = ...,
        updated_at: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "id", b"id", "updated_at", b"updated_at"]) -> None: ...

global___ExtendedAttributes = ExtendedAttributes
