"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GroupPermission(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    GROUP_ID_FIELD_NUMBER: builtins.int
    PERMISSION_SET_FIELD_NUMBER: builtins.int
    ALL_PROJECTS_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    WRITABLE_ENVIRONMENT_CATEGORIES_FIELD_NUMBER: builtins.int
    CREATED_AT_UTC_FIELD_NUMBER: builtins.int
    UPDATED_AT_UTC_FIELD_NUMBER: builtins.int
    id: builtins.str
    group_id: builtins.str
    permission_set: builtins.str
    all_projects: builtins.bool
    project_id: builtins.str
    created_at_utc: builtins.int
    updated_at_utc: builtins.int
    @property
    def writable_environment_categories(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        group_id: builtins.str = ...,
        permission_set: builtins.str = ...,
        all_projects: builtins.bool = ...,
        project_id: builtins.str = ...,
        writable_environment_categories: collections.abc.Iterable[builtins.str] | None = ...,
        created_at_utc: builtins.int = ...,
        updated_at_utc: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["all_projects", b"all_projects", "created_at_utc", b"created_at_utc", "group_id", b"group_id", "id", b"id", "permission_set", b"permission_set", "project_id", b"project_id", "updated_at_utc", b"updated_at_utc", "writable_environment_categories", b"writable_environment_categories"]) -> None: ...

global___GroupPermission = GroupPermission
