"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Invocation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    ARTIFACT_OBJECT_STORE_PATH_FIELD_NUMBER: builtins.int
    STARTED_AT_FIELD_NUMBER: builtins.int
    FINISHED_AT_FIELD_NUMBER: builtins.int
    DBT_VERSION_FIELD_NUMBER: builtins.int
    id: builtins.str
    """id of the invocation"""
    command: builtins.str
    """command and arguments for the invocation"""
    artifact_object_store_path: builtins.str
    """path in object storage where the artifacts are stored without the bucket name"""
    started_at: builtins.int
    """invocation started timestamp in microseconds (time the CLI server received the request)"""
    finished_at: builtins.int
    """invocation finished timestamp in microseconds"""
    dbt_version: builtins.str
    """version of dbt used for the invocation"""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        command: builtins.str = ...,
        artifact_object_store_path: builtins.str = ...,
        started_at: builtins.int = ...,
        finished_at: builtins.int = ...,
        dbt_version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["artifact_object_store_path", b"artifact_object_store_path", "command", b"command", "dbt_version", b"dbt_version", "finished_at", b"finished_at", "id", b"id", "started_at", b"started_at"]) -> None: ...

global___Invocation = Invocation
