"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class JobDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    CRON_FIELD_NUMBER: builtins.int
    DATE_DEFINITION_TYPE_FIELD_NUMBER: builtins.int
    TIME_DEFINITION_TYPE_FIELD_NUMBER: builtins.int
    EXECUTE_STEPS_FIELD_NUMBER: builtins.int
    TRIGGERS_SCHEDULE_FIELD_NUMBER: builtins.int
    TRIGGERS_GITHUB_WEBHOOK_FIELD_NUMBER: builtins.int
    DBT_VERSION_FIELD_NUMBER: builtins.int
    SETTINGS_TARGET_NAME_FIELD_NUMBER: builtins.int
    SETTINGS_THREADS_FIELD_NUMBER: builtins.int
    GENERATE_DOCS_FIELD_NUMBER: builtins.int
    EXECUTION_TIMEOUT_SECONDS_FIELD_NUMBER: builtins.int
    TRIGGERS_CUSTOM_BRANCH_ONLY_FIELD_NUMBER: builtins.int
    DEFERRING_JOB_DEFINITION_ID_FIELD_NUMBER: builtins.int
    LIFECYCLE_WEBHOOKS_FIELD_NUMBER: builtins.int
    LIFECYCLE_WEBHOOKS_URL_FIELD_NUMBER: builtins.int
    TRIGGERS_GIT_PROVIDER_WEBHOOK_FIELD_NUMBER: builtins.int
    RUN_GENERATE_SOURCES_FIELD_NUMBER: builtins.int
    JOB_TYPE_FIELD_NUMBER: builtins.int
    RUN_AUDIT_HELPER_FIELD_NUMBER: builtins.int
    RUN_COMPARE_CHANGES_FIELD_NUMBER: builtins.int
    RUN_LINT_FIELD_NUMBER: builtins.int
    ERRORS_ON_LINT_FAILURE_FIELD_NUMBER: builtins.int
    COMPARE_CHANGES_FLAGS_FIELD_NUMBER: builtins.int
    COST_OPTIMIZATION_FEATURES_FIELD_NUMBER: builtins.int
    id: builtins.str
    name: builtins.str
    created_at: builtins.int
    updated_at: builtins.int
    cron: builtins.str
    date_definition_type: builtins.str
    time_definition_type: builtins.str
    triggers_schedule: builtins.bool
    triggers_github_webhook: builtins.bool
    dbt_version: builtins.str
    settings_target_name: builtins.str
    settings_threads: builtins.int
    generate_docs: builtins.bool
    execution_timeout_seconds: builtins.int
    triggers_custom_branch_only: builtins.bool
    deferring_job_definition_id: builtins.str
    """self-referential"""
    lifecycle_webhooks: builtins.bool
    lifecycle_webhooks_url: builtins.str
    triggers_git_provider_webhook: builtins.bool
    run_generate_sources: builtins.bool
    job_type: builtins.str
    run_audit_helper: builtins.bool
    run_compare_changes: builtins.bool
    run_lint: builtins.bool
    errors_on_lint_failure: builtins.bool
    compare_changes_flags: builtins.str
    @property
    def execute_steps(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def cost_optimization_features(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        created_at: builtins.int = ...,
        updated_at: builtins.int = ...,
        cron: builtins.str = ...,
        date_definition_type: builtins.str = ...,
        time_definition_type: builtins.str = ...,
        execute_steps: collections.abc.Iterable[builtins.str] | None = ...,
        triggers_schedule: builtins.bool = ...,
        triggers_github_webhook: builtins.bool = ...,
        dbt_version: builtins.str = ...,
        settings_target_name: builtins.str = ...,
        settings_threads: builtins.int = ...,
        generate_docs: builtins.bool = ...,
        execution_timeout_seconds: builtins.int = ...,
        triggers_custom_branch_only: builtins.bool = ...,
        deferring_job_definition_id: builtins.str = ...,
        lifecycle_webhooks: builtins.bool = ...,
        lifecycle_webhooks_url: builtins.str = ...,
        triggers_git_provider_webhook: builtins.bool = ...,
        run_generate_sources: builtins.bool = ...,
        job_type: builtins.str = ...,
        run_audit_helper: builtins.bool = ...,
        run_compare_changes: builtins.bool = ...,
        run_lint: builtins.bool = ...,
        errors_on_lint_failure: builtins.bool = ...,
        compare_changes_flags: builtins.str = ...,
        cost_optimization_features: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["compare_changes_flags", b"compare_changes_flags", "cost_optimization_features", b"cost_optimization_features", "created_at", b"created_at", "cron", b"cron", "date_definition_type", b"date_definition_type", "dbt_version", b"dbt_version", "deferring_job_definition_id", b"deferring_job_definition_id", "errors_on_lint_failure", b"errors_on_lint_failure", "execute_steps", b"execute_steps", "execution_timeout_seconds", b"execution_timeout_seconds", "generate_docs", b"generate_docs", "id", b"id", "job_type", b"job_type", "lifecycle_webhooks", b"lifecycle_webhooks", "lifecycle_webhooks_url", b"lifecycle_webhooks_url", "name", b"name", "run_audit_helper", b"run_audit_helper", "run_compare_changes", b"run_compare_changes", "run_generate_sources", b"run_generate_sources", "run_lint", b"run_lint", "settings_target_name", b"settings_target_name", "settings_threads", b"settings_threads", "time_definition_type", b"time_definition_type", "triggers_custom_branch_only", b"triggers_custom_branch_only", "triggers_git_provider_webhook", b"triggers_git_provider_webhook", "triggers_github_webhook", b"triggers_github_webhook", "triggers_schedule", b"triggers_schedule", "updated_at", b"updated_at"]) -> None: ...

global___JobDefinition = JobDefinition
