"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ModelEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    ENVIRONMENT_ID_FIELD_NUMBER: builtins.int
    JOB_DEFINITION_ID_FIELD_NUMBER: builtins.int
    UNIQUE_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DATABASE_FIELD_NUMBER: builtins.int
    SCHEMA_FIELD_NUMBER: builtins.int
    ALIAS_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    SKIP_FIELD_NUMBER: builtins.int
    PACKAGE_NAME_FIELD_NUMBER: builtins.int
    COMPILE_STARTED_AT_FIELD_NUMBER: builtins.int
    COMPILE_COMPLETED_AT_FIELD_NUMBER: builtins.int
    EXECUTE_STARTED_AT_FIELD_NUMBER: builtins.int
    EXECUTE_COMPLETED_AT_FIELD_NUMBER: builtins.int
    EXECUTION_TIME_FIELD_NUMBER: builtins.int
    THREAD_ID_FIELD_NUMBER: builtins.int
    RUN_GENERATED_AT_FIELD_NUMBER: builtins.int
    RUN_ELAPSED_TIME_FIELD_NUMBER: builtins.int
    INVOCATION_ID_FIELD_NUMBER: builtins.int
    META_FIELD_NUMBER: builtins.int
    DBT_VERSION_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    PARENTS_MODELS_FIELD_NUMBER: builtins.int
    PARENTS_SOURCES_FIELD_NUMBER: builtins.int
    CHILDREN_L1_FIELD_NUMBER: builtins.int
    COLUMNS_FIELD_NUMBER: builtins.int
    STATS_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    RAW_SQL_FIELD_NUMBER: builtins.int
    COMPILED_SQL_FIELD_NUMBER: builtins.int
    LANGUAGE_FIELD_NUMBER: builtins.int
    DEPENDS_ON_FIELD_NUMBER: builtins.int
    RUN_RESULTS_FIELD_NUMBER: builtins.int
    MATERIALIZED_TYPE_FIELD_NUMBER: builtins.int
    PACKAGES_FIELD_NUMBER: builtins.int
    DBT_GROUP_FIELD_NUMBER: builtins.int
    ACCESS_FIELD_NUMBER: builtins.int
    STATE_SHA_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    run_id: builtins.str
    account_id: builtins.str
    project_id: builtins.str
    environment_id: builtins.str
    job_definition_id: builtins.str
    unique_id: builtins.str
    name: builtins.str
    database: builtins.str
    schema: builtins.str
    alias: builtins.str
    description: builtins.str
    error: builtins.str
    status: builtins.str
    skip: builtins.bool
    package_name: builtins.str
    execution_time: builtins.float
    thread_id: builtins.str
    run_elapsed_time: builtins.float
    invocation_id: builtins.str
    dbt_version: builtins.str
    type: builtins.str
    owner: builtins.str
    comment: builtins.str
    raw_sql: builtins.str
    compiled_sql: builtins.str
    language: builtins.str
    materialized_type: builtins.str
    dbt_group: builtins.str
    access: builtins.str
    state_sha: builtins.str
    @property
    def compile_started_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def compile_completed_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def execute_started_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def execute_completed_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def run_generated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def meta(self) -> google.protobuf.struct_pb2.Struct: ...
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def parents_models(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def parents_sources(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def children_l1(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def columns(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
    @property
    def stats(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
    @property
    def depends_on(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def run_results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
    @property
    def packages(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        run_id: builtins.str = ...,
        account_id: builtins.str = ...,
        project_id: builtins.str = ...,
        environment_id: builtins.str = ...,
        job_definition_id: builtins.str = ...,
        unique_id: builtins.str = ...,
        name: builtins.str = ...,
        database: builtins.str = ...,
        schema: builtins.str = ...,
        alias: builtins.str = ...,
        description: builtins.str = ...,
        error: builtins.str = ...,
        status: builtins.str = ...,
        skip: builtins.bool = ...,
        package_name: builtins.str = ...,
        compile_started_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        compile_completed_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        execute_started_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        execute_completed_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        execution_time: builtins.float = ...,
        thread_id: builtins.str = ...,
        run_generated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        run_elapsed_time: builtins.float = ...,
        invocation_id: builtins.str = ...,
        meta: google.protobuf.struct_pb2.Struct | None = ...,
        dbt_version: builtins.str = ...,
        tags: collections.abc.Iterable[builtins.str] | None = ...,
        parents_models: collections.abc.Iterable[builtins.str] | None = ...,
        parents_sources: collections.abc.Iterable[builtins.str] | None = ...,
        children_l1: collections.abc.Iterable[builtins.str] | None = ...,
        columns: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        stats: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        type: builtins.str = ...,
        owner: builtins.str = ...,
        comment: builtins.str = ...,
        raw_sql: builtins.str = ...,
        compiled_sql: builtins.str = ...,
        language: builtins.str = ...,
        depends_on: collections.abc.Iterable[builtins.str] | None = ...,
        run_results: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        materialized_type: builtins.str = ...,
        packages: collections.abc.Iterable[builtins.str] | None = ...,
        dbt_group: builtins.str = ...,
        access: builtins.str = ...,
        state_sha: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["compile_completed_at", b"compile_completed_at", "compile_started_at", b"compile_started_at", "created_at", b"created_at", "execute_completed_at", b"execute_completed_at", "execute_started_at", b"execute_started_at", "meta", b"meta", "run_generated_at", b"run_generated_at", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["access", b"access", "account_id", b"account_id", "alias", b"alias", "children_l1", b"children_l1", "columns", b"columns", "comment", b"comment", "compile_completed_at", b"compile_completed_at", "compile_started_at", b"compile_started_at", "compiled_sql", b"compiled_sql", "created_at", b"created_at", "database", b"database", "dbt_group", b"dbt_group", "dbt_version", b"dbt_version", "depends_on", b"depends_on", "description", b"description", "environment_id", b"environment_id", "error", b"error", "execute_completed_at", b"execute_completed_at", "execute_started_at", b"execute_started_at", "execution_time", b"execution_time", "invocation_id", b"invocation_id", "job_definition_id", b"job_definition_id", "language", b"language", "materialized_type", b"materialized_type", "meta", b"meta", "name", b"name", "owner", b"owner", "package_name", b"package_name", "packages", b"packages", "parents_models", b"parents_models", "parents_sources", b"parents_sources", "project_id", b"project_id", "raw_sql", b"raw_sql", "run_elapsed_time", b"run_elapsed_time", "run_generated_at", b"run_generated_at", "run_id", b"run_id", "run_results", b"run_results", "schema", b"schema", "skip", b"skip", "state_sha", b"state_sha", "stats", b"stats", "status", b"status", "tags", b"tags", "thread_id", b"thread_id", "type", b"type", "unique_id", b"unique_id", "updated_at", b"updated_at"]) -> None: ...

global___ModelEntry = ModelEntry
