"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class OAuthClient(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    CLIENT_NAME_FIELD_NUMBER: builtins.int
    REDIRECT_URIS_FIELD_NUMBER: builtins.int
    SOFTWARE_STATEMENT_VERIFIED_FIELD_NUMBER: builtins.int
    SOFTWARE_STATEMENT_ISSUER_FIELD_NUMBER: builtins.int
    IS_MANUAL_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    id: builtins.str
    client_id: builtins.str
    client_name: builtins.str
    redirect_uris: builtins.str
    software_statement_verified: builtins.bool
    software_statement_issuer: builtins.str
    is_manual: builtins.bool
    created_at: builtins.int
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        client_id: builtins.str = ...,
        client_name: builtins.str = ...,
        redirect_uris: builtins.str = ...,
        software_statement_verified: builtins.bool = ...,
        software_statement_issuer: builtins.str = ...,
        is_manual: builtins.bool = ...,
        created_at: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_id", b"client_id", "client_name", b"client_name", "created_at", b"created_at", "id", b"id", "is_manual", b"is_manual", "redirect_uris", b"redirect_uris", "software_statement_issuer", b"software_statement_issuer", "software_statement_verified", b"software_statement_verified"]) -> None: ...

global___OAuthClient = OAuthClient
