# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/fields/oauth_client.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2dbtlabs/proto/private/v1/fields/oauth_client.proto\x12\tv1.fields\"\xc7\x01\n\x0bOAuthClient\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x03 \x01(\t\x12\x15\n\rredirect_uris\x18\x04 \x01(\t\x12#\n\x1bsoftware_statement_verified\x18\x05 \x01(\x08\x12!\n\x19software_statement_issuer\x18\x06 \x01(\t\x12\x11\n\tis_manual\x18\x07 \x01(\x08\x12\x12\n\ncreated_at\x18\x08 \x01(\x03\x42,Z*github.com/dbt-labs/proto-golang/v1/fieldsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.fields.oauth_client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/dbt-labs/proto-golang/v1/fields'
  _globals['_OAUTHCLIENT']._serialized_start=66
  _globals['_OAUTHCLIENT']._serialized_end=265
# @@protoc_insertion_point(module_scope)
