"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PlatformMetadataCredentials(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    ADAPTER_VERSION_FIELD_NUMBER: builtins.int
    CONNECTION_ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    created_at: builtins.int
    updated_at: builtins.int
    adapter_version: builtins.str
    connection_id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        created_at: builtins.int = ...,
        updated_at: builtins.int = ...,
        adapter_version: builtins.str = ...,
        connection_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["adapter_version", b"adapter_version", "connection_id", b"connection_id", "created_at", b"created_at", "id", b"id", "updated_at", b"updated_at"]) -> None: ...

global___PlatformMetadataCredentials = PlatformMetadataCredentials
