"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RefreshToken(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JTI_FIELD_NUMBER: builtins.int
    TOKEN_HASH_FIELD_NUMBER: builtins.int
    TOKEN_VERSION_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    SCOPES_FIELD_NUMBER: builtins.int
    EXPIRES_AT_FIELD_NUMBER: builtins.int
    FAMILY_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    USER_EMAIL_FIELD_NUMBER: builtins.int
    jti: builtins.str
    token_hash: builtins.str
    token_version: builtins.str
    client_id: builtins.str
    expires_at: builtins.int
    family: builtins.str
    user_id: builtins.int
    user_email: builtins.str
    @property
    def scopes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        jti: builtins.str = ...,
        token_hash: builtins.str = ...,
        token_version: builtins.str = ...,
        client_id: builtins.str = ...,
        scopes: collections.abc.Iterable[builtins.str] | None = ...,
        expires_at: builtins.int = ...,
        family: builtins.str = ...,
        user_id: builtins.int = ...,
        user_email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_id", b"client_id", "expires_at", b"expires_at", "family", b"family", "jti", b"jti", "scopes", b"scopes", "token_hash", b"token_hash", "token_version", b"token_version", "user_email", b"user_email", "user_id", b"user_id"]) -> None: ...

global___RefreshToken = RefreshToken
