# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/fields/repository_gitlab.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7dbtlabs/proto/private/v1/fields/repository_gitlab.proto\x12\tv1.fields\"\x7f\n\x10RepositoryGitlab\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\x03\x12\x12\n\nupdated_at\x18\x07 \x01(\x03\x12\x19\n\x11gitlab_project_id\x18\x08 \x01(\t\x12\x1c\n\x14project_access_token\x18\t \x01(\tB,Z*github.com/dbt-labs/proto-golang/v1/fieldsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.fields.repository_gitlab_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/dbt-labs/proto-golang/v1/fields'
  _globals['_REPOSITORYGITLAB']._serialized_start=70
  _globals['_REPOSITORYGITLAB']._serialized_end=197
# @@protoc_insertion_point(module_scope)
