# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/fields/run_trigger.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1dbtlabs/proto/private/v1/fields/run_trigger.proto\x12\tv1.fields\"\xb8\x01\n\nRunTrigger\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x63\x61use\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\x03\x12\x16\n\x0e\x63\x61use_category\x18\x04 \x01(\t\x12\x17\n\x0fpull_request_id\x18\x05 \x01(\t\x12\x0f\n\x07git_sha\x18\x06 \x01(\t\x12\x39\n\x13run_reason_category\x18\x07 \x01(\x0e\x32\x1c.v1.fields.RunReasonCategory*\x8b\x01\n\x11RunReasonCategory\x12\x1b\n\x17RUN_REASON_CATEGORY_API\x10\x00\x12\x1a\n\x16RUN_REASON_CATEGORY_CI\x10\x01\x12!\n\x1dRUN_REASON_CATEGORY_SCHEDULED\x10\x02\x12\x1a\n\x16RUN_REASON_CATEGORY_UI\x10\x03\x42,Z*github.com/dbt-labs/proto-golang/v1/fieldsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.fields.run_trigger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/dbt-labs/proto-golang/v1/fields'
  _globals['_RUNREASONCATEGORY']._serialized_start=252
  _globals['_RUNREASONCATEGORY']._serialized_end=391
  _globals['_RUNTRIGGER']._serialized_start=65
  _globals['_RUNTRIGGER']._serialized_end=249
# @@protoc_insertion_point(module_scope)
