# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/fields/service_token.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3dbtlabs/proto/private/v1/fields/service_token.proto\x12\tv1.fields\"\xb1\x01\n\x0cServiceToken\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncreated_at\x18\x02 \x01(\x03\x12\x12\n\nupdated_at\x18\x03 \x01(\x03\x12\x0b\n\x03uid\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x11\n\x05token\x18\x06 \x01(\tB\x02\x18\x01\x12\x11\n\tlast_used\x18\x08 \x01(\x03\x12\x15\n\rmetadata_only\x18\n \x01(\x08\x12\x15\n\rwebhooks_only\x18\x0b \x01(\x08\x42,Z*github.com/dbt-labs/proto-golang/v1/fieldsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.fields.service_token_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/dbt-labs/proto-golang/v1/fields'
  _globals['_SERVICETOKEN'].fields_by_name['token']._loaded_options = None
  _globals['_SERVICETOKEN'].fields_by_name['token']._serialized_options = b'\030\001'
  _globals['_SERVICETOKEN']._serialized_start=67
  _globals['_SERVICETOKEN']._serialized_end=244
# @@protoc_insertion_point(module_scope)
