"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ServiceToken(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    UID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    LAST_USED_FIELD_NUMBER: builtins.int
    METADATA_ONLY_FIELD_NUMBER: builtins.int
    WEBHOOKS_ONLY_FIELD_NUMBER: builtins.int
    id: builtins.str
    created_at: builtins.int
    updated_at: builtins.int
    uid: builtins.str
    name: builtins.str
    token: builtins.str
    last_used: builtins.int
    metadata_only: builtins.bool
    webhooks_only: builtins.bool
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        created_at: builtins.int = ...,
        updated_at: builtins.int = ...,
        uid: builtins.str = ...,
        name: builtins.str = ...,
        token: builtins.str = ...,
        last_used: builtins.int = ...,
        metadata_only: builtins.bool = ...,
        webhooks_only: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "id", b"id", "last_used", b"last_used", "metadata_only", b"metadata_only", "name", b"name", "token", b"token", "uid", b"uid", "updated_at", b"updated_at", "webhooks_only", b"webhooks_only"]) -> None: ...

global___ServiceToken = ServiceToken
