# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/fields/user_group.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0dbtlabs/proto/private/v1/fields/user_group.proto\x12\tv1.fields\"\x8c\x01\n\tUserGroup\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x19\n\x11\x61ssign_by_default\x18\x03 \x01(\x08\x12\x1a\n\x12sso_mapping_groups\x18\x04 \x03(\t\x12\x16\n\x0e\x63reated_at_utc\x18\x05 \x01(\x03\x12\x16\n\x0eupdated_at_utc\x18\x06 \x01(\x03\x42,Z*github.com/dbt-labs/proto-golang/v1/fieldsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.fields.user_group_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/dbt-labs/proto-golang/v1/fields'
  _globals['_USERGROUP']._serialized_start=64
  _globals['_USERGROUP']._serialized_end=204
# @@protoc_insertion_point(module_scope)
