"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class WebhookDispatch(google.protobuf.message.Message):
    """a common schema for webhook dispatches"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Payload(google.protobuf.message.Message):
        """Payload encapsulates an HTTP payload, including headers and a
        body
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class Header(google.protobuf.message.Message):
            """Header is a key:value pair for an HTTP header"""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            value: builtins.str
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

        HEADERS_FIELD_NUMBER: builtins.int
        BODY_FIELD_NUMBER: builtins.int
        body: builtins.str
        """The body of the HTTP payload"""
        @property
        def headers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WebhookDispatch.Payload.Header]: ...
        def __init__(
            self,
            *,
            headers: collections.abc.Iterable[global___WebhookDispatch.Payload.Header] | None = ...,
            body: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["body", b"body", "headers", b"headers"]) -> None: ...

    EVENT_KEY_FIELD_NUMBER: builtins.int
    ATTEMPT_COUNT_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    RESPONSE_CODE_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    event_key: builtins.str
    """triggering event routing key"""
    attempt_count: builtins.int
    """number of POST attempts (can be 0)"""
    url: builtins.str
    """the url to be POSTed to"""
    response_code: builtins.int
    """POST response code (can be null)"""
    @property
    def request(self) -> global___WebhookDispatch.Payload:
        """the payload to be POSTed"""

    @property
    def response(self) -> global___WebhookDispatch.Payload:
        """POST response body (can be null)"""

    def __init__(
        self,
        *,
        event_key: builtins.str = ...,
        attempt_count: builtins.int = ...,
        url: builtins.str = ...,
        request: global___WebhookDispatch.Payload | None = ...,
        response_code: builtins.int = ...,
        response: global___WebhookDispatch.Payload | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["request", b"request", "response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["attempt_count", b"attempt_count", "event_key", b"event_key", "request", b"request", "response", b"response", "response_code", b"response_code", "url", b"url"]) -> None: ...

global___WebhookDispatch = WebhookDispatch
