# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbtlabs/proto/private/v1/fields/webhooks_subscription.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;dbtlabs/proto/private/v1/fields/webhooks_subscription.proto\x12\tv1.fields\"\xaf\x02\n\x14WebhooksSubscription\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1a\n\x12\x61\x63\x63ount_identifier\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0f\n\x07job_ids\x18\x05 \x03(\x03\x12\x13\n\x0b\x65vent_types\x18\x06 \x03(\t\x12\x12\n\nclient_url\x18\x07 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\t \x01(\x08\x12\x12\n\ncreated_at\x18\x0b \x01(\x03\x12\x12\n\nupdated_at\x18\x0c \x01(\x03\x12\x18\n\x10http_status_code\x18\r \x01(\x03\x12\x1a\n\rdispatched_at\x18\x0e \x01(\x03H\x00\x88\x01\x01\x12\x12\n\naccount_id\x18\x0f \x01(\x03\x42\x10\n\x0e_dispatched_atB,Z*github.com/dbt-labs/proto-golang/v1/fieldsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbtlabs.proto.private.v1.fields.webhooks_subscription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/dbt-labs/proto-golang/v1/fields'
  _globals['_WEBHOOKSSUBSCRIPTION']._serialized_start=75
  _globals['_WEBHOOKSSUBSCRIPTION']._serialized_end=378
# @@protoc_insertion_point(module_scope)
