"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CloudInvocation(google.protobuf.message.Message):
    """CloudInvocation is additional information about a Fusion CLI invocation that
    is available when the Fusion CLI is invoked in the dbt Cloud enviroment. It
    is emitted after the public Invocation event and adds additional decoration
    to that stream of events that are specific to the cloud environment.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DBT_CLOUD_ACCOUNT_IDENTIFIER_FIELD_NUMBER: builtins.int
    DBT_CLOUD_PROJECT_ID_FIELD_NUMBER: builtins.int
    DBT_CLOUD_ENVIRONMENT_ID_FIELD_NUMBER: builtins.int
    DBT_CLOUD_JOB_ID_FIELD_NUMBER: builtins.int
    DBT_CLOUD_ENVIRONMENT_TYPE_FIELD_NUMBER: builtins.int
    DBT_CLOUD_ENVIRONMENT_DEPLOYMENT_TYPE_FIELD_NUMBER: builtins.int
    DBT_CLOUD_JOB_TYPE_FIELD_NUMBER: builtins.int
    DBT_CLOUD_RUN_ID_FIELD_NUMBER: builtins.int
    DBT_CLOUD_RUN_REASON_FIELD_NUMBER: builtins.int
    DBT_CLOUD_RUN_REASON_CATEGORY_FIELD_NUMBER: builtins.int
    DBT_CLOUD_RUN_TRIGGER_CATEGORY_FIELD_NUMBER: builtins.int
    dbt_cloud_account_identifier: builtins.str
    """Globally unique account identifier in which the invokation is run.
    Comes from the DBT_CLOUD_ACCOUNT_IDENTIFIER environment variable.
    e.g. act_0g9JY6ZTSUNAQPG6WvLNYYdmYHW
    Required
    """
    dbt_cloud_project_id: builtins.str
    """Project identifier
    Comes from the DBT_CLOUD_PROJECT_ID environment variable.
    e.g. 672
    Required
    """
    dbt_cloud_environment_id: builtins.str
    """Unique identifier of the environment within the tenant.
    Comes from the DBT_CLOUD_ENVIRONMENT_ID environment variable.
    e.g. 2
    Required
    """
    dbt_cloud_job_id: builtins.str
    """Unique identifier of the job within the account identifier.
    Comes from the DBT_CLOUD_JOB_ID environment variable.
    e.g. 0
    """
    dbt_cloud_environment_type: builtins.str
    """The type of environment in dbt Cloud.
    Comes from the DBT_CLOUD_ENVIRONMENT_TYPE environment variable.
    e.g. development or deployment
    Required
    """
    dbt_cloud_environment_deployment_type: builtins.str
    """The type of deployment for the environment.
    Comes from the DBT_CLOUD_ENVIRONMENT_DEPLOYMENT_TYPE environment variable.
    e.g. production or staging
    """
    dbt_cloud_job_type: builtins.str
    """The job type as configured when the invocation ran
    Comes from the DBT_CLOUD_JOB_TYPE environment variable.
    e.g. ci, scheduled, merge, adaptive, etc.
    """
    dbt_cloud_run_id: builtins.str
    """The unique run identifier in dbt Cloud
    Comes from the DBT_CLOUD_RUN_ID environment variable.
    May be empty if executed from a development context
    """
    dbt_cloud_run_reason: builtins.str
    """Comes from DBT_CLOUD_RUN_REASON environment variable."""
    dbt_cloud_run_reason_category: builtins.str
    """Comes from DBT_CLOUD_RUN_REASON_CATEGORY environment variable."""
    dbt_cloud_run_trigger_category: builtins.str
    """Comes from DBT_CLOUD_RUN_TRIGGER_CATEGORY environment variable."""
    def __init__(
        self,
        *,
        dbt_cloud_account_identifier: builtins.str = ...,
        dbt_cloud_project_id: builtins.str = ...,
        dbt_cloud_environment_id: builtins.str = ...,
        dbt_cloud_job_id: builtins.str = ...,
        dbt_cloud_environment_type: builtins.str = ...,
        dbt_cloud_environment_deployment_type: builtins.str | None = ...,
        dbt_cloud_job_type: builtins.str | None = ...,
        dbt_cloud_run_id: builtins.str | None = ...,
        dbt_cloud_run_reason: builtins.str | None = ...,
        dbt_cloud_run_reason_category: builtins.str | None = ...,
        dbt_cloud_run_trigger_category: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_dbt_cloud_environment_deployment_type", b"_dbt_cloud_environment_deployment_type", "_dbt_cloud_job_type", b"_dbt_cloud_job_type", "_dbt_cloud_run_id", b"_dbt_cloud_run_id", "_dbt_cloud_run_reason", b"_dbt_cloud_run_reason", "_dbt_cloud_run_reason_category", b"_dbt_cloud_run_reason_category", "_dbt_cloud_run_trigger_category", b"_dbt_cloud_run_trigger_category", "dbt_cloud_environment_deployment_type", b"dbt_cloud_environment_deployment_type", "dbt_cloud_job_type", b"dbt_cloud_job_type", "dbt_cloud_run_id", b"dbt_cloud_run_id", "dbt_cloud_run_reason", b"dbt_cloud_run_reason", "dbt_cloud_run_reason_category", b"dbt_cloud_run_reason_category", "dbt_cloud_run_trigger_category", b"dbt_cloud_run_trigger_category"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_dbt_cloud_environment_deployment_type", b"_dbt_cloud_environment_deployment_type", "_dbt_cloud_job_type", b"_dbt_cloud_job_type", "_dbt_cloud_run_id", b"_dbt_cloud_run_id", "_dbt_cloud_run_reason", b"_dbt_cloud_run_reason", "_dbt_cloud_run_reason_category", b"_dbt_cloud_run_reason_category", "_dbt_cloud_run_trigger_category", b"_dbt_cloud_run_trigger_category", "dbt_cloud_account_identifier", b"dbt_cloud_account_identifier", "dbt_cloud_environment_deployment_type", b"dbt_cloud_environment_deployment_type", "dbt_cloud_environment_id", b"dbt_cloud_environment_id", "dbt_cloud_environment_type", b"dbt_cloud_environment_type", "dbt_cloud_job_id", b"dbt_cloud_job_id", "dbt_cloud_job_type", b"dbt_cloud_job_type", "dbt_cloud_project_id", b"dbt_cloud_project_id", "dbt_cloud_run_id", b"dbt_cloud_run_id", "dbt_cloud_run_reason", b"dbt_cloud_run_reason", "dbt_cloud_run_reason_category", b"dbt_cloud_run_reason_category", "dbt_cloud_run_trigger_category", b"dbt_cloud_run_trigger_category"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_dbt_cloud_environment_deployment_type", b"_dbt_cloud_environment_deployment_type"]) -> typing.Literal["dbt_cloud_environment_deployment_type"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_dbt_cloud_job_type", b"_dbt_cloud_job_type"]) -> typing.Literal["dbt_cloud_job_type"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_dbt_cloud_run_id", b"_dbt_cloud_run_id"]) -> typing.Literal["dbt_cloud_run_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_dbt_cloud_run_reason", b"_dbt_cloud_run_reason"]) -> typing.Literal["dbt_cloud_run_reason"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_dbt_cloud_run_reason_category", b"_dbt_cloud_run_reason_category"]) -> typing.Literal["dbt_cloud_run_reason_category"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_dbt_cloud_run_trigger_category", b"_dbt_cloud_run_trigger_category"]) -> typing.Literal["dbt_cloud_run_trigger_category"] | None: ...

global___CloudInvocation = CloudInvocation
